import type { PropFirm, Article } from '../types.ts';

export const propFirms: PropFirm[] = [
  {
    id: 'apex-trader-funding',
    name: 'Apex Trader Funding',
    shortName: 'Apex',
    logoUrl: 'https://logo.clearbit.com/apextraderfunding.com',
    officialWebsite: 'https://apextraderfunding.com',
    tagline: 'The Leader in Futures Funding',
    shortDescription: 'Premier futures prop firm with a simple one-step evaluation, no daily drawdown, and up to 20 accounts.',
    rating: 4.7,
    reviewCount: 13000,
    isFeatured: true,
    affiliateUrl: 'https://apextraderfunding.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['1-Step Challenge'],
    tradingInstruments: ['Futures'],
    categories: ['Futures'],
    payoutFrequency: 'Every 8 days',
    drawdownType: 'Trailing',
    evaluationProcessSummary: 'Offers a one-step evaluation process with no daily drawdown. Traders keep 100% of the first $25K profit per account.',
    minStartingCost: 147,
    geoRestrictions: 'Available worldwide.',
    overview: 'Founded in 2021, Apex Trader Funding is the most popular choice for futures traders, with over $579M in payouts.',
    pros: ["Simple one-step evaluation", "No daily drawdown limit", "Frequent huge discounts (80%+)", "Trade with up to 20 accounts"],
    cons: ["Trailing drawdown can be tricky", "Monthly subscription fee model"],
    details: { minFunding: 25000, maxFunding: 6000000, profitSplit: 90, maxDrawdown: 6, dailyDrawdown: 0, profitTarget: 6, minTradingDays: 7 },
    features: { scalingPlan: false, weekendHolding: false, newsTrading: true, expertAdvisors: false, fastPayouts: true, noTimeLimit: true },
    deal: {
      description: 'Get up to 80% off on all evaluation accounts.',
      isTopDeal: true,
    },
  },
  {
    id: 'ftmo',
    name: 'FTMO',
    shortName: 'FTMO',
    logoUrl: '/logos/ftmo-logo.svg',
    officialWebsite: 'https://ftmo.com',
    tagline: 'The Industry Standard for Forex Traders',
    shortDescription: 'One of the most recognized firms with a 2-step evaluation, scaling up to $2M and 80-90% profit splits.',
    rating: 4.8,
    reviewCount: 28000,
    isFeatured: true,
    affiliateUrl: 'https://ftmo.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['2-Step Challenge'],
    tradingInstruments: ['Forex', 'Indices', 'Commodities', 'Crypto', 'Stocks'],
    categories: ['Forex/CFD'],
    payoutFrequency: 'Bi-weekly',
    drawdownType: 'Static',
    evaluationProcessSummary: 'FTMO features a renowned 2-step evaluation process (Challenge and Verification) to test trading skills.',
    minStartingCost: 155,
    geoRestrictions: 'US clients accepted via OANDA.',
    overview: 'FTMO, founded in 2015, is a global leader in the prop trading industry. They offer funding up to $2M.',
    pros: ["Highly reputable and trusted brand", "Clear scaling plan up to $2M", "Excellent trader support"],
    cons: ["Rigorous 2-step evaluation can be difficult", "Strict on consistency rules"],
    details: { minFunding: 10000, maxFunding: 2000000, profitSplit: 90, maxDrawdown: 10, dailyDrawdown: 5, profitTarget: 10, minTradingDays: 4 },
    features: { scalingPlan: true, weekendHolding: true, newsTrading: true, expertAdvisors: true, fastPayouts: true, noTimeLimit: true },
    deal: {
      description: 'The industry standard challenge at a competitive price.',
      isTopDeal: true,
    },
  },
  {
    id: 'the-5-percenters',
    name: 'The 5%ers',
    shortName: '5%ers',
    logoUrl: '/logos/5ers-logo.svg',
    officialWebsite: 'https://the5ers.com',
    tagline: 'Hyper Growth, Bootcamp, and High Stakes Programs',
    shortDescription: 'Offers up to $4M in funding with unique evaluation models and profit splits up to 100%.',
    rating: 4.8,
    reviewCount: 18000,
    isFeatured: true,
    affiliateUrl: 'https://the5ers.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['Bootcamp', 'Hyper Growth', 'High Stakes'],
    tradingInstruments: ['Forex', 'Indices', 'Metals'],
    categories: ['Forex/CFD'],
    payoutFrequency: 'Bi-weekly',
    drawdownType: 'Static',
    evaluationProcessSummary: 'Provides various programs including Hyper Growth, a 3-step Bootcamp, and High Stakes.',
    minStartingCost: 39,
    geoRestrictions: 'Available worldwide.',
    overview: 'Founded in 2016, The 5%ers is a major player offering up to $4 million in funding.',
    pros: ["Massive scaling up to $4M", "Unique and flexible evaluation models", "Profit splits up to 100%"],
    cons: ["Bootcamp model has a learning curve"],
    details: { minFunding: 5000, maxFunding: 4000000, profitSplit: 100, maxDrawdown: 10, dailyDrawdown: 5, profitTarget: 8, minTradingDays: 0 },
    features: { scalingPlan: true, weekendHolding: true, newsTrading: true, expertAdvisors: true, fastPayouts: true, noTimeLimit: true },
    deal: {
      description: 'Join the popular Bootcamp program with special offers.',
      isTopDeal: true,
    },
  },
  {
    id: 'top-one-futures',
    name: 'Top One Futures',
    shortName: 'Top One',
    logoUrl: 'https://app.toponefutures.com/_nuxt/img/topoone-logo.6f6aef5.png',
    officialWebsite: 'https://toponefutures.com/',
    tagline: '2-Hour Auto-Payouts',
    shortDescription: 'A new 2025 entrant focused on instant sim trading and the fastest automated payouts in the futures market.',
    rating: 4.7,
    reviewCount: 1000,
    affiliateUrl: 'https://toponefutures.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: true,
    isUSFriendly: true,
    fundingModels: ['1-Step Challenge', 'Instant Sim'],
    tradingInstruments: ['Futures'],
    categories: ['Futures', 'Instant Funding'],
    payoutFrequency: '2h (auto)',
    drawdownType: 'Trailing',
    evaluationProcessSummary: 'Offers a 1-step evaluation or an instant sim funding model with no daily drawdown, designed for scalpers.',
    minStartingCost: 99,
    geoRestrictions: 'Available worldwide.',
    overview: 'Launched in 2025, Top One Futures is making a name for itself with extremely fast, 2-hour automated payouts.',
    pros: ["Fastest automated payouts (2 hours)", "Instant sim funding option", "No daily drawdown"],
    cons: ["Very new firm (launched 2025)", "Long-term viability unproven"],
    details: { minFunding: 25000, maxFunding: 250000, profitSplit: 90, maxDrawdown: 5, dailyDrawdown: 0, profitTarget: 6, minTradingDays: 1 },
    features: { scalingPlan: true, weekendHolding: false, newsTrading: true, expertAdvisors: false, fastPayouts: true, noTimeLimit: true },
  },
  {
    id: 'blusky-trading',
    name: 'BluSky Trading',
    shortName: 'BluSky',
    logoUrl: 'https://blusky.pro/wp-content/uploads/2024/12/BluSky-Logo-Banner-Transparent-Background-1-1.png',
    officialWebsite: 'https://blusky.pro/',
    tagline: 'Your Success Is Our Business.',
    shortDescription: 'Beginner-friendly futures firm with static drawdown options, no daily loss limit, and daily payouts available from day one.',
    rating: 4.7,
    reviewCount: 600,
    affiliateUrl: 'https://blusky.pro/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['1-Step Challenge'],
    tradingInstruments: ['Futures'],
    categories: ['Futures'],
    payoutFrequency: 'Daily',
    drawdownType: 'Static',
    evaluationProcessSummary: 'Offers a straightforward 1-step evaluation with a static drawdown (no trailing) and no daily loss limit.',
    minStartingCost: 85,
    geoRestrictions: 'Available worldwide.',
    overview: 'BluSky Trading is considered one of the top futures firms in 2025, especially for beginners.',
    pros: ["Beginner-friendly", "Static drawdown option (no trailing)", "No daily loss limit", "Daily payouts available"],
    cons: ["Lower max funding than some competitors", "Monthly subscription model"],
    details: { minFunding: 25000, maxFunding: 150000, profitSplit: 90, maxDrawdown: 5, dailyDrawdown: 0, profitTarget: 6, minTradingDays: 1 },
    features: { scalingPlan: true, weekendHolding: true, newsTrading: true, expertAdvisors: false, fastPayouts: true, noTimeLimit: true },
  },
  {
    id: 'my-funded-futures',
    name: 'My Funded Futures',
    shortName: 'MFFU',
    logoUrl: 'https://myfundedfutures.com/wp-content/uploads/2024/01/MFF-Logo.png',
    officialWebsite: 'https://myfundedfutures.com',
    tagline: 'Daily, Automated Payouts for Futures Traders',
    shortDescription: 'A futures-specialized firm known for its quick one-step evaluation, daily automated payouts, and trader-friendly model.',
    rating: 4.8,
    reviewCount: 10000,
    affiliateUrl: 'https://myfundedfutures.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['1-Step Challenge'],
    tradingInstruments: ['Futures', 'Commodities'],
    categories: ['Futures'],
    payoutFrequency: 'Daily',
    drawdownType: 'Trailing',
    evaluationProcessSummary: 'Provides a one-step evaluation with end-of-day trailing drawdown. Traders keep 100% of the first $10k.',
    minStartingCost: 99,
    geoRestrictions: 'Available worldwide.',
    overview: "My Funded Futures is a top-rated futures firm with over $81M in payouts, praised for its transparent rules.",
    pros: ["Daily, automated payouts", "Keep 100% of first $10k profit", "End-of-day trailing drawdown", "Free NinjaTrader license"],
    cons: ["Trailing drawdown can be difficult for some traders"],
    details: { minFunding: 50000, maxFunding: 600000, profitSplit: 100, maxDrawdown: 10, dailyDrawdown: 0, profitTarget: 6, minTradingDays: 1 },
    features: { scalingPlan: true, weekendHolding: false, newsTrading: true, expertAdvisors: false, fastPayouts: true, noTimeLimit: true },
  },
  {
    id: 'funding-pips',
    name: 'Funding Pips',
    shortName: 'Funding Pips',
    logoUrl: 'https://logo.clearbit.com/fundingpips.com',
    officialWebsite: 'https://fundingpips.com',
    tagline: 'Lightning-Fast Payouts in 4 Hours',
    shortDescription: 'Known for the fastest payouts in the industry. Offers flexible 1, 2, 3-step, and Zero-challenge options.',
    rating: 4.7,
    reviewCount: 31000,
    affiliateUrl: 'https://fundingpips.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: true,
    isUSFriendly: true,
    fundingModels: ['1-Step Challenge', '2-Step Challenge', '3-Step Challenge', 'Instant Funding'],
    tradingInstruments: ['Forex', 'Indices', 'Commodities', 'Crypto', 'Metals'],
    categories: ['Forex/CFD', 'Instant Funding'],
    payoutFrequency: '4h',
    drawdownType: 'Static',
    evaluationProcessSummary: 'Extremely flexible with multiple evaluation types, including a Zero-challenge option.',
    minStartingCost: 32,
    geoRestrictions: 'Available worldwide.',
    overview: "Funding Pips has disrupted the industry with its focus on payout speed, offering withdrawals in as little as 4 hours.",
    pros: ["Extremely fast payouts (4 hours)", "Multiple funding models including instant", "Very low entry fees", "EAs allowed"],
    cons: ["Consistency rule can be restrictive"],
    details: { minFunding: 5000, maxFunding: 300000, profitSplit: 100, maxDrawdown: 10, dailyDrawdown: 5, profitTarget: 8, minTradingDays: 0 },
    features: { scalingPlan: true, weekendHolding: true, newsTrading: true, expertAdvisors: true, fastPayouts: true, noTimeLimit: true },
  }
];

export const articles: Article[] = [
  {
    id: 'test-article',
    title: 'Test Article',
    summary: 'This is a test article',
    author: 'Test Author',
    publishedDate: '2024-01-01',
    imageUrl: 'https://via.placeholder.com/400x200',
    content: '<p>This is test content</p>'
  }
];
