import type { PropFirm, Article } from '../types.ts';

export const propFirms: PropFirm[] = [
  // Basic prop firms from AI Studio
  {
    id: 'ftmo',
    name: 'FTMO',
    shortName: 'FTMO',
    logoUrl: 'https://logo.clearbit.com/ftmo.com',
    officialWebsite: 'https://ftmo.com/',
    tagline: 'The Most Recognized Prop Firm',
    shortDescription: 'One of the most recognized firms with a 2-step evaluation, scaling up to $2M and 80-90% profit splits.',
    rating: 4.8,
    reviewCount: 28000,
    affiliateUrl: 'https://ftmo.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['2-Step Challenge'],
    tradingInstruments: ['Forex', 'Indices', 'Commodities'],
    categories: ['Forex/CFD'],
    payoutFrequency: 'Bi-weekly',
    drawdownType: 'Static',
    evaluationProcessSummary: 'Two-step evaluation process with scaling opportunities.',
    minStartingCost: 155,
    geoRestrictions: 'Available worldwide.',
    overview: 'FTMO is one of the most established and recognized prop trading firms in the industry. They offer a comprehensive 2-step evaluation process that allows traders to prove their skills and scale up to $2M in funding.',
    pros: ["Established reputation", "High funding limits", "Good profit splits", "US-friendly"],
    cons: ["Strict rules", "Two-step process"],
    details: { minFunding: 10000, maxFunding: 2000000, profitSplit: 90, maxDrawdown: 10, dailyDrawdown: 5, profitTarget: 10, minTradingDays: 4 },
    features: { scalingPlan: true, weekendHolding: true, newsTrading: true, expertAdvisors: true, fastPayouts: true, noTimeLimit: true },
    sources: ['Official website', 'Community reviews'],
    verificationStatus: 'verified',
    lastVerifiedAt: '2024-12-19',
  },
  {
    id: 'the-5-percenters',
    name: 'The 5%ers',
    shortName: 'The 5%ers',
    logoUrl: 'https://logo.clearbit.com/the5percenters.com',
    officialWebsite: 'https://the5percenters.com/',
    tagline: 'Unique Evaluation Models',
    shortDescription: 'Offers up to $4M in funding with unique evaluation models and profit splits up to 100%.',
    rating: 4.8,
    reviewCount: 18000,
    affiliateUrl: 'https://the5percenters.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['Bootcamp', 'Hyper Growth', 'High Stakes'],
    tradingInstruments: ['Forex', 'Indices', 'Commodities'],
    categories: ['Forex/CFD'],
    payoutFrequency: 'Bi-weekly',
    drawdownType: 'Static',
    evaluationProcessSummary: 'Multiple evaluation models including bootcamp and high stakes programs.',
    minStartingCost: 155,
    geoRestrictions: 'Available worldwide.',
    overview: 'The 5%ers offers unique evaluation models including bootcamp programs and high stakes challenges. They provide up to $4M in funding with profit splits up to 100%.',
    pros: ["High funding limits", "100% profit splits", "Multiple programs", "US-friendly"],
    cons: ["Complex evaluation process"],
    details: { minFunding: 4000, maxFunding: 4000000, profitSplit: 100, maxDrawdown: 8, dailyDrawdown: 4, profitTarget: 8, minTradingDays: 5 },
    features: { scalingPlan: true, weekendHolding: true, newsTrading: true, expertAdvisors: true, fastPayouts: true, noTimeLimit: true },
    sources: ['Official website', 'Community reviews'],
    verificationStatus: 'verified',
    lastVerifiedAt: '2024-12-19',
  },
  {
    id: 'apex-trader-funding',
    name: 'Apex Trader Funding',
    shortName: 'Apex',
    logoUrl: 'https://logo.clearbit.com/apextraderfunding.com',
    officialWebsite: 'https://apextraderfunding.com/',
    tagline: 'Premier Futures Prop Firm',
    shortDescription: 'Premier futures prop firm with a simple one-step evaluation, no daily drawdown, and up to 20 accounts.',
    rating: 4.7,
    reviewCount: 13000,
    affiliateUrl: 'https://apextraderfunding.com/?ref=FPG',
    fpgAffiliateCode: 'FPG',
    hasInstantFunding: false,
    isUSFriendly: true,
    fundingModels: ['1-Step Challenge'],
    tradingInstruments: ['Futures'],
    categories: ['Futures'],
    payoutFrequency: 'Weekly',
    drawdownType: 'Static',
    evaluationProcessSummary: 'Simple one-step evaluation with no daily drawdown requirements.',
    minStartingCost: 97,
    geoRestrictions: 'Available worldwide.',
    overview: 'Apex Trader Funding is a premier futures prop firm offering a simple one-step evaluation process with no daily drawdown requirements. Traders can manage up to 20 accounts.',
    pros: ["No daily drawdown", "Simple evaluation", "Multiple accounts", "US-friendly"],
    cons: ["Futures only", "Higher minimum cost"],
    details: { minFunding: 25000, maxFunding: 300000, profitSplit: 90, maxDrawdown: 6, dailyDrawdown: 0, profitTarget: 6, minTradingDays: 7 },
    features: { scalingPlan: true, weekendHolding: false, newsTrading: true, expertAdvisors: false, fastPayouts: true, noTimeLimit: true },
    sources: ['Official website', 'Community reviews'],
    verificationStatus: 'verified',
    lastVerifiedAt: '2024-12-19',
  }
];

export const articles: Article[] = [
  {
    id: 'getting-started',
    title: 'Getting Started with Prop Trading',
    summary: 'Learn the basics of proprietary trading and how to get started.',
    content: 'Proprietary trading, or prop trading, is when a firm provides capital to traders...',
    author: 'FPG Team',
    publishDate: '2024-01-15',
    readTime: 5,
    category: 'Beginner',
    difficulty: 'Easy',
    imageUrl: '/images/education/getting-started.png',
    tags: ['beginner', 'introduction', 'basics']
  }
];
