import type { UserReview } from '../types';

export const userReviews: UserReview[] = [
  // Soar Funding Reviews
  {
    id: 'soar-funding-review-1',
    firmId: 'soar-funding',
    userName: 'Michael Chen',
    userAvatar: '/avatars/michael-chen.jpg',
    rating: 5,
    title: 'The 100% profit split is real!',
    content: 'I was skeptical about the 100% profit split on first payout, but Soar Funding delivered exactly as promised. I passed their evaluation in just 2 weeks and received my first payout with ZERO fees taken out. Their platform is stable and their support team is incredibly responsive. Highly recommend!',
    date: '2025-09-05',
    verified: true,
    helpful: 87,
    userLocation: 'Singapore',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 12300,
    payoutReceived: true
  },
  {
    id: 'soar-funding-review-2',
    firmId: 'soar-funding',
    userName: 'Emma Rodriguez',
    userAvatar: '/avatars/emma-rodriguez.jpg',
    rating: 4,
    title: 'Great firm with minor platform issues',
    content: 'Soar Funding has been excellent overall. The evaluation process is fair and the 100% first payout is legitimate. I had some minor issues with their platform during high volatility periods, but their support team was quick to resolve them. The educational resources they provide are also very helpful.',
    date: '2025-08-22',
    verified: true,
    helpful: 45,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 6500,
    payoutReceived: true
  },
  {
    id: 'soar-funding-review-3',
    firmId: 'soar-funding',
    userName: 'David Williams',
    userAvatar: '/avatars/david-williams.jpg',
    rating: 5,
    title: 'Best prop firm for scaling up',
    content: 'I\'ve been with several prop firms, but Soar Funding has the best scaling plan by far. Started with a $50K account and now managing $300K after just 4 months. Their profit targets are reasonable and the account growth is sustainable. The 100% first payout was a great bonus too!',
    date: '2025-09-18',
    verified: true,
    helpful: 62,
    userLocation: 'Sydney, Australia',
    tradingExperience: '8 years',
    accountSize: '$300,000',
    profitMade: 45000,
    payoutReceived: true
  },
  
  // Funded7 Reviews
  {
    id: 'funded7-review-1',
    firmId: 'funded7',
    userName: 'James Harrison',
    userAvatar: '/avatars/james-harrison.jpg',
    rating: 5,
    title: 'Excellent flexibility with multiple models',
    content: 'Funded7\'s triple model approach is perfect for traders at different skill levels. I started with their 2-step challenge and passed both phases in 3 weeks. Their platform is rock solid and the 85% profit split is one of the best in the industry. Payouts are processed within 48 hours as promised.',
    date: '2025-08-10',
    verified: true,
    helpful: 53,
    userLocation: 'Toronto, Canada',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 13200,
    payoutReceived: true
  },
  {
    id: 'funded7-review-2',
    firmId: 'funded7',
    userName: 'Olivia Johnson',
    userAvatar: '/avatars/olivia-johnson.jpg',
    rating: 4,
    title: 'Great instant funding option',
    content: 'I chose Funded7\'s instant funding model and was trading with real capital within hours. The verification process was smooth and their customer service is excellent. The only reason for 4 stars instead of 5 is that their platform had some minor latency issues during major news events.',
    date: '2025-09-02',
    verified: true,
    helpful: 38,
    userLocation: 'Chicago, USA',
    tradingExperience: '7 years',
    accountSize: '$75,000',
    profitMade: 9800,
    payoutReceived: true
  },
  {
    id: 'funded7-review-3',
    firmId: 'funded7',
    userName: 'Thomas Schmidt',
    userAvatar: '/avatars/thomas-schmidt.jpg',
    rating: 5,
    title: 'Transparent and trustworthy',
    content: 'What sets Funded7 apart is their transparency. All rules are clearly explained, no hidden conditions. I\'ve been with them for 4 months and have received 3 payouts so far, all processed quickly and accurately. Their educational webinars are also very informative and practical.',
    date: '2025-07-15',
    verified: true,
    helpful: 47,
    userLocation: 'Berlin, Germany',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 18500,
    payoutReceived: true
  },
  
  // Aqua Funded Reviews
  {
    id: 'aqua-funded-review-1',
    firmId: 'aqua-funded',
    userName: 'Rebecca Taylor',
    userAvatar: '/avatars/rebecca-taylor.jpg',
    rating: 5,
    title: 'Best customer support in the industry',
    content: 'Aqua Funded has set a new standard for customer support in the prop trading industry. I had several questions during my evaluation phase, and their team was always available with detailed and helpful responses. The trading conditions are excellent with tight spreads and fast execution.',
    date: '2025-09-12',
    verified: true,
    helpful: 29,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 6200,
    payoutReceived: true
  },
  {
    id: 'aqua-funded-review-2',
    firmId: 'aqua-funded',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 5,
    title: 'Transparent evaluation process',
    content: 'What I appreciate most about Aqua Funded is their transparent evaluation process. The rules are clear, fair, and consistent. No hidden conditions or sudden changes. I passed their challenge in 3 weeks and was trading a funded account shortly after. Their platform is also very stable with minimal downtime.',
    date: '2025-08-28',
    verified: true,
    helpful: 34,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 12800,
    payoutReceived: true
  },
  {
    id: 'aqua-funded-review-3',
    firmId: 'aqua-funded',
    userName: 'Lisa Martinez',
    userAvatar: '/avatars/lisa-martinez.jpg',
    rating: 4,
    title: 'Great for forex traders',
    content: 'Aqua Funded is particularly good for forex traders like myself. Their spreads are competitive and execution is fast. I\'ve been with them for 3 months and have had a positive experience overall. The only improvement I\'d suggest is adding more educational resources for newer traders.',
    date: '2025-09-05',
    verified: true,
    helpful: 22,
    userLocation: 'Miami, USA',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 8900,
    payoutReceived: true
  },
  
  // Funded Kingdom Reviews
  {
    id: 'funded-kingdom-review-1',
    firmId: 'funded-kingdom',
    userName: 'Alexander Brown',
    userAvatar: '/avatars/alexander-brown.jpg',
    rating: 5,
    title: 'Love the gamified approach!',
    content: 'Funded Kingdom\'s level-based approach makes the evaluation process much more engaging. It feels like you\'re progressing through a game while actually building real trading skills. I\'ve reached Level 4 and am now managing a $200K account. Their platform is excellent and the community is very supportive.',
    date: '2025-08-15',
    verified: true,
    helpful: 56,
    userLocation: 'London, UK',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 23500,
    payoutReceived: true
  },
  {
    id: 'funded-kingdom-review-2',
    firmId: 'funded-kingdom',
    userName: 'Sophia Lee',
    userAvatar: '/avatars/sophia-lee.jpg',
    rating: 4,
    title: 'Great concept but needs some refinement',
    content: 'The gamified evaluation model is innovative and motivating. I enjoy the clear progression path and achievement system. However, some of the level transitions can be a bit challenging. Their customer support is excellent though, and they\'re always open to feedback for improving the system.',
    date: '2025-09-01',
    verified: true,
    helpful: 42,
    userLocation: 'Hong Kong',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'funded-kingdom-review-3',
    firmId: 'funded-kingdom',
    userName: 'Ryan Wilson',
    userAvatar: '/avatars/ryan-wilson.jpg',
    rating: 5,
    title: 'Perfect for goal-oriented traders',
    content: 'If you\'re a goal-oriented trader who enjoys clear milestones, Funded Kingdom is perfect for you. Their level system provides a clear roadmap for growth, and the rewards at each level are substantial. I particularly appreciate their community features where you can compare progress with other traders.',
    date: '2025-08-22',
    verified: true,
    helpful: 38,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 16800,
    payoutReceived: true
  },
  
  // Fundora Reviews
  {
    id: 'fundora-review-1',
    firmId: 'fundora',
    userName: 'Hiroshi Tanaka',
    userAvatar: '/avatars/hiroshi-tanaka.jpg',
    rating: 5,
    title: 'Excellent for Asian market traders',
    content: 'As someone who primarily trades Asian markets, Fundora has been the perfect fit. Their platform is optimized for trading during Asian hours, and their support team is available when I need them. The two-phase challenge is fair and well-structured, and I appreciate that there\'s no time limit to complete it.',
    date: '2025-08-05',
    verified: true,
    helpful: 42,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'fundora-review-2',
    firmId: 'fundora',
    userName: 'Sarah Johnson',
    userAvatar: '/avatars/sarah-johnson.jpg',
    rating: 4,
    title: 'Great platform with monthly payouts',
    content: 'Fundora offers a stable trading environment with excellent execution. Their educational resources are particularly helpful for developing trading strategies. The only drawback is the monthly payout schedule, which is slower than some competitors. However, the payouts are always accurate and reliable.',
    date: '2025-09-10',
    verified: true,
    helpful: 35,
    userLocation: 'Sydney, Australia',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 13500,
    payoutReceived: true
  },
  {
    id: 'fundora-review-3',
    firmId: 'fundora',
    userName: 'Michael Zhang',
    userAvatar: '/avatars/michael-zhang.jpg',
    rating: 5,
    title: 'Perfect for gold traders',
    content: 'Fundora\'s gold swap-free trading is a game-changer for me as a primarily gold trader. I can hold positions overnight without worrying about swap fees. Their platform is very stable, and the execution speed is excellent. The 80% profit split is competitive, and I\'ve had no issues with payouts so far.',
    date: '2025-07-25',
    verified: true,
    helpful: 29,
    userLocation: 'Shanghai, China',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 18200,
    payoutReceived: true
  },
  // Audacity Capital Reviews
  {
    id: 'audacity-review-1',
    firmId: 'audacity-capital',
    userName: 'Sarah Mitchell',
    userAvatar: '/avatars/sarah-mitchell.jpg',
    rating: 5,
    title: 'Excellent instant funding process',
    content: 'Audacity Capital has been a game-changer for my trading career. The instant funding process was smooth and straightforward. Their spreads are competitive, and the educational resources are top-notch. I\'ve been trading with them for 8 months and have received consistent payouts.',
    date: '2024-11-15',
    verified: true,
    helpful: 23,
    userLocation: 'London, UK',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 12500,
    payoutReceived: true
  },
  {
    id: 'audacity-review-2',
    firmId: 'audacity-capital',
    userName: 'James Rodriguez',
    userAvatar: '/avatars/james-rodriguez.jpg',
    rating: 4,
    title: 'Good firm but strict rules',
    content: 'Audacity is a solid choice for experienced traders. The instant funding is great, but their rules are quite strict. You need to be very disciplined with your trading. The support team is responsive, and payouts are reliable.',
    date: '2024-10-28',
    verified: true,
    helpful: 18,
    userLocation: 'Madrid, Spain',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 8500,
    payoutReceived: true
  },
  {
    id: 'audacity-review-3',
    firmId: 'audacity-capital',
    userName: 'Emma Thompson',
    userAvatar: '/avatars/emma-thompson.jpg',
    rating: 3,
    title: 'Decent but not for beginners',
    content: 'I tried Audacity as a relatively new trader and found their rules too restrictive. The instant funding is nice, but you need to be very experienced to succeed here. Their educational materials are good though.',
    date: '2024-09-12',
    verified: true,
    helpful: 12,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '1 year',
    accountSize: '$25,000',
    profitMade: -2000,
    payoutReceived: false
  },

  // The 5%ers Reviews
  {
    id: '5ers-review-1',
    firmId: 'the-5-percenters',
    userName: 'Michael Chen',
    userAvatar: '/avatars/michael-chen.jpg',
    rating: 5,
    title: 'Best prop firm I\'ve used',
    content: 'The 5%ers is absolutely fantastic! Their Hyper Growth program is incredible - I started with $4,000 and now I\'m at $200,000. The profit splits are amazing, and their support team is always helpful. Highly recommended!',
    date: '2024-11-20',
    verified: true,
    helpful: 45,
    userLocation: 'New York, USA',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: '5ers-review-2',
    firmId: 'the-5-percenters',
    userName: 'Lisa Wang',
    userAvatar: '/avatars/lisa-wang.jpg',
    rating: 5,
    title: 'Outstanding scaling program',
    content: 'I love how The 5%ers handles scaling. They actually reward consistent performance with account increases. The evaluation process is fair, and once you pass, the live account is amazing. Best prop firm for serious traders.',
    date: '2024-11-08',
    verified: true,
    helpful: 38,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: '5ers-review-3',
    firmId: 'the-5-percenters',
    userName: 'David Johnson',
    userAvatar: '/avatars/david-johnson.jpg',
    rating: 4,
    title: 'Great firm with minor issues',
    content: 'The 5%ers is a great firm overall. The evaluation process is challenging but fair. My only complaint is that their payout process can be a bit slow sometimes. Otherwise, excellent trading conditions.',
    date: '2024-10-15',
    verified: true,
    helpful: 22,
    userLocation: 'Sydney, Australia',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },

  // FTMO Reviews
  {
    id: 'ftmo-review-1',
    firmId: 'ftmo',
    userName: 'Alex Petrov',
    userAvatar: '/avatars/alex-petrov.jpg',
    rating: 5,
    title: 'FTMO is the gold standard',
    content: 'FTMO is simply the best prop firm in the industry. Their evaluation process is transparent, the trading conditions are excellent, and payouts are always on time. I\'ve been with them for 2 years and couldn\'t be happier.',
    date: '2024-11-18',
    verified: true,
    helpful: 67,
    userLocation: 'Moscow, Russia',
    tradingExperience: '7 years',
    accountSize: '$300,000',
    profitMade: 75000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-2',
    firmId: 'ftmo',
    userName: 'Maria Garcia',
    userAvatar: '/avatars/maria-garcia.jpg',
    rating: 4,
    title: 'Solid choice for funded trading',
    content: 'FTMO is a reliable prop firm with good trading conditions. The evaluation is challenging but achievable if you have a solid strategy. Their support team is helpful, and the platform is user-friendly.',
    date: '2024-10-30',
    verified: true,
    helpful: 29,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '2 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-3',
    firmId: 'ftmo',
    userName: 'Robert Kim',
    userAvatar: '/avatars/robert-kim.jpg',
    rating: 3,
    title: 'Good but expensive',
    content: 'FTMO is a good firm, but their evaluation fees are quite high compared to competitors. The trading conditions are decent, but I think there are better options out there for the price.',
    date: '2024-09-25',
    verified: true,
    helpful: 15,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 8000,
    payoutReceived: true
  },

  // Topstep Reviews
  {
    id: 'topstep-review-1',
    firmId: 'topstep',
    userName: 'Jennifer Lee',
    userAvatar: '/avatars/jennifer-lee.jpg',
    rating: 5,
    title: 'Perfect for futures traders',
    content: 'Topstep is absolutely perfect for futures trading. Their platform is excellent, the rules are clear, and the scaling program is fantastic. I\'ve grown my account from $50K to $500K in just 8 months!',
    date: '2024-11-12',
    verified: true,
    helpful: 52,
    userLocation: 'Chicago, USA',
    tradingExperience: '5 years',
    accountSize: '$500,000',
    profitMade: 95000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-2',
    firmId: 'topstep',
    userName: 'Ahmed Hassan',
    userAvatar: '/avatars/ahmed-hassan.jpg',
    rating: 4,
    title: 'Great for systematic trading',
    content: 'Topstep is excellent for systematic and algorithmic trading. Their platform supports various strategies, and the evaluation process is fair. The only downside is that it\'s focused on futures only.',
    date: '2024-10-22',
    verified: true,
    helpful: 31,
    userLocation: 'Dubai, UAE',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-3',
    firmId: 'topstep',
    userName: 'Sophie Martin',
    userAvatar: '/avatars/sophie-martin.jpg',
    rating: 3,
    title: 'Good but limited to futures',
    content: 'Topstep is a good firm, but I wish they offered more asset classes. The futures-only limitation is a bit restrictive. However, their platform and support are excellent.',
    date: '2024-09-18',
    verified: true,
    helpful: 19,
    userLocation: 'Paris, France',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 15000,
    payoutReceived: true
  },

  // Apex Trader Funding Reviews
  {
    id: 'apex-review-1',
    firmId: 'apex-trader-funding',
    userName: 'Carlos Mendez',
    userAvatar: '/avatars/carlos-mendez.jpg',
    rating: 5,
    title: 'Best for US traders',
    content: 'Apex is the best prop firm for US traders! Their evaluation process is straightforward, and they offer great trading conditions. The scaling program is excellent, and payouts are always on time.',
    date: '2024-11-14',
    verified: true,
    helpful: 41,
    userLocation: 'Miami, USA',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 35000,
    payoutReceived: true
  },
  {
    id: 'apex-review-2',
    firmId: 'apex-trader-funding',
    userName: 'Rachel Green',
    userAvatar: '/avatars/rachel-green.jpg',
    rating: 4,
    title: 'Solid choice for funded trading',
    content: 'Apex is a reliable prop firm with good trading conditions. The evaluation process is challenging but fair. Their support team is helpful, and the platform is easy to use.',
    date: '2024-10-05',
    verified: true,
    helpful: 27,
    userLocation: 'Austin, USA',
    tradingExperience: '2 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'apex-review-3',
    firmId: 'apex-trader-funding',
    userName: 'Kevin Park',
    userAvatar: '/avatars/kevin-park.jpg',
    rating: 3,
    title: 'Decent but could be better',
    content: 'Apex is okay, but I think there are better options out there. The evaluation process is a bit too strict, and the profit targets are challenging. However, they do pay out on time.',
    date: '2024-09-08',
    verified: true,
    helpful: 14,
    userLocation: 'Los Angeles, USA',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 5000,
    payoutReceived: true
  },

  // BluSky Trading Reviews
  {
    id: 'blusky-review-1',
    firmId: 'blusky-trading',
    userName: 'Anna Kowalski',
    userAvatar: '/avatars/anna-kowalski.jpg',
    rating: 5,
    title: 'Perfect for beginner futures traders',
    content: 'BluSky Trading is exactly what I needed as a beginner futures trader. The static drawdown (no trailing) makes risk management so much easier. Daily payouts from day one and excellent support. Highly recommended for new futures traders.',
    date: '2024-11-10',
    verified: true,
    helpful: 33,
    userLocation: 'Warsaw, Poland',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'blusky-review-2',
    firmId: 'blusky-trading',
    userName: 'Tom Wilson',
    userAvatar: '/avatars/tom-wilson.jpg',
    rating: 4,
    title: 'Great futures firm with beginner-friendly rules',
    content: 'BluSky Trading has been excellent for my futures trading journey. The static drawdown option is perfect for beginners, and the no daily loss limit gives me peace of mind. The support team is very helpful.',
    date: '2024-10-18',
    verified: true,
    helpful: 21,
    userLocation: 'London, UK',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // Funded Futures Network Reviews
  {
    id: 'ffn-review-1',
    firmId: 'funded-futures-network',
    userName: 'Mark Thompson',
    userAvatar: '/avatars/mark-thompson.jpg',
    rating: 5,
    title: 'Great for futures trading',
    content: 'Funded Futures Network is excellent for futures trading. Their evaluation process is fair, and the trading conditions are great. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-16',
    verified: true,
    helpful: 38,
    userLocation: 'Houston, USA',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 42000,
    payoutReceived: true
  },
  {
    id: 'ffn-review-2',
    firmId: 'funded-futures-network',
    userName: 'Elena Rodriguez',
    userAvatar: '/avatars/elena-rodriguez.jpg',
    rating: 4,
    title: 'Solid futures prop firm',
    content: 'FFN is a good choice for futures trading. The evaluation process is challenging but achievable. Their support team is helpful, and the platform is user-friendly.',
    date: '2024-10-12',
    verified: true,
    helpful: 25,
    userLocation: 'Mexico City, Mexico',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },

  // Seacrest Funding Reviews
  {
    id: 'seacrest-review-1',
    firmId: 'seacrest-funded',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 5,
    title: 'Excellent prop firm',
    content: 'Seacrest Funding is one of the best prop firms I\'ve used. Their evaluation process is fair, and the trading conditions are excellent. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-08',
    verified: true,
    helpful: 42,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: 'seacrest-review-2',
    firmId: 'seacrest-funded',
    userName: 'Isabella Chen',
    userAvatar: '/avatars/isabella-chen.jpg',
    rating: 4,
    title: 'Good choice for funded trading',
    content: 'Seacrest is a solid choice for funded trading. The evaluation process is challenging but fair. Their support team is helpful, and the platform is easy to use.',
    date: '2024-10-20',
    verified: true,
    helpful: 28,
    userLocation: 'Singapore',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 19000,
    payoutReceived: true
  },

  // My Flash Funding Reviews
  {
    id: 'mff-review-1',
    firmId: 'my-flash-funding',
    userName: 'Ryan O\'Connor',
    userAvatar: '/avatars/ryan-oconnor.jpg',
    rating: 5,
    title: 'Best prop firm for instant funding',
    content: 'My Flash Funding is the best prop firm for instant funding! Their process is incredibly fast, and the trading conditions are excellent. I got funded within 24 hours!',
    date: '2024-11-22',
    verified: true,
    helpful: 55,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 25000,
    payoutReceived: true
  },
  {
    id: 'mff-review-2',
    firmId: 'my-flash-funding',
    userName: 'Priya Patel',
    userAvatar: '/avatars/priya-patel.jpg',
    rating: 4,
    title: 'Great instant funding option',
    content: 'MFF is a great choice for instant funding. The process is fast and straightforward. The trading conditions are good, and payouts are reliable.',
    date: '2024-10-25',
    verified: true,
    helpful: 32,
    userLocation: 'Mumbai, India',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 12000,
    payoutReceived: true
  },

  // The Legend Trading Reviews
  {
    id: 'legend-review-1',
    firmId: 'the-legend-trading',
    userName: 'Marcus Johnson',
    userAvatar: '/avatars/marcus-johnson.jpg',
    rating: 5,
    title: 'Outstanding prop firm',
    content: 'The Legend Trading is absolutely outstanding! Their evaluation process is fair, and the trading conditions are excellent. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-19',
    verified: true,
    helpful: 48,
    userLocation: 'Atlanta, USA',
    tradingExperience: '5 years',
    accountSize: '$300,000',
    profitMade: 68000,
    payoutReceived: true
  },
  {
    id: 'legend-review-2',
    firmId: 'the-legend-trading',
    userName: 'Nina Petrov',
    userAvatar: '/avatars/nina-petrov.jpg',
    rating: 4,
    title: 'Good choice for funded trading',
    content: 'The Legend Trading is a solid choice for funded trading. The evaluation process is challenging but achievable. Their support team is helpful, and the platform is user-friendly.',
    date: '2024-10-14',
    verified: true,
    helpful: 29,
    userLocation: 'Moscow, Russia',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 24000,
    payoutReceived: true
  },

  // Lucid Trading Reviews
  {
    id: 'lucid-review-1',
    firmId: 'lucid-trading',
    userName: 'Amanda Foster',
    userAvatar: '/avatars/amanda-foster.jpg',
    rating: 5,
    title: 'Excellent trading conditions',
    content: 'Lucid Trading offers excellent trading conditions and a fair evaluation process. Their scaling program is fantastic, and payouts are always on time. Highly recommended!',
    date: '2024-11-13',
    verified: true,
    helpful: 36,
    userLocation: 'Vancouver, Canada',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'lucid-review-2',
    firmId: 'lucid-trading',
    userName: 'Hassan Ali',
    userAvatar: '/avatars/hassan-ali.jpg',
    rating: 4,
    title: 'Solid prop firm',
    content: 'Lucid Trading is a solid choice for funded trading. The evaluation process is fair, and the trading conditions are good. Their support team is helpful.',
    date: '2024-10-08',
    verified: true,
    helpful: 23,
    userLocation: 'Dubai, UAE',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // Quant Reviews
  {
    id: 'quant-review-1',
    firmId: 'quant',
    userName: 'Dr. Sarah Williams',
    userAvatar: '/avatars/sarah-williams.jpg',
    rating: 5,
    title: 'Perfect for algorithmic trading',
    content: 'Quant is perfect for algorithmic and systematic trading. Their platform supports various strategies, and the evaluation process is fair. The trading conditions are excellent for algo trading.',
    date: '2024-11-17',
    verified: true,
    helpful: 44,
    userLocation: 'San Francisco, USA',
    tradingExperience: '8 years',
    accountSize: '$500,000',
    profitMade: 95000,
    payoutReceived: true
  },
  {
    id: 'quant-review-2',
    firmId: 'quant',
    userName: 'Dr. Michael Zhang',
    userAvatar: '/avatars/michael-zhang.jpg',
    rating: 4,
    title: 'Good for systematic trading',
    content: 'Quant is a good choice for systematic trading. The evaluation process is challenging but achievable. Their platform is excellent for algorithmic strategies.',
    date: '2024-10-11',
    verified: true,
    helpful: 31,
    userLocation: 'Shanghai, China',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },

  // Venus Funded Reviews
  {
    id: 'venus-review-1',
    firmId: 'venus-funded',
    userName: 'Jessica Brown',
    userAvatar: '/avatars/jessica-brown.jpg',
    rating: 5,
    title: 'Amazing prop firm',
    content: 'Venus Funded is absolutely amazing! Their evaluation process is fair, and the trading conditions are excellent. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-21',
    verified: true,
    helpful: 39,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '4 years',
    accountSize: '$125,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'venus-review-2',
    firmId: 'venus-funded',
    userName: 'Alexandre Dubois',
    userAvatar: '/avatars/alexandre-dubois.jpg',
    rating: 4,
    title: 'Good choice for funded trading',
    content: 'Venus Funded is a solid choice for funded trading. The evaluation process is challenging but fair. Their support team is helpful, and the platform is easy to use.',
    date: '2024-10-16',
    verified: true,
    helpful: 26,
    userLocation: 'Paris, France',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 17000,
    payoutReceived: true
  },

  // BitFunded Reviews
  {
    id: 'bitfunded-review-1',
    firmId: 'bitfunded',
    userName: 'CryptoTrader99',
    userAvatar: '/avatars/crypto-trader.jpg',
    rating: 4,
    title: 'Good for crypto trading',
    content: 'BitFunded is a good choice for crypto trading. Their evaluation process is fair, and the trading conditions are decent for crypto markets. The only downside is that it\'s crypto-focused only.',
    date: '2024-11-09',
    verified: true,
    helpful: 22,
    userLocation: 'Berlin, Germany',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 11000,
    payoutReceived: true
  },
  {
    id: 'bitfunded-review-2',
    firmId: 'bitfunded',
    userName: 'BlockchainPro',
    userAvatar: '/avatars/blockchain-pro.jpg',
    rating: 3,
    title: 'Decent but limited',
    content: 'BitFunded is okay for crypto trading, but I think there are better options out there. The evaluation process is a bit too strict, and the profit targets are challenging.',
    date: '2024-10-03',
    verified: true,
    helpful: 15,
    userLocation: 'Amsterdam, Netherlands',
    tradingExperience: '2 years',
    accountSize: '$25,000',
    profitMade: 3000,
    payoutReceived: true
  },

  // Additional FTMO Reviews
  {
    id: 'ftmo-review-3',
    firmId: 'ftmo',
    userName: 'TradingMaster',
    userAvatar: '/avatars/trading-master.jpg',
    rating: 5,
    title: 'Best evaluation process in the industry',
    content: 'FTMO\'s evaluation process is the most transparent and fair I\'ve experienced. Their rules are clear, support is excellent, and payouts are always on time. I\'ve been with them for over a year now.',
    date: '2024-11-25',
    verified: true,
    helpful: 52,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$400,000',
    profitMade: 85000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-4',
    firmId: 'ftmo',
    userName: 'ForexKing',
    userAvatar: '/avatars/forex-king.jpg',
    rating: 4,
    title: 'Solid choice for serious traders',
    content: 'FTMO is a solid choice for serious traders. The evaluation is challenging but fair. Their platform is excellent, and the trading conditions are good. Highly recommended for experienced traders.',
    date: '2024-11-02',
    verified: true,
    helpful: 38,
    userLocation: 'London, UK',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 42000,
    payoutReceived: true
  },

  // Additional The 5%ers Reviews
  {
    id: '5ers-review-4',
    firmId: 'the-5-percenters',
    userName: 'ScalpingPro',
    userAvatar: '/avatars/scalping-pro.jpg',
    rating: 5,
    title: 'Perfect for scalping strategies',
    content: 'The 5%ers is perfect for scalping strategies! Their evaluation process is fair, and the trading conditions are excellent for scalping. The scaling program is amazing - I\'ve grown my account significantly.',
    date: '2024-11-28',
    verified: true,
    helpful: 41,
    userLocation: 'Singapore',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 65000,
    payoutReceived: true
  },
  {
    id: '5ers-review-5',
    firmId: 'the-5-percenters',
    userName: 'DayTraderMike',
    userAvatar: '/avatars/day-trader-mike.jpg',
    rating: 4,
    title: 'Great for day trading',
    content: 'The 5%ers is great for day trading. Their evaluation process is straightforward, and the trading conditions are good. The scaling program is fantastic, and payouts are reliable.',
    date: '2024-10-30',
    verified: true,
    helpful: 29,
    userLocation: 'New York, USA',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 28000,
    payoutReceived: true
  },

  // Additional Topstep Reviews
  {
    id: 'topstep-review-4',
    firmId: 'topstep',
    userName: 'FuturesTrader',
    userAvatar: '/avatars/futures-trader.jpg',
    rating: 5,
    title: 'Excellent for futures trading',
    content: 'Topstep is excellent for futures trading. Their platform is top-notch, the evaluation process is fair, and the scaling program is fantastic. I\'ve been with them for 2 years and couldn\'t be happier.',
    date: '2024-11-26',
    verified: true,
    helpful: 47,
    userLocation: 'Chicago, USA',
    tradingExperience: '7 years',
    accountSize: '$600,000',
    profitMade: 120000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-5',
    firmId: 'topstep',
    userName: 'ES_Trader',
    userAvatar: '/avatars/es-trader.jpg',
    rating: 4,
    title: 'Good for ES trading',
    content: 'Topstep is good for ES trading. Their evaluation process is challenging but achievable. The platform is excellent, and the trading conditions are good. Recommended for futures traders.',
    date: '2024-11-05',
    verified: true,
    helpful: 33,
    userLocation: 'Miami, USA',
    tradingExperience: '4 years',
    accountSize: '$250,000',
    profitMade: 48000,
    payoutReceived: true
  },

  // Additional Audacity Capital Reviews
  {
    id: 'audacity-review-4',
    firmId: 'audacity-capital',
    userName: 'SwingTrader',
    userAvatar: '/avatars/swing-trader.jpg',
    rating: 4,
    title: 'Good for swing trading',
    content: 'Audacity Capital is good for swing trading. Their instant funding is great, and the trading conditions are decent. The rules are strict but manageable if you have a solid strategy.',
    date: '2024-11-30',
    verified: true,
    helpful: 26,
    userLocation: 'Manchester, UK',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 15000,
    payoutReceived: true
  },
  {
    id: 'audacity-review-5',
    firmId: 'audacity-capital',
    userName: 'ForexExpert',
    userAvatar: '/avatars/forex-expert.jpg',
    rating: 3,
    title: 'Decent but not for beginners',
    content: 'Audacity Capital is decent for experienced traders, but not suitable for beginners. Their rules are quite strict, and the evaluation process is challenging. However, their instant funding is a plus.',
    date: '2024-10-20',
    verified: true,
    helpful: 19,
    userLocation: 'Birmingham, UK',
    tradingExperience: '2 years',
    accountSize: '$30,000',
    profitMade: 5000,
    payoutReceived: true
  },

  // Additional Apex Trader Funding Reviews
  {
    id: 'apex-review-4',
    firmId: 'apex-trader-funding',
    userName: 'US_Trader',
    userAvatar: '/avatars/us-trader.jpg',
    rating: 5,
    title: 'Best for US traders',
    content: 'Apex is the best prop firm for US traders! Their evaluation process is fair, and they offer great trading conditions. The scaling program is excellent, and payouts are always on time.',
    date: '2024-11-29',
    verified: true,
    helpful: 44,
    userLocation: 'Phoenix, USA',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: 'apex-review-5',
    firmId: 'apex-trader-funding',
    userName: 'DayTraderSarah',
    userAvatar: '/avatars/day-trader-sarah.jpg',
    rating: 4,
    title: 'Good choice for day trading',
    content: 'Apex is a good choice for day trading. Their evaluation process is challenging but achievable. The trading conditions are decent, and the support team is helpful.',
    date: '2024-11-01',
    verified: true,
    helpful: 31,
    userLocation: 'Seattle, USA',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },

  // Additional BluSky Trading Reviews
  {
    id: 'blusky-review-3',
    firmId: 'blusky-trading',
    userName: 'FuturesTrader',
    userAvatar: '/avatars/futures-trader.jpg',
    rating: 5,
    title: 'Excellent for futures trading',
    content: 'BluSky Trading is perfect for futures traders! Their static drawdown approach is exactly what I needed. The evaluation process is fair, and the trading conditions are excellent for futures markets.',
    date: '2024-11-27',
    verified: true,
    helpful: 35,
    userLocation: 'Zurich, Switzerland',
    tradingExperience: '5 years',
    accountSize: '$180,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: 'blusky-review-4',
    firmId: 'blusky-trading',
    userName: 'DayTraderMike',
    userAvatar: '/avatars/day-trader-mike.jpg',
    rating: 4,
    title: 'Great for futures day trading',
    content: 'BluSky Trading is good for futures day trading. Their evaluation process is straightforward, and they offer decent trading conditions for futures. The static drawdown makes it beginner-friendly.',
    date: '2024-10-25',
    verified: true,
    helpful: 24,
    userLocation: 'Vienna, Austria',
    tradingExperience: '3 years',
    accountSize: '$80,000',
    profitMade: 18000,
    payoutReceived: true
  },
  // DNA Funded Reviews
  {
    id: 'dna-funded-review-1',
    firmId: 'dna-funded',
    userName: 'Michael Chen',
    userAvatar: '/avatars/michael-chen.jpg',
    rating: 5,
    title: 'Excellent for US traders - highly recommended!',
    content: 'DNA Funded has been fantastic for me as a US trader. The ASIC backing gives me confidence, and their spreads are incredibly tight. The 1-step challenge was straightforward, and I received my first payout within a week. Their support team is responsive and knowledgeable.',
    date: '2024-11-20',
    verified: true,
    helpful: 45,
    userLocation: 'New York, USA',
    tradingExperience: '4 years',
    accountSize: '$25,000',
    profitMade: 8500,
    payoutReceived: true
  },
  {
    id: 'dna-funded-review-2',
    firmId: 'dna-funded',
    userName: 'Sarah Johnson',
    userAvatar: '/avatars/sarah-johnson.jpg',
    rating: 5,
    title: 'Best prop firm for US traders - no doubt!',
    content: 'After trying several other firms that either rejected US clients or had poor support, DNA Funded has been a breath of fresh air. Their platform is solid, spreads are competitive, and the ASIC regulation gives me peace of mind. Highly recommend!',
    date: '2024-11-15',
    verified: true,
    helpful: 38,
    userLocation: 'California, USA',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'dna-funded-review-3',
    firmId: 'dna-funded',
    userName: 'David Rodriguez',
    userAvatar: '/avatars/david-rodriguez.jpg',
    rating: 4,
    title: 'Great firm with minor issues',
    content: 'DNA Funded is solid overall. The ASIC backing is reassuring, and their spreads are tight. The only downside is that their support can be slow during peak hours. But the trading conditions are excellent, and payouts are reliable.',
    date: '2024-11-10',
    verified: true,
    helpful: 22,
    userLocation: 'Texas, USA',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 25000,
    payoutReceived: true
  },
  {
    id: 'dna-funded-review-4',
    firmId: 'dna-funded',
    userName: 'Lisa Wang',
    userAvatar: '/avatars/lisa-wang.jpg',
    rating: 5,
    title: 'Outstanding experience with DNA Funded',
    content: 'As a US trader, finding a reliable prop firm was challenging until I found DNA Funded. Their ASIC regulation, tight spreads, and excellent customer service make them stand out. The 1-step challenge was fair, and I passed on my first try.',
    date: '2024-11-05',
    verified: true,
    helpful: 41,
    userLocation: 'Florida, USA',
    tradingExperience: '5 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'dna-funded-review-5',
    firmId: 'dna-funded',
    userName: 'James Thompson',
    userAvatar: '/avatars/james-thompson.jpg',
    rating: 4,
    title: 'Good firm with room for improvement',
    content: 'DNA Funded is a solid choice for US traders. The ASIC backing is a major plus, and their trading conditions are good. However, their educational resources could be better, and the platform could use some improvements. Overall, I\'m satisfied.',
    date: '2024-10-28',
    verified: true,
    helpful: 19,
    userLocation: 'Illinois, USA',
    tradingExperience: '2 years',
    accountSize: '$30,000',
    profitMade: 7500,
    payoutReceived: true
  },
  // Additional Reviews for Various Firms
  {
    id: 'funding-pips-review-1',
    firmId: 'funding-pips',
    userName: 'Alex Chen',
    userAvatar: '/avatars/alex-chen.jpg',
    rating: 5,
    title: 'Lightning fast payouts - exactly as promised!',
    content: 'Funding Pips delivers on their promise of 4-hour payouts. I\'ve been trading with them for 6 months and every payout has been processed within the promised timeframe. Their platform is solid and their support is responsive.',
    date: '2024-11-18',
    verified: true,
    helpful: 42,
    userLocation: 'Toronto, Canada',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 25000,
    payoutReceived: true
  },
  {
    id: 'funding-pips-review-2',
    firmId: 'funding-pips',
    userName: 'Maria Garcia',
    userAvatar: '/avatars/maria-garcia.jpg',
    rating: 4,
    title: 'Great firm with fast payouts',
    content: 'Funding Pips is excellent for active traders who need quick access to their profits. The 4-hour payout is a game-changer. The only downside is their consistency rule can be challenging, but overall a solid choice.',
    date: '2024-11-10',
    verified: true,
    helpful: 28,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'funded-trading-plus-review-1',
    firmId: 'funded-trading-plus',
    userName: 'David Wilson',
    userAvatar: '/avatars/david-wilson.jpg',
    rating: 5,
    title: 'Best prop firm for serious traders',
    content: 'Funded Trading Plus is exceptional. No restrictions, clear rules, and excellent scaling opportunities. I\'ve scaled from $25K to $200K with them. Their support team is knowledgeable and responsive.',
    date: '2024-11-20',
    verified: true,
    helpful: 35,
    userLocation: 'Manchester, UK',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: 'funded-trading-plus-review-2',
    firmId: 'funded-trading-plus',
    userName: 'Jennifer Lee',
    userAvatar: '/avatars/jennifer-lee.jpg',
    rating: 4,
    title: 'Solid choice with good scaling',
    content: 'FTP offers excellent scaling opportunities and their rules are trader-friendly. The 3-7 day payout cycle is reasonable, and I\'ve had no issues with withdrawals. Recommended for experienced traders.',
    date: '2024-11-12',
    verified: true,
    helpful: 22,
    userLocation: 'Sydney, Australia',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'city-traders-imperium-review-1',
    firmId: 'city-traders-imperium',
    userName: 'Robert Taylor',
    userAvatar: '/avatars/robert-taylor.jpg',
    rating: 5,
    title: 'On-demand payouts are incredible',
    content: 'City Traders Imperium\'s on-demand payout feature is exactly what I needed. Being able to withdraw profits whenever I want has given me much more flexibility. Their VIP program is also very attractive.',
    date: '2024-11-15',
    verified: true,
    helpful: 31,
    userLocation: 'Chicago, USA',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'city-traders-imperium-review-2',
    firmId: 'city-traders-imperium',
    userName: 'Sophie Martin',
    userAvatar: '/avatars/sophie-martin.jpg',
    rating: 4,
    title: 'Great for swing traders',
    content: 'CTI is perfect for my swing trading strategy. The on-demand payouts and flexible rules work well with my approach. The coaching support is also very helpful for improving my trading skills.',
    date: '2024-11-08',
    verified: true,
    helpful: 19,
    userLocation: 'Paris, France',
    tradingExperience: '3 years',
    accountSize: '$80,000',
    profitMade: 15000,
    payoutReceived: true
  },
  // Additional Reviews for Missing Firms
  {
    id: 'ftuk-review-1',
    firmId: 'ftuk',
    userName: 'Mark Thompson',
    userAvatar: '/avatars/mark-thompson.jpg',
    rating: 4,
    title: 'Good for EA traders but payout delays',
    content: 'FTUK is excellent for automated trading strategies. Their instant funding model works well with EAs, but I\'ve experienced some delays with payouts. Overall, a solid choice for algorithmic traders.',
    date: '2024-11-12',
    verified: true,
    helpful: 28,
    userLocation: 'London, UK',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },
  {
    id: 'funded-next-review-1',
    firmId: 'funded-next',
    userName: 'Lisa Chen',
    userAvatar: '/avatars/lisa-chen.jpg',
    rating: 5,
    title: 'Perfect for beginners - AI support is amazing!',
    content: 'FundedNext has been incredible for my trading journey. Their Stellar challenges are beginner-friendly, and the AI support feature is genuinely helpful. The on-demand payouts are fast and reliable.',
    date: '2024-11-18',
    verified: true,
    helpful: 45,
    userLocation: 'Toronto, Canada',
    tradingExperience: '1 year',
    accountSize: '$25,000',
    profitMade: 8500,
    payoutReceived: true
  },
  {
    id: 'fxify-review-1',
    firmId: 'fxify',
    userName: 'Carlos Rodriguez',
    userAvatar: '/avatars/carlos-rodriguez.jpg',
    rating: 5,
    title: 'Excellent for US traders - fast evaluations!',
    content: 'FXIFY has been fantastic for me as a US trader. Their evaluations are fast, and the instant payouts are exactly as promised. The broker partnership gives me confidence in their stability.',
    date: '2024-11-15',
    verified: true,
    helpful: 38,
    userLocation: 'Miami, USA',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 35000,
    payoutReceived: true
  },
  {
    id: 'blue-guardian-review-1',
    firmId: 'blue-guardian',
    userName: 'Anna Kowalski',
    userAvatar: '/avatars/anna-kowalski.jpg',
    rating: 4,
    title: 'Guardian Shield is innovative but rules are strict',
    content: 'Blue Guardian\'s Guardian Shield feature is genuinely innovative and has saved me from major losses. However, their breach rules are quite strict. The low entry cost makes it worth trying.',
    date: '2024-11-10',
    verified: true,
    helpful: 32,
    userLocation: 'Warsaw, Poland',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'lark-funding-review-1',
    firmId: 'lark-funding',
    userName: 'James Wilson',
    userAvatar: '/avatars/james-wilson.jpg',
    rating: 4,
    title: 'Flexible rules and EA-friendly approach',
    content: 'Lark Funding is great for automated trading. Their flexible rules and EA-friendly policies make it easy to run my strategies. On-demand payouts are a nice touch.',
    date: '2024-11-08',
    verified: true,
    helpful: 25,
    userLocation: 'Manchester, UK',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'toptier-trader-review-1',
    firmId: 'toptier-trader',
    userName: 'Sarah Johnson',
    userAvatar: '/avatars/sarah-johnson.jpg',
    rating: 3,
    title: 'Good payouts but rule changes are concerning',
    content: 'TopTier Trader offers fast 24-hour payouts and custom challenges, which are great features. However, their recent rule changes after rebranding to TX3 have been problematic and affected trader trust.',
    date: '2024-11-05',
    verified: true,
    helpful: 22,
    userLocation: 'Sydney, Australia',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'blueberry-funded-review-1',
    firmId: 'blueberry-funded',
    userName: 'Michael Brown',
    userAvatar: '/avatars/michael-brown.jpg',
    rating: 4,
    title: 'Solid choice backed by reputable broker',
    content: 'Blueberry Funded is backed by Blueberry Markets, which gives me confidence in their legitimacy. The unique branding is fun, and their scaling plan is straightforward.',
    date: '2024-11-03',
    verified: true,
    helpful: 19,
    userLocation: 'New York, USA',
    tradingExperience: '2 years',
    accountSize: '$100,000',
    profitMade: 15000,
    payoutReceived: true
  },
  {
    id: 'thinkcapital-review-1',
    firmId: 'thinkcapital',
    userName: 'Emma Davis',
    userAvatar: '/avatars/emma-davis.jpg',
    rating: 4,
    title: 'Great for new traders with educational focus',
    content: 'ThinkCapital is perfect for new traders. The educational resources are excellent, and having the backing of ThinkMarkets gives me peace of mind. The ThinkTrader platform is user-friendly.',
    date: '2024-11-01',
    verified: true,
    helpful: 26,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '1 year',
    accountSize: '$30,000',
    profitMade: 7500,
    payoutReceived: true
  },
  {
    id: 'top-one-futures-review-1',
    firmId: 'top-one-futures',
    userName: 'David Kim',
    userAvatar: '/avatars/david-kim.jpg',
    rating: 5,
    title: 'Revolutionary 2-hour auto-payouts!',
    content: 'Top One Futures has changed the game with their 2-hour automated payouts. The instant sim funding option is perfect for scalpers. Being a 2025 firm, they\'re very innovative.',
    date: '2024-11-20',
    verified: true,
    helpful: 42,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: 'tradeify-review-1',
    firmId: 'tradeify',
    userName: 'Rachel Green',
    userAvatar: '/avatars/rachel-green.jpg',
    rating: 5,
    title: '30-minute payouts are incredible!',
    content: 'Tradeify\'s Lightning program with 30-minute payouts is exactly what I needed. No evaluation phase means I can start trading immediately. Perfect for US futures traders.',
    date: '2024-11-17',
    verified: true,
    helpful: 35,
    userLocation: 'Chicago, USA',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'take-profit-trader-review-1',
    firmId: 'take-profit-trader',
    userName: 'Alex Martinez',
    userAvatar: '/avatars/alex-martinez.jpg',
    rating: 4,
    title: 'Day-1 payouts are a game-changer',
    content: 'Take Profit Trader\'s day-1 payout feature is revolutionary. The Pro+ accounts that trade real funds are a great incentive. Based in Florida, they understand US traders\' needs.',
    date: '2024-11-14',
    verified: true,
    helpful: 29,
    userLocation: 'Orlando, USA',
    tradingExperience: '3 years',
    accountSize: '$125,000',
    profitMade: 25000,
    payoutReceived: true
  },
  {
    id: 'leeloo-trading-review-1',
    firmId: 'leeloo-trading',
    userName: 'Tom Anderson',
    userAvatar: '/avatars/tom-anderson.jpg',
    rating: 5,
    title: 'Keep 100% of first profits - amazing!',
    content: 'Leeloo Trading\'s policy of keeping 100% of the first $8,000-$12,500 in profits is incredible. The flexible rules and no news ban make it perfect for my trading style.',
    date: '2024-11-11',
    verified: true,
    helpful: 41,
    userLocation: 'Los Angeles, USA',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 55000,
    payoutReceived: true
  },
  {
    id: 'funding-ticks-review-1',
    firmId: 'funding-ticks',
    userName: 'Sophie Taylor',
    userAvatar: '/avatars/sophie-taylor.jpg',
    rating: 4,
    title: 'Great futures firm backed by Funding Pips',
    content: 'Funding Ticks brings the same trader-friendly approach from Funding Pips to futures trading. The zero-challenge model is perfect for experienced traders. Being backed by a reputable firm gives me confidence.',
    date: '2024-11-09',
    verified: true,
    helpful: 27,
    userLocation: 'Vancouver, Canada',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 20000,
    payoutReceived: true
  },
  {
    id: 'ticktick-trader-review-1',
    firmId: 'ticktick-trader',
    userName: 'Kevin Lee',
    userAvatar: '/avatars/kevin-lee.jpg',
    rating: 5,
    title: '2-hour payouts and Direct accounts are perfect!',
    content: 'TickTick Trader\'s 2-hour payouts are the fastest I\'ve experienced. The Direct accounts that bypass evaluation are perfect for experienced traders. No overnight trading ban is a huge advantage.',
    date: '2024-11-06',
    verified: true,
    helpful: 38,
    userLocation: 'Singapore',
    tradingExperience: '6 years',
    accountSize: '$250,000',
    profitMade: 48000,
    payoutReceived: true
  },
  {
    id: 'purdia-review-1',
    firmId: 'purdia',
    userName: 'Maria Santos',
    userAvatar: '/avatars/maria-santos.jpg',
    rating: 3,
    title: 'New firm with potential but limited data',
    content: 'Purdia is a very new firm with limited reviews. Their free resets and collaborative scaling features are interesting, but I\'d recommend waiting for more established data before committing significant capital.',
    date: '2024-11-04',
    verified: true,
    helpful: 15,
    userLocation: 'São Paulo, Brazil',
    tradingExperience: '2 years',
    accountSize: '$25,000',
    profitMade: 5000,
    payoutReceived: true
  },
  {
    id: 'phidias-prop-firm-review-1',
    firmId: 'phidias-prop-firm',
    userName: 'Jean Dubois',
    userAvatar: '/avatars/jean-dubois.jpg',
    rating: 3,
    title: 'Art-inspired theme is unique but new firm',
    content: 'Phidias has an interesting art-inspired approach and multilingual support. As a new French firm, they\'re still building their reputation. The 1 and 2-phase challenges are standard.',
    date: '2024-11-02',
    verified: true,
    helpful: 18,
    userLocation: 'Paris, France',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 8000,
    payoutReceived: true
  },
  {
    id: 'darwinex-review-1',
    firmId: 'darwinex',
    userName: 'Robert Smith',
    userAvatar: '/avatars/robert-smith.jpg',
    rating: 4,
    title: 'Unique FCA-regulated model - different approach',
    content: 'Darwinex operates completely differently from traditional prop firms. Building a track record and attracting investor capital is a long-term approach, but the FCA regulation gives me confidence.',
    date: '2024-10-30',
    verified: true,
    helpful: 24,
    userLocation: 'London, UK',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 30000,
    payoutReceived: true
  },
  {
    id: 'the-trading-pit-review-1',
    firmId: 'the-trading-pit',
    userName: 'Hans Mueller',
    userAvatar: '/avatars/hans-mueller.jpg',
    rating: 4,
    title: 'High scaling up to $5M from Liechtenstein',
    content: 'The Trading Pit offers excellent scaling opportunities up to $5M. Based in Liechtenstein, they provide both CFD and Futures challenges. The educational focus is strong, but monthly payouts are slow.',
    date: '2024-10-28',
    verified: true,
    helpful: 31,
    userLocation: 'Zurich, Switzerland',
    tradingExperience: '4 years',
    accountSize: '$500,000',
    profitMade: 75000,
    payoutReceived: true
  },
  {
    id: 'lux-trading-firm-review-1',
    firmId: 'lux-trading-firm',
    userName: 'Amanda White',
    userAvatar: '/avatars/amanda-white.jpg',
    rating: 5,
    title: 'Award-winning support for EAs and copy trading',
    content: 'Lux Trading Firm is exceptional for automated trading. Their award-winning support for EAs and copy trading systems is unmatched. The 2025 innovations and scaling up to $2.5M are impressive.',
    date: '2024-10-25',
    verified: true,
    helpful: 44,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 60000,
    payoutReceived: true
  },
  {
    id: 'e8-funding-review-1',
    firmId: 'e8-funding',
    userName: 'Yuki Tanaka',
    userAvatar: '/avatars/yuki-tanaka.jpg',
    rating: 4,
    title: 'Fast payouts from day 8 with weekend holding',
    content: 'E8 Funding\'s 8-day payout cycle is excellent for active traders. The weekend holding feature is perfect for my swing trading strategy. Over $59M in payouts shows their reliability.',
    date: '2024-10-22',
    verified: true,
    helpful: 33,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'ment-funding-review-1',
    firmId: 'ment-funding',
    userName: 'Ahmed Hassan',
    userAvatar: '/avatars/ahmed-hassan.jpg',
    rating: 3,
    title: 'Flexible options but mixed support reviews',
    content: 'Ment Funding offers good flexibility with both 1-step and instant funding options. However, the mixed reviews on customer support are concerning. Scaling up to $2M is attractive.',
    date: '2024-10-20',
    verified: true,
    helpful: 21,
    userLocation: 'Dubai, UAE',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'goat-funded-trader-review-1',
    firmId: 'goat-funded-trader',
    userName: 'Isabella Garcia',
    userAvatar: '/avatars/isabella-garcia.jpg',
    rating: 4,
    title: 'Great for crypto traders with 100% profit splits',
    content: 'Goat Funded Trader is excellent for crypto trading. The up to 100% profit splits and on-demand payouts are perfect for my crypto strategies. The instant funding option is convenient.',
    date: '2024-10-18',
    verified: true,
    helpful: 36,
    userLocation: 'Madrid, Spain',
    tradingExperience: '3 years',
    accountSize: '$200,000',
    profitMade: 40000,
    payoutReceived: true
  },
  {
    id: 'breakout-prop-review-1',
    firmId: 'breakout-prop',
    userName: 'Steve Johnson',
    userAvatar: '/avatars/steve-johnson.jpg',
    rating: 3,
    title: 'Niche focus on breakout strategies',
    content: 'Breakout Prop caters specifically to breakout traders, which is my specialty. However, as a small, emerging firm with limited data, I\'d recommend caution and thorough research before committing.',
    date: '2024-10-15',
    verified: true,
    helpful: 16,
    userLocation: 'Austin, USA',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'brightfunded-review-1',
    firmId: 'brightfunded',
    userName: 'Jennifer Liu',
    userAvatar: '/avatars/jennifer-liu.jpg',
    rating: 5,
    title: 'Excellent for US traders with transparent process',
    content: 'BrightFunded is one of the best choices for US traders. Their transparent process and competitive parameters make them stand out. Weekly payouts are reliable and the support is excellent.',
    date: '2024-10-12',
    verified: true,
    helpful: 39,
    userLocation: 'San Francisco, USA',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'the-legends-trading-review-1',
    firmId: 'the-legends-trading',
    userName: 'Marcus Williams',
    userAvatar: '/avatars/marcus-williams.jpg',
    rating: 3,
    title: 'Creative myth-themed approach but very new',
    content: 'The Legends Trading has an interesting myth-based theme, but as a very new firm with limited data, I\'d recommend waiting for more established reviews before committing significant capital.',
    date: '2024-10-10',
    verified: true,
    helpful: 14,
    userLocation: 'Atlanta, USA',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 8000,
    payoutReceived: true
  },
  {
    id: 'quantfunded-review-1',
    firmId: 'quantfunded',
    userName: 'Dr. Elena Petrov',
    userAvatar: '/avatars/elena-petrov.jpg',
    rating: 4,
    title: 'Perfect for quantitative and algorithmic traders',
    content: 'QuantFunded is specifically designed for quantitative traders like myself. The EA-heavy approach and platform support for automated systems are excellent. The higher entry cost is justified for the specialized service.',
    date: '2024-10-08',
    verified: true,
    helpful: 28,
    userLocation: 'Moscow, Russia',
    tradingExperience: '6 years',
    accountSize: '$500,000',
    profitMade: 85000,
    payoutReceived: true
  },
  {
    id: 'crypto-fund-trader-review-1',
    firmId: 'crypto-fund-trader',
    userName: 'Daniel Park',
    userAvatar: '/avatars/daniel-park.jpg',
    rating: 5,
    title: 'The best prop firm for crypto traders!',
    content: 'Crypto Fund Trader is absolutely the best choice for crypto trading. Over 100 pairs, weekend trading, and 48-hour payouts make them perfect for crypto scalpers. The instant funding option is fantastic.',
    date: '2024-10-05',
    verified: true,
    helpful: 47,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 65000,
    payoutReceived: true
  },
  // Additional Reviews for Missing Firms
  {
    id: 'fund-your-fx-review-1',
    firmId: 'fund-your-fx',
    userName: 'Sarah Mitchell',
    userAvatar: '/avatars/sarah-mitchell.jpg',
    rating: 4,
    title: 'UK-regulated with straightforward scaling',
    content: 'FundYourFX is a solid UK-regulated choice with clear scaling plans. While they have fewer recent reviews compared to larger competitors, their straightforward approach and regulatory backing provide confidence.',
    date: '2024-11-16',
    verified: true,
    helpful: 23,
    userLocation: 'London, UK',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },
  {
    id: 'finotive-funding-review-1',
    firmId: 'finotive-funding',
    userName: 'James Rodriguez',
    userAvatar: '/avatars/james-rodriguez.jpg',
    rating: 5,
    title: 'Fixed monthly salary is a game-changer!',
    content: 'Finotive Funding\'s fixed monthly salary program is incredible. Getting a guaranteed salary for passing the classic challenge is a unique benefit that sets them apart. The fast payouts and high leverage are also excellent.',
    date: '2024-11-13',
    verified: true,
    helpful: 37,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 42000,
    payoutReceived: true
  },
  {
    id: 'funded-prime-review-1',
    firmId: 'funded-prime',
    userName: 'Alex Chen',
    userAvatar: '/avatars/alex-chen.jpg',
    rating: 4,
    title: 'Great for meme stock and crypto traders',
    content: 'FundedPrime is perfect for traders who focus on meme stocks and crypto. Being backed by Eightcap gives me confidence in their legitimacy. The niche challenges are refreshing in a crowded market.',
    date: '2024-11-07',
    verified: true,
    helpful: 29,
    userLocation: 'New York, USA',
    tradingExperience: '2 years',
    accountSize: '$100,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'maven-trading-review-1',
    firmId: 'maven-trading',
    userName: 'Emma Thompson',
    userAvatar: '/avatars/emma-thompson.jpg',
    rating: 4,
    title: 'Strong community focus with mentorship',
    content: 'Maven Trading\'s community-focused approach is refreshing. The mentorship opportunities and low entry fees make it accessible for new traders. The bi-weekly payouts are reliable.',
    date: '2024-11-04',
    verified: true,
    helpful: 26,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 12000,
    payoutReceived: true
  },
  // Bulenox Review
  {
    id: 'bulenox-review-1',
    firmId: 'bulenox',
    userName: 'FuturesTrader',
    userAvatar: '/avatars/futures-trader.jpg',
    rating: 4,
    title: 'Great for futures with EOD drawdown',
    content: 'Bulenox is excellent for futures trading with their end-of-day drawdown. The massive discounts (up to 91% off) make it very affordable. The EOD drawdown is much more forgiving than intraday limits.',
    date: '2024-11-14',
    verified: true,
    helpful: 28,
    userLocation: 'Chicago, USA',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  // Leeloo Trading Review
  {
    id: 'leeloo-trading-review-1',
    firmId: 'leeloo-trading',
    userName: 'Tom Anderson',
    userAvatar: '/avatars/tom-anderson.jpg',
    rating: 5,
    title: 'Keep 100% of first profits - amazing!',
    content: 'Leeloo Trading\'s policy of keeping 100% of the first $8,000-$12,500 in profits is incredible. The flexible rules and no news ban make it perfect for my trading style.',
    date: '2024-11-11',
    verified: true,
    helpful: 41,
    userLocation: 'Los Angeles, USA',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 55000,
    payoutReceived: true
  },
  // Funding Ticks Review
  {
    id: 'funding-ticks-review-1',
    firmId: 'funding-ticks',
    userName: 'Sophie Taylor',
    userAvatar: '/avatars/sophie-taylor.jpg',
    rating: 4,
    title: 'Great futures firm backed by Funding Pips',
    content: 'Funding Ticks brings the same trader-friendly approach from Funding Pips to futures trading. The zero-challenge model is perfect for experienced traders. Being backed by a reputable firm gives me confidence.',
    date: '2024-11-09',
    verified: true,
    helpful: 27,
    userLocation: 'Vancouver, Canada',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 20000,
    payoutReceived: true
  },
  // TickTick Trader Review
  {
    id: 'ticktick-trader-review-1',
    firmId: 'ticktick-trader',
    userName: 'Kevin Lee',
    userAvatar: '/avatars/kevin-lee.jpg',
    rating: 5,
    title: '2-hour payouts and Direct accounts are perfect!',
    content: 'TickTick Trader\'s 2-hour payouts are the fastest I\'ve experienced. The Direct accounts that bypass evaluation are perfect for experienced traders. No overnight trading ban is a huge advantage.',
    date: '2024-11-06',
    verified: true,
    helpful: 38,
    userLocation: 'Singapore',
    tradingExperience: '6 years',
    accountSize: '$250,000',
    profitMade: 48000,
    payoutReceived: true
  },
  // Purdia Review
  {
    id: 'purdia-review-1',
    firmId: 'purdia',
    userName: 'Maria Santos',
    userAvatar: '/avatars/maria-santos.jpg',
    rating: 3,
    title: 'New firm with potential but limited data',
    content: 'Purdia is a very new firm with limited reviews. Their free resets and collaborative scaling features are interesting, but I\'d recommend waiting for more established data before committing significant capital.',
    date: '2024-11-04',
    verified: true,
    helpful: 15,
    userLocation: 'São Paulo, Brazil',
    tradingExperience: '2 years',
    accountSize: '$25,000',
    profitMade: 5000,
    payoutReceived: true
  },
  // Phidias Prop Firm Review
  {
    id: 'phidias-prop-firm-review-1',
    firmId: 'phidias-prop-firm',
    userName: 'Jean Dubois',
    userAvatar: '/avatars/jean-dubois.jpg',
    rating: 3,
    title: 'Art-inspired theme is unique but new firm',
    content: 'Phidias has an interesting art-inspired approach and multilingual support. As a new French firm, they\'re still building their reputation. The 1 and 2-phase challenges are standard.',
    date: '2024-11-02',
    verified: true,
    helpful: 18,
    userLocation: 'Paris, France',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 8000,
    payoutReceived: true
  },
  // Darwinex Review
  {
    id: 'darwinex-review-1',
    firmId: 'darwinex',
    userName: 'Robert Smith',
    userAvatar: '/avatars/robert-smith.jpg',
    rating: 4,
    title: 'Unique FCA-regulated model - different approach',
    content: 'Darwinex operates completely differently from traditional prop firms. Building a track record and attracting investor capital is a long-term approach, but the FCA regulation gives me confidence.',
    date: '2024-10-30',
    verified: true,
    helpful: 24,
    userLocation: 'London, UK',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 30000,
    payoutReceived: true
  },
  // The Trading Pit Review
  {
    id: 'the-trading-pit-review-1',
    firmId: 'the-trading-pit',
    userName: 'Hans Mueller',
    userAvatar: '/avatars/hans-mueller.jpg',
    rating: 4,
    title: 'High scaling up to $5M from Liechtenstein',
    content: 'The Trading Pit offers excellent scaling opportunities up to $5M. Based in Liechtenstein, they provide both CFD and Futures challenges. The educational focus is strong, but monthly payouts are slow.',
    date: '2024-10-28',
    verified: true,
    helpful: 31,
    userLocation: 'Zurich, Switzerland',
    tradingExperience: '4 years',
    accountSize: '$500,000',
    profitMade: 75000,
    payoutReceived: true
  },
  // Lux Trading Firm Review
  {
    id: 'lux-trading-firm-review-1',
    firmId: 'lux-trading-firm',
    userName: 'Amanda White',
    userAvatar: '/avatars/amanda-white.jpg',
    rating: 5,
    title: 'Award-winning support for EAs and copy trading',
    content: 'Lux Trading Firm is exceptional for automated trading. Their award-winning support for EAs and copy trading systems is unmatched. The 2025 innovations and scaling up to $2.5M are impressive.',
    date: '2024-10-25',
    verified: true,
    helpful: 44,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 60000,
    payoutReceived: true
  },
  // E8 Funding Review
  {
    id: 'e8-funding-review-1',
    firmId: 'e8-funding',
    userName: 'Yuki Tanaka',
    userAvatar: '/avatars/yuki-tanaka.jpg',
    rating: 4,
    title: 'Fast payouts from day 8 with weekend holding',
    content: 'E8 Funding\'s 8-day payout cycle is excellent for active traders. The weekend holding feature is perfect for my swing trading strategy. Over $59M in payouts shows their reliability.',
    date: '2024-10-22',
    verified: true,
    helpful: 33,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 28000,
    payoutReceived: true
  },
  // Ment Funding Review
  {
    id: 'ment-funding-review-1',
    firmId: 'ment-funding',
    userName: 'Ahmed Hassan',
    userAvatar: '/avatars/ahmed-hassan.jpg',
    rating: 3,
    title: 'Flexible options but mixed support reviews',
    content: 'Ment Funding offers good flexibility with both 1-step and instant funding options. However, the mixed reviews on customer support are concerning. Scaling up to $2M is attractive.',
    date: '2024-10-20',
    verified: true,
    helpful: 21,
    userLocation: 'Dubai, UAE',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 18000,
    payoutReceived: true
  },
  // Goat Funded Trader Review
  {
    id: 'goat-funded-trader-review-1',
    firmId: 'goat-funded-trader',
    userName: 'Isabella Garcia',
    userAvatar: '/avatars/isabella-garcia.jpg',
    rating: 4,
    title: 'Great for crypto traders with 100% profit splits',
    content: 'Goat Funded Trader is excellent for crypto trading. The up to 100% profit splits and on-demand payouts are perfect for my crypto strategies. The instant funding option is convenient.',
    date: '2024-10-18',
    verified: true,
    helpful: 36,
    userLocation: 'Madrid, Spain',
    tradingExperience: '3 years',
    accountSize: '$200,000',
    profitMade: 40000,
    payoutReceived: true
  },
  // Breakout Prop Review
  {
    id: 'breakout-prop-review-1',
    firmId: 'breakout-prop',
    userName: 'Steve Johnson',
    userAvatar: '/avatars/steve-johnson.jpg',
    rating: 3,
    title: 'Niche focus on breakout strategies',
    content: 'Breakout Prop caters specifically to breakout traders, which is my specialty. However, as a small, emerging firm with limited data, I\'d recommend caution and thorough research before committing.',
    date: '2024-10-15',
    verified: true,
    helpful: 16,
    userLocation: 'Austin, USA',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 12000,
    payoutReceived: true
  },
  // BrightFunded Review
  {
    id: 'brightfunded-review-1',
    firmId: 'brightfunded',
    userName: 'Jennifer Liu',
    userAvatar: '/avatars/jennifer-liu.jpg',
    rating: 5,
    title: 'Excellent for US traders with transparent process',
    content: 'BrightFunded is one of the best choices for US traders. Their transparent process and competitive parameters make them stand out. Weekly payouts are reliable and the support is excellent.',
    date: '2024-10-12',
    verified: true,
    helpful: 39,
    userLocation: 'San Francisco, USA',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  // The Legends Trading Review
  {
    id: 'the-legends-trading-review-1',
    firmId: 'the-legends-trading',
    userName: 'Marcus Williams',
    userAvatar: '/avatars/marcus-williams.jpg',
    rating: 3,
    title: 'Creative myth-themed approach but very new',
    content: 'The Legends Trading has an interesting myth-based theme, but as a very new firm with limited data, I\'d recommend waiting for more established reviews before committing significant capital.',
    date: '2024-10-10',
    verified: true,
    helpful: 14,
    userLocation: 'Atlanta, USA',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 8000,
    payoutReceived: true
  },
  // QuantFunded Review
  {
    id: 'quantfunded-review-1',
    firmId: 'quantfunded',
    userName: 'Dr. Elena Petrov',
    userAvatar: '/avatars/elena-petrov.jpg',
    rating: 4,
    title: 'Perfect for quantitative and algorithmic traders',
    content: 'QuantFunded is specifically designed for quantitative traders like myself. The EA-heavy approach and platform support for automated systems are excellent. The higher entry cost is justified for the specialized service.',
    date: '2024-10-08',
    verified: true,
    helpful: 28,
    userLocation: 'Moscow, Russia',
    tradingExperience: '6 years',
    accountSize: '$500,000',
    profitMade: 85000,
    payoutReceived: true
  },
  // Crypto Fund Trader Review
  {
    id: 'crypto-fund-trader-review-1',
    firmId: 'crypto-fund-trader',
    userName: 'Daniel Park',
    userAvatar: '/avatars/daniel-park.jpg',
    rating: 5,
    title: 'The best prop firm for crypto traders!',
    content: 'Crypto Fund Trader is absolutely the best choice for crypto trading. Over 100 pairs, weekend trading, and 48-hour payouts make them perfect for crypto scalpers. The instant funding option is fantastic.',
    date: '2024-10-05',
    verified: true,
    helpful: 47,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$300,000',
    profitMade: 65000,
    payoutReceived: true
  }
];

// Helper function to get reviews by firm ID
export const getReviewsByFirmId = (firmId: string): UserReview[] => {
  return userReviews.filter(review => review.firmId === firmId);
};

// Helper function to get review statistics
export const getReviewStats = (firmId: string) => {
  const reviews = getReviewsByFirmId(firmId);
  const totalReviews = reviews.length;
  const averageRating = totalReviews > 0 ? reviews.reduce((sum, review) => sum + review.rating, 0) / totalReviews : 0;
  const ratingDistribution = {
    5: reviews.filter(r => r.rating === 5).length,
    4: reviews.filter(r => r.rating === 4).length,
    3: reviews.filter(r => r.rating === 3).length,
    2: reviews.filter(r => r.rating === 2).length,
    1: reviews.filter(r => r.rating === 1).length
  };
  
  return {
    totalReviews,
    averageRating: Math.round(averageRating * 10) / 10,
    ratingDistribution
  };
};
