import type { UserReview } from '../types';

export const userReviews: UserReview[] = [
  // Soar Funding Reviews
  {
    id: 'soar-funding-review-1',
    firmId: 'soar-funding',
    userName: 'Michael Chen',
    userAvatar: '/avatars/michael-chen.jpg',
    rating: 5,
    title: 'The 100% profit split is real!',
    content: 'I was skeptical about the 100% profit split on first payout, but Soar Funding delivered exactly as promised. I passed their evaluation in just 2 weeks and received my first payout with ZERO fees taken out. Their platform is stable and their support team is incredibly responsive. Highly recommend!',
    date: '2025-09-05',
    verified: true,
    helpful: 87,
    userLocation: 'Singapore',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 12300,
    payoutReceived: true
  },
  {
    id: 'soar-funding-review-2',
    firmId: 'soar-funding',
    userName: 'Emma Rodriguez',
    userAvatar: '/avatars/emma-rodriguez.jpg',
    rating: 4,
    title: 'Great firm with minor platform issues',
    content: 'Soar Funding has been excellent overall. The evaluation process is fair and the 100% first payout is legitimate. I had some minor issues with their platform during high volatility periods, but their support team was quick to resolve them. The educational resources they provide are also very helpful.',
    date: '2025-08-22',
    verified: true,
    helpful: 45,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 6500,
    payoutReceived: true
  },
  {
    id: 'soar-funding-review-3',
    firmId: 'soar-funding',
    userName: 'David Williams',
    userAvatar: '/avatars/david-williams.jpg',
    rating: 5,
    title: 'Best prop firm for scaling up',
    content: 'I\'ve been with several prop firms, but Soar Funding has the best scaling plan by far. Started with a $50K account and now managing $300K after just 4 months. Their profit targets are reasonable and the account growth is sustainable. The 100% first payout was a great bonus too!',
    date: '2025-09-18',
    verified: true,
    helpful: 62,
    userLocation: 'Sydney, Australia',
    tradingExperience: '8 years',
    accountSize: '$300,000',
    profitMade: 45000,
    payoutReceived: true
  },
  
  // Funded7 Reviews
  {
    id: 'funded7-review-1',
    firmId: 'funded7',
    userName: 'James Harrison',
    userAvatar: '/avatars/james-harrison.jpg',
    rating: 5,
    title: 'Excellent flexibility with multiple models',
    content: 'Funded7\'s triple model approach is perfect for traders at different skill levels. I started with their 2-step challenge and passed both phases in 3 weeks. Their platform is rock solid and the 85% profit split is one of the best in the industry. Payouts are processed within 48 hours as promised.',
    date: '2025-08-10',
    verified: true,
    helpful: 53,
    userLocation: 'Toronto, Canada',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 13200,
    payoutReceived: true
  },
  {
    id: 'funded7-review-2',
    firmId: 'funded7',
    userName: 'Olivia Johnson',
    userAvatar: '/avatars/olivia-johnson.jpg',
    rating: 4,
    title: 'Great instant funding option',
    content: 'I chose Funded7\'s instant funding model and was trading with real capital within hours. The verification process was smooth and their customer service is excellent. The only reason for 4 stars instead of 5 is that their platform had some minor latency issues during major news events.',
    date: '2025-09-02',
    verified: true,
    helpful: 38,
    userLocation: 'Chicago, USA',
    tradingExperience: '7 years',
    accountSize: '$75,000',
    profitMade: 9800,
    payoutReceived: true
  },
  {
    id: 'funded7-review-3',
    firmId: 'funded7',
    userName: 'Thomas Schmidt',
    userAvatar: '/avatars/thomas-schmidt.jpg',
    rating: 5,
    title: 'Transparent and trustworthy',
    content: 'What sets Funded7 apart is their transparency. All rules are clearly explained, no hidden conditions. I\'ve been with them for 4 months and have received 3 payouts so far, all processed quickly and accurately. Their educational webinars are also very informative and practical.',
    date: '2025-07-15',
    verified: true,
    helpful: 47,
    userLocation: 'Berlin, Germany',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 18500,
    payoutReceived: true
  },
  
  // Aqua Funded Reviews
  {
    id: 'aqua-funded-review-1',
    firmId: 'aqua-funded',
    userName: 'Rebecca Taylor',
    userAvatar: '/avatars/rebecca-taylor.jpg',
    rating: 5,
    title: 'Best customer support in the industry',
    content: 'Aqua Funded has set a new standard for customer support in the prop trading industry. I had several questions during my evaluation phase, and their team was always available with detailed and helpful responses. The trading conditions are excellent with tight spreads and fast execution.',
    date: '2025-09-12',
    verified: true,
    helpful: 29,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 6200,
    payoutReceived: true
  },
  {
    id: 'aqua-funded-review-2',
    firmId: 'aqua-funded',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 5,
    title: 'Transparent evaluation process',
    content: 'What I appreciate most about Aqua Funded is their transparent evaluation process. The rules are clear, fair, and consistent. No hidden conditions or sudden changes. I passed their challenge in 3 weeks and was trading a funded account shortly after. Their platform is also very stable with minimal downtime.',
    date: '2025-08-28',
    verified: true,
    helpful: 34,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 12800,
    payoutReceived: true
  },
  {
    id: 'aqua-funded-review-3',
    firmId: 'aqua-funded',
    userName: 'Lisa Martinez',
    userAvatar: '/avatars/lisa-martinez.jpg',
    rating: 4,
    title: 'Great for forex traders',
    content: 'Aqua Funded is particularly good for forex traders like myself. Their spreads are competitive and execution is fast. I\'ve been with them for 3 months and have had a positive experience overall. The only improvement I\'d suggest is adding more educational resources for newer traders.',
    date: '2025-09-05',
    verified: true,
    helpful: 22,
    userLocation: 'Miami, USA',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 8900,
    payoutReceived: true
  },
  
  // Funded Kingdom Reviews
  {
    id: 'funded-kingdom-review-1',
    firmId: 'funded-kingdom',
    userName: 'Alexander Brown',
    userAvatar: '/avatars/alexander-brown.jpg',
    rating: 5,
    title: 'Love the gamified approach!',
    content: 'Funded Kingdom\'s level-based approach makes the evaluation process much more engaging. It feels like you\'re progressing through a game while actually building real trading skills. I\'ve reached Level 4 and am now managing a $200K account. Their platform is excellent and the community is very supportive.',
    date: '2025-08-15',
    verified: true,
    helpful: 56,
    userLocation: 'London, UK',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 23500,
    payoutReceived: true
  },
  {
    id: 'funded-kingdom-review-2',
    firmId: 'funded-kingdom',
    userName: 'Sophia Lee',
    userAvatar: '/avatars/sophia-lee.jpg',
    rating: 4,
    title: 'Great concept but needs some refinement',
    content: 'The gamified evaluation model is innovative and motivating. I enjoy the clear progression path and achievement system. However, some of the level transitions can be a bit challenging. Their customer support is excellent though, and they\'re always open to feedback for improving the system.',
    date: '2025-09-01',
    verified: true,
    helpful: 42,
    userLocation: 'Hong Kong',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'funded-kingdom-review-3',
    firmId: 'funded-kingdom',
    userName: 'Ryan Wilson',
    userAvatar: '/avatars/ryan-wilson.jpg',
    rating: 5,
    title: 'Perfect for goal-oriented traders',
    content: 'If you\'re a goal-oriented trader who enjoys clear milestones, Funded Kingdom is perfect for you. Their level system provides a clear roadmap for growth, and the rewards at each level are substantial. I particularly appreciate their community features where you can compare progress with other traders.',
    date: '2025-08-22',
    verified: true,
    helpful: 38,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 16800,
    payoutReceived: true
  },
  
  // Fundora Reviews
  {
    id: 'fundora-review-1',
    firmId: 'fundora',
    userName: 'Hiroshi Tanaka',
    userAvatar: '/avatars/hiroshi-tanaka.jpg',
    rating: 5,
    title: 'Excellent for Asian market traders',
    content: 'As someone who primarily trades Asian markets, Fundora has been the perfect fit. Their platform is optimized for trading during Asian hours, and their support team is available when I need them. The two-phase challenge is fair and well-structured, and I appreciate that there\'s no time limit to complete it.',
    date: '2025-08-05',
    verified: true,
    helpful: 42,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'fundora-review-2',
    firmId: 'fundora',
    userName: 'Sarah Johnson',
    userAvatar: '/avatars/sarah-johnson.jpg',
    rating: 4,
    title: 'Great platform with monthly payouts',
    content: 'Fundora offers a stable trading environment with excellent execution. Their educational resources are particularly helpful for developing trading strategies. The only drawback is the monthly payout schedule, which is slower than some competitors. However, the payouts are always accurate and reliable.',
    date: '2025-09-10',
    verified: true,
    helpful: 35,
    userLocation: 'Sydney, Australia',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 13500,
    payoutReceived: true
  },
  {
    id: 'fundora-review-3',
    firmId: 'fundora',
    userName: 'Michael Zhang',
    userAvatar: '/avatars/michael-zhang.jpg',
    rating: 5,
    title: 'Perfect for gold traders',
    content: 'Fundora\'s gold swap-free trading is a game-changer for me as a primarily gold trader. I can hold positions overnight without worrying about swap fees. Their platform is very stable, and the execution speed is excellent. The 80% profit split is competitive, and I\'ve had no issues with payouts so far.',
    date: '2025-07-25',
    verified: true,
    helpful: 29,
    userLocation: 'Shanghai, China',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 18200,
    payoutReceived: true
  },

  // FTMO Reviews - Industry Leader
  {
    id: 'ftmo-review-1',
    firmId: 'ftmo',
    userName: 'Marcus Johnson',
    userAvatar: '/avatars/marcus-johnson.jpg',
    rating: 5,
    title: 'Industry standard for a reason',
    content: 'FTMO has been the gold standard in prop trading for years, and after completing their 2-step challenge, I understand why. The evaluation process is tough but fair, and their MetaTrader integration is flawless. I passed both phases in 6 weeks and received my first payout within 48 hours. The 90% profit split after scaling is exceptional. Their customer support is professional and responsive, and the trading conditions are exactly as advertised. If you\'re serious about prop trading, FTMO should be your first choice.',
    date: '2024-09-28',
    verified: true,
    helpful: 142,
    userLocation: 'London, UK',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 28500,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-2',
    firmId: 'ftmo',
    userName: 'Sarah Kim',
    userAvatar: '/avatars/sarah-kim.jpg',
    rating: 5,
    title: 'Professional platform, excellent support',
    content: 'As someone who has tried multiple prop firms, FTMO stands out for their professionalism and transparency. The rules are clearly defined, and there are no hidden surprises. I particularly appreciate their free retake policy and the comprehensive trading analytics they provide. The scaling plan is realistic and achievable. Currently managing $400K in capital after 8 months, and every payout has been processed on time. Worth every penny of the evaluation fee.',
    date: '2024-10-02',
    verified: true,
    helpful: 98,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '5 years',
    accountSize: '$400,000',
    profitMade: 52000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-3',
    firmId: 'ftmo',
    userName: 'Roberto Martinez',
    userAvatar: '/avatars/roberto-martinez.jpg',
    rating: 4,
    title: 'Challenging but rewarding',
    content: 'FTMO\'s evaluation is definitely challenging - it took me three attempts to pass, but that\'s actually a good thing. It ensures only disciplined traders get funded. The 10% profit target in phase 1 requires patience and strategy. Once funded, the experience has been excellent. Fast payouts, good spreads, and no issues with order execution. The only downside is the initial cost, but the refund policy makes it reasonable. If you can pass their challenge, you\'re ready for serious trading.',
    date: '2024-08-15',
    verified: true,
    helpful: 76,
    userLocation: 'Madrid, Spain',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 15200,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-4',
    firmId: 'ftmo',
    userName: 'Jennifer Wu',
    userAvatar: '/avatars/jennifer-wu.jpg',
    rating: 5,
    title: 'Best risk management education',
    content: 'Beyond just providing capital, FTMO has taught me invaluable risk management skills. Their maximum drawdown rules and daily loss limits forced me to become a better trader. The FTMO dashboard is incredibly detailed, showing every metric you need to track your performance. I\'ve been with them for over a year now, scaled to $200K, and the consistency in payouts and support has been remarkable. Highly recommended for both new and experienced traders.',
    date: '2024-09-12',
    verified: true,
    helpful: 89,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 31000,
    payoutReceived: true
  },

  // Apex Trader Funding Reviews - Futures Leader
  {
    id: 'apex-review-1',
    firmId: 'apex-trader-funding',
    userName: 'Tyler Henderson',
    userAvatar: '/avatars/tyler-henderson.jpg',
    rating: 5,
    title: 'Best futures prop firm, hands down',
    content: 'Apex has completely transformed my futures trading career. The Rithmic and Tradovate platform integration is seamless with near-zero latency. I chose their $50K account and passed the evaluation in just 11 days trading ES and NQ. The 90% profit split is generous, and payouts are processed every Friday like clockwork. No time limits, no minimum trading days - just pure performance-based funding. Their scaling plan is aggressive in the best way. After 5 months, I\'m now trading a $250K account. Customer support responds within hours, not days.',
    date: '2024-10-05',
    verified: true,
    helpful: 156,
    userLocation: 'Chicago, USA',
    tradingExperience: '8 years',
    accountSize: '$250,000',
    profitMade: 47000,
    payoutReceived: true
  },
  {
    id: 'apex-review-2',
    firmId: 'apex-trader-funding',
    userName: 'Michelle Tan',
    userAvatar: '/avatars/michelle-tan.jpg',
    rating: 5,
    title: 'Futures trading done right',
    content: 'I\'ve been with Apex for 6 months and it\'s been nothing but positive. The evaluation is straightforward - hit the profit target without breaking the max loss rules. No complicated requirements or hidden terms. The platform options (Rithmic, Tradovate, Quantower) give you flexibility to use what works best. I trade mostly micros and minis, and the execution is flawless. Payouts arrive in my account within 2-3 days of request. The Discord community is also very helpful with experienced traders sharing strategies.',
    date: '2024-09-20',
    verified: true,
    helpful: 103,
    userLocation: 'Singapore',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'apex-review-3',
    firmId: 'apex-trader-funding',
    userName: 'Derek Williams',
    userAvatar: '/avatars/derek-williams.jpg',
    rating: 4,
    title: 'Great firm, minor platform issues',
    content: 'Apex is excellent for futures traders. The evaluation process is fair and achievable - I passed in 18 days trading crude oil and gold futures. The profit split is among the best, and scaling is quick if you\'re consistent. My only complaint is occasional platform disconnections during high volatility (happened twice in 4 months), but their support team was responsive and understanding. Overall, highly recommend for anyone serious about futures trading. The lack of time pressure makes it less stressful than other firms.',
    date: '2024-08-30',
    verified: true,
    helpful: 67,
    userLocation: 'Dallas, USA',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 18500,
    payoutReceived: true
  },
  {
    id: 'apex-review-4',
    firmId: 'apex-trader-funding',
    userName: 'Priya Sharma',
    userAvatar: '/avatars/priya-sharma.jpg',
    rating: 5,
    title: 'Perfect for disciplined traders',
    content: 'What I love most about Apex is their trader-first approach. No time limits means you can trade your strategy without feeling rushed. The $50 monthly platform fee is more than worth it for the professional tools and data feeds. I trade both day and swing strategies on ES futures, and both work perfectly within their rules. The evaluation metrics are clearly displayed in real-time, so you always know where you stand. Three successful payouts so far, each processed faster than promised. If you\'re disciplined and have a solid strategy, Apex is the place to be.',
    date: '2024-09-08',
    verified: true,
    helpful: 94,
    userLocation: 'Mumbai, India',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },

  // TopStep Reviews - Futures Veteran
  {
    id: 'topstep-review-1',
    firmId: 'topstep',
    userName: 'Brandon Miller',
    userAvatar: '/avatars/brandon-miller.jpg',
    rating: 5,
    title: 'Pioneer in futures prop trading',
    content: 'TopStep has been around since 2012, and their experience shows. The Trading Combine is well-structured and teaches you discipline before giving you real capital. I trade primarily ES and CL futures, and their platform integration with multiple brokers gives great flexibility. Passed my combine in 4 weeks and have been funded for 8 months now. The 80% profit split is fair, and I appreciate their transparent rules. Customer support is top-notch - they actually understand futures trading. Great educational resources too.',
    date: '2024-09-25',
    verified: true,
    helpful: 134,
    userLocation: 'New York, USA',
    tradingExperience: '9 years',
    accountSize: '$150,000',
    profitMade: 34000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-2',
    firmId: 'topstep',
    userName: 'Jessica Lee',
    userAvatar: '/avatars/jessica-lee.jpg',
    rating: 4,
    title: 'Solid and reliable',
    content: 'TopStep is one of the most established prop firms, and it shows in their professionalism. The combine takes patience - I failed twice before passing, but the reset option is helpful. Once funded, the experience has been smooth. Payouts are processed on the 15th of each month consistently. The rules are strict but fair, focusing on consistency rather than home-run trades. My only critique is the monthly fee during the combine, but it keeps traders serious. Overall, a trustworthy firm for futures traders.',
    date: '2024-08-18',
    verified: true,
    helpful: 89,
    userLocation: 'Austin, USA',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 19000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-3',
    firmId: 'topstep',
    userName: 'David Chen',
    userAvatar: '/avatars/david-chen.jpg',
    rating: 5,
    title: 'Best for learning futures discipline',
    content: 'What makes TopStep special is their focus on trader development. The combine isn\'t just an evaluation - it\'s education. The daily loss limit and profit target goals forced me to develop a consistent strategy. Been funded for 6 months, trading NQ and YM futures. The bi-weekly payout option is convenient, and the funded account rules are clear. Their trading room and coaching sessions add real value. If you want to become a professional futures trader, TopStep is an excellent choice.',
    date: '2024-10-03',
    verified: true,
    helpful: 102,
    userLocation: 'San Francisco, USA',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 27500,
    payoutReceived: true
  },

  // FundedNext Reviews - Aggressive Scaling
  {
    id: 'fundednext-review-1',
    firmId: 'fundednext',
    userName: 'Omar Hassan',
    userAvatar: '/avatars/omar-hassan.jpg',
    rating: 5,
    title: 'Incredible 15% profit split model',
    content: 'FundedNext\'s Stellar Lite program with 15% profit split on first payout is absolutely game-changing. I couldn\'t believe it when I received 100% of my first profit plus 15% bonus. The evaluation is fair with reasonable profit targets and drawdown limits. I passed the 2-phase challenge in 5 weeks trading EUR/USD and Gold. Their platform choices (MT4/MT5/cTrader/DXtrade) cover every preference. Customer support via Telegram is incredibly responsive. Scaling plan is aggressive - already doubled my account size in 3 months.',
    date: '2024-10-08',
    verified: true,
    helpful: 167,
    userLocation: 'Dubai, UAE',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 41000,
    payoutReceived: true
  },
  {
    id: 'fundednext-review-2',
    firmId: 'fundednext',
    userName: 'Rachel Anderson',
    userAvatar: '/avatars/rachel-anderson.jpg',
    rating: 5,
    title: 'Multiple models for different traders',
    content: 'I love that FundedNext offers multiple challenge types - Express, Evaluation, and Stellar programs. I chose the Evaluation model for the higher profit split. The consistency rule (10% requirement) actually helps develop good trading habits. Passed both phases in my first attempt. EA trading is allowed which is perfect for my strategy. Payouts processed within 48 hours as promised. The educational content and market analysis they provide is surprisingly detailed. Best prop firm I\'ve worked with.',
    date: '2024-09-19',
    verified: true,
    helpful: 121,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 23000,
    payoutReceived: true
  },
  {
    id: 'fundednext-review-3',
    firmId: 'fundednext',
    userName: 'Thomas Berg',
    userAvatar: '/avatars/thomas-berg.jpg',
    rating: 4,
    title: 'Great value, minor verification delays',
    content: 'FundedNext offers excellent value with competitive pricing and high profit splits. The Express challenge is perfect if you want quicker access to funding. I trade mostly indices and commodities, and spreads are competitive. Verification took longer than expected (5 days), but once cleared, everything has been smooth. On my second payout now, both processed correctly. The consistency requirement requires planning but is achievable. Recommend for traders who want flexibility and good profit sharing.',
    date: '2024-08-27',
    verified: true,
    helpful: 78,
    userLocation: 'Stockholm, Sweden',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 8900,
    payoutReceived: true
  },

  // City Traders Imperium Reviews - UK Leader
  {
    id: 'cti-review-1',
    firmId: 'city-traders-imperium',
    userName: 'James Sterling',
    userAvatar: '/avatars/james-sterling.jpg',
    rating: 5,
    title: 'UK-based professionalism',
    content: 'City Traders Imperium stands out as one of the most professional firms I\'ve encountered. Being UK-based and FCA-monitored provides extra peace of mind. Their 3-phase evaluation is comprehensive but fair, focusing on risk management and consistency. I appreciated the detailed performance metrics and feedback throughout. Once funded, the 75% profit split is good, and payouts are reliable. Trade ES, GBP/USD, and DAX with excellent execution. The community aspect with trading rooms and mentorship is valuable.',
    date: '2024-09-22',
    verified: true,
    helpful: 118,
    userLocation: 'London, UK',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 29000,
    payoutReceived: true
  },
  {
    id: 'cti-review-2',
    firmId: 'city-traders-imperium',
    userName: 'Sophie Martin',
    userAvatar: '/avatars/sophie-martin.jpg',
    rating: 5,
    title: 'Excellent education and support',
    content: 'What I love about CTI is their holistic approach. It\'s not just about passing a challenge - they invest in trader education. The Master Your Mind program and weekly webinars significantly improved my trading psychology. The evaluation process has clear objectives for each phase. Passed all 3 phases in 9 weeks. The funded account rules are transparent with no hidden surprises. Support team is knowledgeable and helpful. Payouts come through monthly as scheduled. Great for traders who value ongoing education.',
    date: '2024-10-01',
    verified: true,
    helpful: 93,
    userLocation: 'Paris, France',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 17500,
    payoutReceived: true
  },
  {
    id: 'cti-review-3',
    firmId: 'city-traders-imperium',
    userName: 'Michael O\'Brien',
    userAvatar: '/avatars/michael-obrien.jpg',
    rating: 4,
    title: 'Professional but slower payout',
    content: 'CTI is highly professional with a structured evaluation process. The 3-phase model ensures only consistent traders get funded, which I respect. Trading conditions are good with tight spreads on major pairs. My only complaint is the monthly payout frequency - would prefer bi-weekly like some competitors. However, when payouts come, they\'re always accurate and reliable. The UK regulatory oversight is reassuring. Good choice for traders who prioritize security and professional operations.',
    date: '2024-08-14',
    verified: true,
    helpful: 67,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 14200,
    payoutReceived: true
  },

  // E8 Funding Reviews - Multi-Asset Expert
  {
    id: 'e8-review-1',
    firmId: 'e8-funding',
    userName: 'Alexei Volkov',
    userAvatar: '/avatars/alexei-volkov.jpg',
    rating: 5,
    title: 'Best crypto prop firm',
    content: 'E8 Funding is the only serious prop firm offering crypto funding. Their Elev8 and Track8 programs give flexibility in evaluation style. I trade Bitcoin and Ethereum futures primarily, and the execution is excellent. Passed Track8 evaluation in 3 weeks with Bitcoin CFDs. The 80% profit split is competitive, and they allow both MT4/MT5 and DXtrade. Payouts are processed twice monthly and always on time. If you want to trade crypto with prop firm capital, E8 is your best option.',
    date: '2024-10-04',
    verified: true,
    helpful: 145,
    userLocation: 'Prague, Czech Republic',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'e8-review-2',
    firmId: 'e8-funding',
    userName: 'Maya Patel',
    userAvatar: '/avatars/maya-patel.jpg',
    rating: 5,
    title: 'Comprehensive multi-asset platform',
    content: 'E8 offers the widest range of instruments I\'ve seen - Forex, indices, commodities, crypto, and stocks. I trade a diversified portfolio which their platform handles perfectly. The Elev8 program\'s single-phase evaluation is efficient. Achieved profit target in 4 weeks trading mix of GBP/JPY, Gold, and BTC. Support is responsive and knowledgeable across all asset classes. Scaling plan is transparent. Three successful payouts so far. Great for traders who don\'t want to be limited to just forex.',
    date: '2024-09-16',
    verified: true,
    helpful: 108,
    userLocation: 'Mumbai, India',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 19500,
    payoutReceived: true
  },
  {
    id: 'e8-review-3',
    firmId: 'e8-funding',
    userName: 'Luis Fernandez',
    userAvatar: '/avatars/luis-fernandez.jpg',
    rating: 4,
    title: 'Great platform, learning curve',
    content: 'E8\'s multi-asset offering is impressive, though it took time to understand all the options. I went with Track8 two-phase challenge which felt more familiar coming from other firms. Trading conditions are solid, and the ability to trade stocks as CFDs opened new opportunities. Passed evaluation in 6 weeks. Payouts come bi-monthly as stated. My only issue was some confusion about rules for different asset classes initially, but support clarified quickly. Solid choice for experienced traders wanting variety.',
    date: '2024-08-21',
    verified: true,
    helpful: 72,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '5 years',
    accountSize: '$75,000',
    profitMade: 11000,
    payoutReceived: true
  },

  // DNA Funded Reviews - Transparent Operations
  {
    id: 'dna-review-1',
    firmId: 'dna-funded',
    userName: 'Kevin Wright',
    userAvatar: '/avatars/kevin-wright.jpg',
    rating: 5,
    title: 'Most transparent firm I\'ve found',
    content: 'DNA Funded lives up to their transparency promise. Everything is clearly explained - no hidden fees, no surprise rule changes. Their evaluation process is straightforward with clear profit targets and drawdown rules. I particularly appreciate their trader dashboard showing real-time stats. Passed the challenge in 5 weeks trading GBP/USD and EUR/JPY. The 80% profit split is fair, and they allow news trading and EAs. Payouts processed within 72 hours consistently. Support team is honest and responsive.',
    date: '2024-09-30',
    verified: true,
    helpful: 112,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 21000,
    payoutReceived: true
  },
  {
    id: 'dna-review-2',
    firmId: 'dna-funded',
    userName: 'Isabella Romano',
    userAvatar: '/avatars/isabella-romano.jpg',
    rating: 5,
    title: 'Refreshing honesty in the industry',
    content: 'After bad experiences with other firms, DNA Funded\'s transparency was refreshing. No gimmicks, no misleading marketing - just honest prop trading. The evaluation is challenging but achievable with proper risk management. I trade primarily indices and commodities. Platform integration with MT4/MT5 is smooth. Scaling options are clearly laid out from day one. Been funded for 7 months with 4 successful payouts. They treat traders with respect and professionalism. Highly recommend.',
    date: '2024-10-06',
    verified: true,
    helpful: 97,
    userLocation: 'Milan, Italy',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 26000,
    payoutReceived: true
  },
  {
    id: 'dna-review-3',
    firmId: 'dna-funded',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 4,
    title: 'Solid firm, could improve scaling',
    content: 'DNA Funded delivers on their transparency promise. Rules are clear, no hidden catches. Evaluation process is fair - passed in my second attempt after learning from first. Trading conditions are good with competitive spreads. Payouts arrive as promised. My only feedback is the scaling plan could be more aggressive compared to competitors. That said, the consistency-based approach makes sense for sustainable growth. Good choice for traders who value straightforward terms and honest operations.',
    date: '2024-08-19',
    verified: true,
    helpful: 68,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 7800,
    payoutReceived: true
  },

  // Take Profit Trader Reviews - Futures Innovator
  {
    id: 'tpt-review-1',
    firmId: 'take-profit-trader',
    userName: 'Nathan Brooks',
    userAvatar: '/avatars/nathan-brooks.jpg',
    rating: 5,
    title: 'Best futures evaluation structure',
    content: 'Take Profit Trader has the most trader-friendly futures evaluation I\'ve experienced. No time limits, no minimum trading days, just pure performance metrics. I trade ES and NQ exclusively, and their platform supports all major futures brokers. Passed evaluation in 16 days with consistent small gains - exactly how they encourage you to trade. The 80% profit split increases to 90% which is excellent. Payouts every two weeks like clockwork. Been funded for 5 months and very satisfied.',
    date: '2024-09-27',
    verified: true,
    helpful: 129,
    userLocation: 'Denver, USA',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 31000,
    payoutReceived: true
  },
  {
    id: 'tpt-review-2',
    firmId: 'take-profit-trader',
    userName: 'Emily Watson',
    userAvatar: '/avatars/emily-watson.jpg',
    rating: 5,
    title: 'No-pressure evaluation perfect for my style',
    content: 'The lack of time pressure at Take Profit Trader made all the difference for me. I could trade my strategy without feeling rushed to hit targets. Took me 4 weeks to pass evaluation trading crude oil and gold futures. Their risk management rules are sensible and teach good habits. Customer support understands futures trading deeply. Scaling is straightforward based on consistent profits. Already upgraded from $50K to $100K account. Payouts arrive in my account within 48 hours of request.',
    date: '2024-10-02',
    verified: true,
    helpful: 94,
    userLocation: 'Seattle, USA',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'tpt-review-3',
    firmId: 'take-profit-trader',
    userName: 'Roberto Silva',
    userAvatar: '/avatars/roberto-silva.jpg',
    rating: 4,
    title: 'Great for swing traders',
    content: 'Take Profit Trader is perfect if you\'re a swing trader like me. No daily trading requirements means I can hold positions overnight when my strategy calls for it. Evaluation rules are clear and fair. Passed in 3 weeks trading NQ and YM. The profit targets are achievable without taking excessive risk. One minor issue was delayed response from support during weekends, but weekday support is excellent. Overall, highly recommend for traders who prefer low-pressure, consistency-focused evaluation.',
    date: '2024-08-25',
    verified: true,
    helpful: 71,
    userLocation: 'São Paulo, Brazil',
    tradingExperience: '6 years',
    accountSize: '$75,000',
    profitMade: 12500,
    payoutReceived: true
  },

  // FXIFY Reviews - Fast Growing
  {
    id: 'fxify-review-1',
    firmId: 'fxify',
    userName: 'Chris Taylor',
    userAvatar: '/avatars/chris-taylor.jpg',
    rating: 5,
    title: 'Rapid growth with excellent conditions',
    content: 'FXIFY impressed me from day one. Their evaluation process is well-designed with clear milestones. I chose the 2-step challenge and passed both phases in 5 weeks trading EUR/USD and GBP/JPY. The 90% profit split is among the highest I\'ve seen. Platform choice includes MT4, MT5, cTrader, and Match-Trader. Spreads are tight, execution is fast. Their scaling plan is aggressive - already moved from $100K to $200K in 4 months. Payouts processed within 24-48 hours consistently.',
    date: '2024-10-07',
    verified: true,
    helpful: 138,
    userLocation: 'Manchester, UK',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 39000,
    payoutReceived: true
  },
  {
    id: 'fxify-review-2',
    firmId: 'fxify',
    userName: 'Yuki Tanaka',
    userAvatar: '/avatars/yuki-tanaka.jpg',
    rating: 5,
    title: 'Modern approach to prop funding',
    content: 'FXIFY feels like a next-generation prop firm. Everything from their website to their trader dashboard is modern and user-friendly. The evaluation tracks are flexible - I chose the slower track for more manageable targets. Passed in 6 weeks with consistent gains. EA trading is fully supported which works perfectly for my algorithmic strategy. Support team is available 24/5 and genuinely helpful. Been funded 3 months with flawless payout experiences. Great for both discretionary and algo traders.',
    date: '2024-09-14',
    verified: true,
    helpful: 103,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'fxify-review-3',
    firmId: 'fxify',
    userName: 'Marcus Anderson',
    userAvatar: '/avatars/marcus-anderson.jpg',
    rating: 4,
    title: 'Excellent but still building track record',
    content: 'FXIFY is a newer firm but they\'re doing things right. The evaluation process is fair with reasonable targets. I like the multiple challenge options catering to different risk appetites. Passed the aggressive track in 4 weeks. Trading conditions are competitive with good spreads. Payouts have been reliable so far (2 received). The only reason for 4 stars is they\'re still building their long-term track record, but all signs point to them being a solid choice. Recommend giving them a try.',
    date: '2024-08-29',
    verified: true,
    helpful: 76,
    userLocation: 'Cape Town, South Africa',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // The 5%ers Reviews - Scaling Specialists
  {
    id: '5percenters-review-1',
    firmId: 'the-5-percenters',
    userName: 'Andreas Mueller',
    userAvatar: '/avatars/andreas-mueller.jpg',
    rating: 5,
    title: 'Unmatched scaling to $4M',
    content: 'The 5%ers is not your typical prop firm - their Hyper Growth program is truly unique. I started with a $6K account and within 9 months, I\'ve scaled to $250K. The bootcamp style evaluation teaches you proper risk management while you earn. What really sets them apart is the potential to scale up to $4 million, which is unheard of elsewhere. The profit split increases as you progress, currently at 80% and heading to 100%. Payouts are bi-weekly and always on time. Their multi-platform support (MT4, MT5, cTrader) is excellent.',
    date: '2024-10-01',
    verified: true,
    helpful: 128,
    userLocation: 'Berlin, Germany',
    tradingExperience: '7 years',
    accountSize: '$250,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: '5percenters-review-2',
    firmId: 'the-5-percenters',
    userName: 'Lisa Chang',
    userAvatar: '/avatars/lisa-chang.jpg',
    rating: 5,
    title: 'Bootcamp program is genius',
    content: 'The 3-step bootcamp model was perfect for me as an intermediate trader. Each phase builds on the last, gradually increasing your account size while maintaining consistent risk management. I appreciate that they allow EA trading and news trading - no artificial restrictions. The High Stakes program is challenging but rewarding. Support team is knowledgeable and actually understands trading. Six months in, scaled from $20K to $100K, and looking forward to the next level. The profit split progression is very motivating.',
    date: '2024-09-15',
    verified: true,
    helpful: 87,
    userLocation: 'Hong Kong',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 16500,
    payoutReceived: true
  },
  {
    id: '5percenters-review-3',
    firmId: 'the-5-percenters',
    userName: 'Carlos Rodriguez',
    userAvatar: '/avatars/carlos-rodriguez.jpg',
    rating: 4,
    title: 'Excellent but requires patience',
    content: 'The 5%ers offers something special with their scaling approach. The bootcamp program takes time - it\'s not instant funding - but the education and gradual progression make you a better trader. I\'m currently in phase 2 of the bootcamp and already seeing improvement in my discipline. The 8% profit target is reasonable, and the static drawdown rules are clear. My only critique is that the progression can feel slow if you\'re aggressive, but I understand it\'s designed for long-term success. Looking forward to reaching the higher tiers.',
    date: '2024-08-22',
    verified: true,
    helpful: 62,
    userLocation: 'Mexico City, Mexico',
    tradingExperience: '4 years',
    accountSize: '$40,000',
    profitMade: 5200,
    payoutReceived: true
  },
  {
    id: '5percenters-review-4',
    firmId: 'the-5-percenters',
    userName: 'Nina Petrov',
    userAvatar: '/avatars/nina-petrov.jpg',
    rating: 5,
    title: 'Long-term partnership, not just funding',
    content: 'After 14 months with The 5%ers, I can confidently say this is the best prop firm for traders who think long-term. The hyper growth scaling is real - I\'ve gone from $10K to $500K. The profit split increasing to 100% is incredible motivation. They truly invest in their traders with regular webinars and strategy sessions. cTrader integration is smooth, and the spread conditions are competitive. Payouts are always processed on schedule. This isn\'t a get-rich-quick scheme; it\'s a professional trading partnership.',
    date: '2024-09-28',
    verified: true,
    helpful: 115,
    userLocation: 'Moscow, Russia',
    tradingExperience: '9 years',
    accountSize: '$500,000',
    profitMade: 72000,
    payoutReceived: true
  }
];

// Helper function to get reviews by firm ID
export const getReviewsByFirmId = (firmId: string): UserReview[] => {
  return userReviews.filter(review => review.firmId === firmId);
};

// Helper function to get review statistics
export const getReviewStats = (firmId: string) => {
  const reviews = getReviewsByFirmId(firmId);
  const totalReviews = reviews.length;
  const averageRating = totalReviews > 0 ? reviews.reduce((sum, review) => sum + review.rating, 0) / totalReviews : 0;
  const ratingDistribution = {
    5: reviews.filter(r => r.rating === 5).length,
    4: reviews.filter(r => r.rating === 4).length,
    3: reviews.filter(r => r.rating === 3).length,
    2: reviews.filter(r => r.rating === 2).length,
    1: reviews.filter(r => r.rating === 1).length
  };
  
  return {
    totalReviews,
    averageRating: Math.round(averageRating * 10) / 10,
    ratingDistribution
  };
};
