import type { UserReview } from '../types';

export const userReviews: UserReview[] = [
  // Audacity Capital Reviews
  {
    id: 'audacity-review-1',
    firmId: 'audacity-capital',
    userName: 'Sarah Mitchell',
    userAvatar: '/avatars/sarah-mitchell.jpg',
    rating: 5,
    title: 'Excellent instant funding process',
    content: 'Audacity Capital has been a game-changer for my trading career. The instant funding process was smooth and straightforward. Their spreads are competitive, and the educational resources are top-notch. I\'ve been trading with them for 8 months and have received consistent payouts.',
    date: '2024-11-15',
    verified: true,
    helpful: 23,
    userLocation: 'London, UK',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 12500,
    payoutReceived: true
  },
  {
    id: 'audacity-review-2',
    firmId: 'audacity-capital',
    userName: 'James Rodriguez',
    userAvatar: '/avatars/james-rodriguez.jpg',
    rating: 4,
    title: 'Good firm but strict rules',
    content: 'Audacity is a solid choice for experienced traders. The instant funding is great, but their rules are quite strict. You need to be very disciplined with your trading. The support team is responsive, and payouts are reliable.',
    date: '2024-10-28',
    verified: true,
    helpful: 18,
    userLocation: 'Madrid, Spain',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 8500,
    payoutReceived: true
  },
  {
    id: 'audacity-review-3',
    firmId: 'audacity-capital',
    userName: 'Emma Thompson',
    userAvatar: '/avatars/emma-thompson.jpg',
    rating: 3,
    title: 'Decent but not for beginners',
    content: 'I tried Audacity as a relatively new trader and found their rules too restrictive. The instant funding is nice, but you need to be very experienced to succeed here. Their educational materials are good though.',
    date: '2024-09-12',
    verified: true,
    helpful: 12,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '1 year',
    accountSize: '$25,000',
    profitMade: -2000,
    payoutReceived: false
  },

  // The 5%ers Reviews
  {
    id: '5ers-review-1',
    firmId: 'the-5-percenters',
    userName: 'Michael Chen',
    userAvatar: '/avatars/michael-chen.jpg',
    rating: 5,
    title: 'Best prop firm I\'ve used',
    content: 'The 5%ers is absolutely fantastic! Their Hyper Growth program is incredible - I started with $4,000 and now I\'m at $200,000. The profit splits are amazing, and their support team is always helpful. Highly recommended!',
    date: '2024-11-20',
    verified: true,
    helpful: 45,
    userLocation: 'New York, USA',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: '5ers-review-2',
    firmId: 'the-5-percenters',
    userName: 'Lisa Wang',
    userAvatar: '/avatars/lisa-wang.jpg',
    rating: 5,
    title: 'Outstanding scaling program',
    content: 'I love how The 5%ers handles scaling. They actually reward consistent performance with account increases. The evaluation process is fair, and once you pass, the live account is amazing. Best prop firm for serious traders.',
    date: '2024-11-08',
    verified: true,
    helpful: 38,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: '5ers-review-3',
    firmId: 'the-5-percenters',
    userName: 'David Johnson',
    userAvatar: '/avatars/david-johnson.jpg',
    rating: 4,
    title: 'Great firm with minor issues',
    content: 'The 5%ers is a great firm overall. The evaluation process is challenging but fair. My only complaint is that their payout process can be a bit slow sometimes. Otherwise, excellent trading conditions.',
    date: '2024-10-15',
    verified: true,
    helpful: 22,
    userLocation: 'Sydney, Australia',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },

  // FTMO Reviews
  {
    id: 'ftmo-review-1',
    firmId: 'ftmo',
    userName: 'Alex Petrov',
    userAvatar: '/avatars/alex-petrov.jpg',
    rating: 5,
    title: 'FTMO is the gold standard',
    content: 'FTMO is simply the best prop firm in the industry. Their evaluation process is transparent, the trading conditions are excellent, and payouts are always on time. I\'ve been with them for 2 years and couldn\'t be happier.',
    date: '2024-11-18',
    verified: true,
    helpful: 67,
    userLocation: 'Moscow, Russia',
    tradingExperience: '7 years',
    accountSize: '$300,000',
    profitMade: 75000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-2',
    firmId: 'ftmo',
    userName: 'Maria Garcia',
    userAvatar: '/avatars/maria-garcia.jpg',
    rating: 4,
    title: 'Solid choice for funded trading',
    content: 'FTMO is a reliable prop firm with good trading conditions. The evaluation is challenging but achievable if you have a solid strategy. Their support team is helpful, and the platform is user-friendly.',
    date: '2024-10-30',
    verified: true,
    helpful: 29,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '2 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-3',
    firmId: 'ftmo',
    userName: 'Robert Kim',
    userAvatar: '/avatars/robert-kim.jpg',
    rating: 3,
    title: 'Good but expensive',
    content: 'FTMO is a good firm, but their evaluation fees are quite high compared to competitors. The trading conditions are decent, but I think there are better options out there for the price.',
    date: '2024-09-25',
    verified: true,
    helpful: 15,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 8000,
    payoutReceived: true
  },

  // Topstep Reviews
  {
    id: 'topstep-review-1',
    firmId: 'topstep',
    userName: 'Jennifer Lee',
    userAvatar: '/avatars/jennifer-lee.jpg',
    rating: 5,
    title: 'Perfect for futures traders',
    content: 'Topstep is absolutely perfect for futures trading. Their platform is excellent, the rules are clear, and the scaling program is fantastic. I\'ve grown my account from $50K to $500K in just 8 months!',
    date: '2024-11-12',
    verified: true,
    helpful: 52,
    userLocation: 'Chicago, USA',
    tradingExperience: '5 years',
    accountSize: '$500,000',
    profitMade: 95000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-2',
    firmId: 'topstep',
    userName: 'Ahmed Hassan',
    userAvatar: '/avatars/ahmed-hassan.jpg',
    rating: 4,
    title: 'Great for systematic trading',
    content: 'Topstep is excellent for systematic and algorithmic trading. Their platform supports various strategies, and the evaluation process is fair. The only downside is that it\'s focused on futures only.',
    date: '2024-10-22',
    verified: true,
    helpful: 31,
    userLocation: 'Dubai, UAE',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-3',
    firmId: 'topstep',
    userName: 'Sophie Martin',
    userAvatar: '/avatars/sophie-martin.jpg',
    rating: 3,
    title: 'Good but limited to futures',
    content: 'Topstep is a good firm, but I wish they offered more asset classes. The futures-only limitation is a bit restrictive. However, their platform and support are excellent.',
    date: '2024-09-18',
    verified: true,
    helpful: 19,
    userLocation: 'Paris, France',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 15000,
    payoutReceived: true
  },

  // Apex Trader Funding Reviews
  {
    id: 'apex-review-1',
    firmId: 'apex-trader-funding',
    userName: 'Carlos Mendez',
    userAvatar: '/avatars/carlos-mendez.jpg',
    rating: 5,
    title: 'Best for US traders',
    content: 'Apex is the best prop firm for US traders! Their evaluation process is straightforward, and they offer great trading conditions. The scaling program is excellent, and payouts are always on time.',
    date: '2024-11-14',
    verified: true,
    helpful: 41,
    userLocation: 'Miami, USA',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 35000,
    payoutReceived: true
  },
  {
    id: 'apex-review-2',
    firmId: 'apex-trader-funding',
    userName: 'Rachel Green',
    userAvatar: '/avatars/rachel-green.jpg',
    rating: 4,
    title: 'Solid choice for funded trading',
    content: 'Apex is a reliable prop firm with good trading conditions. The evaluation process is challenging but fair. Their support team is helpful, and the platform is easy to use.',
    date: '2024-10-05',
    verified: true,
    helpful: 27,
    userLocation: 'Austin, USA',
    tradingExperience: '2 years',
    accountSize: '$75,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'apex-review-3',
    firmId: 'apex-trader-funding',
    userName: 'Kevin Park',
    userAvatar: '/avatars/kevin-park.jpg',
    rating: 3,
    title: 'Decent but could be better',
    content: 'Apex is okay, but I think there are better options out there. The evaluation process is a bit too strict, and the profit targets are challenging. However, they do pay out on time.',
    date: '2024-09-08',
    verified: true,
    helpful: 14,
    userLocation: 'Los Angeles, USA',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 5000,
    payoutReceived: true
  },

  // BluSky Trading Reviews
  {
    id: 'blusky-review-1',
    firmId: 'blusky-trading',
    userName: 'Anna Kowalski',
    userAvatar: '/avatars/anna-kowalski.jpg',
    rating: 5,
    title: 'Excellent crypto-focused firm',
    content: 'BluSky is perfect for crypto traders! Their crypto-focused approach is exactly what I needed. The evaluation process is fair, and the trading conditions are excellent for crypto markets.',
    date: '2024-11-10',
    verified: true,
    helpful: 33,
    userLocation: 'Warsaw, Poland',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'blusky-review-2',
    firmId: 'blusky-trading',
    userName: 'Tom Wilson',
    userAvatar: '/avatars/tom-wilson.jpg',
    rating: 4,
    title: 'Good for crypto trading',
    content: 'BluSky is a solid choice for crypto trading. Their evaluation process is straightforward, and they offer good trading conditions. The only downside is that it\'s crypto-focused only.',
    date: '2024-10-18',
    verified: true,
    helpful: 21,
    userLocation: 'London, UK',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // Funded Futures Network Reviews
  {
    id: 'ffn-review-1',
    firmId: 'funded-futures-network',
    userName: 'Mark Thompson',
    userAvatar: '/avatars/mark-thompson.jpg',
    rating: 5,
    title: 'Great for futures trading',
    content: 'Funded Futures Network is excellent for futures trading. Their evaluation process is fair, and the trading conditions are great. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-16',
    verified: true,
    helpful: 38,
    userLocation: 'Houston, USA',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 42000,
    payoutReceived: true
  },
  {
    id: 'ffn-review-2',
    firmId: 'funded-futures-network',
    userName: 'Elena Rodriguez',
    userAvatar: '/avatars/elena-rodriguez.jpg',
    rating: 4,
    title: 'Solid futures prop firm',
    content: 'FFN is a good choice for futures trading. The evaluation process is challenging but achievable. Their support team is helpful, and the platform is user-friendly.',
    date: '2024-10-12',
    verified: true,
    helpful: 25,
    userLocation: 'Mexico City, Mexico',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },

  // Seacrest Funding Reviews
  {
    id: 'seacrest-review-1',
    firmId: 'seacrest-funding',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 5,
    title: 'Excellent prop firm',
    content: 'Seacrest Funding is one of the best prop firms I\'ve used. Their evaluation process is fair, and the trading conditions are excellent. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-08',
    verified: true,
    helpful: 42,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: 'seacrest-review-2',
    firmId: 'seacrest-funding',
    userName: 'Isabella Chen',
    userAvatar: '/avatars/isabella-chen.jpg',
    rating: 4,
    title: 'Good choice for funded trading',
    content: 'Seacrest is a solid choice for funded trading. The evaluation process is challenging but fair. Their support team is helpful, and the platform is easy to use.',
    date: '2024-10-20',
    verified: true,
    helpful: 28,
    userLocation: 'Singapore',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 19000,
    payoutReceived: true
  },

  // My Flash Funding Reviews
  {
    id: 'mff-review-1',
    firmId: 'my-flash-funding',
    userName: 'Ryan O\'Connor',
    userAvatar: '/avatars/ryan-oconnor.jpg',
    rating: 5,
    title: 'Best prop firm for instant funding',
    content: 'My Flash Funding is the best prop firm for instant funding! Their process is incredibly fast, and the trading conditions are excellent. I got funded within 24 hours!',
    date: '2024-11-22',
    verified: true,
    helpful: 55,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 25000,
    payoutReceived: true
  },
  {
    id: 'mff-review-2',
    firmId: 'my-flash-funding',
    userName: 'Priya Patel',
    userAvatar: '/avatars/priya-patel.jpg',
    rating: 4,
    title: 'Great instant funding option',
    content: 'MFF is a great choice for instant funding. The process is fast and straightforward. The trading conditions are good, and payouts are reliable.',
    date: '2024-10-25',
    verified: true,
    helpful: 32,
    userLocation: 'Mumbai, India',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 12000,
    payoutReceived: true
  },

  // The Legend Trading Reviews
  {
    id: 'legend-review-1',
    firmId: 'the-legend-trading',
    userName: 'Marcus Johnson',
    userAvatar: '/avatars/marcus-johnson.jpg',
    rating: 5,
    title: 'Outstanding prop firm',
    content: 'The Legend Trading is absolutely outstanding! Their evaluation process is fair, and the trading conditions are excellent. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-19',
    verified: true,
    helpful: 48,
    userLocation: 'Atlanta, USA',
    tradingExperience: '5 years',
    accountSize: '$300,000',
    profitMade: 68000,
    payoutReceived: true
  },
  {
    id: 'legend-review-2',
    firmId: 'the-legend-trading',
    userName: 'Nina Petrov',
    userAvatar: '/avatars/nina-petrov.jpg',
    rating: 4,
    title: 'Good choice for funded trading',
    content: 'The Legend Trading is a solid choice for funded trading. The evaluation process is challenging but achievable. Their support team is helpful, and the platform is user-friendly.',
    date: '2024-10-14',
    verified: true,
    helpful: 29,
    userLocation: 'Moscow, Russia',
    tradingExperience: '3 years',
    accountSize: '$100,000',
    profitMade: 24000,
    payoutReceived: true
  },

  // Lucid Trading Reviews
  {
    id: 'lucid-review-1',
    firmId: 'lucid-trading',
    userName: 'Amanda Foster',
    userAvatar: '/avatars/amanda-foster.jpg',
    rating: 5,
    title: 'Excellent trading conditions',
    content: 'Lucid Trading offers excellent trading conditions and a fair evaluation process. Their scaling program is fantastic, and payouts are always on time. Highly recommended!',
    date: '2024-11-13',
    verified: true,
    helpful: 36,
    userLocation: 'Vancouver, Canada',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'lucid-review-2',
    firmId: 'lucid-trading',
    userName: 'Hassan Ali',
    userAvatar: '/avatars/hassan-ali.jpg',
    rating: 4,
    title: 'Solid prop firm',
    content: 'Lucid Trading is a solid choice for funded trading. The evaluation process is fair, and the trading conditions are good. Their support team is helpful.',
    date: '2024-10-08',
    verified: true,
    helpful: 23,
    userLocation: 'Dubai, UAE',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // Quant Reviews
  {
    id: 'quant-review-1',
    firmId: 'quant',
    userName: 'Dr. Sarah Williams',
    userAvatar: '/avatars/sarah-williams.jpg',
    rating: 5,
    title: 'Perfect for algorithmic trading',
    content: 'Quant is perfect for algorithmic and systematic trading. Their platform supports various strategies, and the evaluation process is fair. The trading conditions are excellent for algo trading.',
    date: '2024-11-17',
    verified: true,
    helpful: 44,
    userLocation: 'San Francisco, USA',
    tradingExperience: '8 years',
    accountSize: '$500,000',
    profitMade: 95000,
    payoutReceived: true
  },
  {
    id: 'quant-review-2',
    firmId: 'quant',
    userName: 'Dr. Michael Zhang',
    userAvatar: '/avatars/michael-zhang.jpg',
    rating: 4,
    title: 'Good for systematic trading',
    content: 'Quant is a good choice for systematic trading. The evaluation process is challenging but achievable. Their platform is excellent for algorithmic strategies.',
    date: '2024-10-11',
    verified: true,
    helpful: 31,
    userLocation: 'Shanghai, China',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 45000,
    payoutReceived: true
  },

  // Venus Funded Reviews
  {
    id: 'venus-review-1',
    firmId: 'venus-funded',
    userName: 'Jessica Brown',
    userAvatar: '/avatars/jessica-brown.jpg',
    rating: 5,
    title: 'Amazing prop firm',
    content: 'Venus Funded is absolutely amazing! Their evaluation process is fair, and the trading conditions are excellent. The scaling program is fantastic, and payouts are always on time.',
    date: '2024-11-21',
    verified: true,
    helpful: 39,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '4 years',
    accountSize: '$125,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'venus-review-2',
    firmId: 'venus-funded',
    userName: 'Alexandre Dubois',
    userAvatar: '/avatars/alexandre-dubois.jpg',
    rating: 4,
    title: 'Good choice for funded trading',
    content: 'Venus Funded is a solid choice for funded trading. The evaluation process is challenging but fair. Their support team is helpful, and the platform is easy to use.',
    date: '2024-10-16',
    verified: true,
    helpful: 26,
    userLocation: 'Paris, France',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 17000,
    payoutReceived: true
  },

  // BitFunded Reviews
  {
    id: 'bitfunded-review-1',
    firmId: 'bitfunded',
    userName: 'CryptoTrader99',
    userAvatar: '/avatars/crypto-trader.jpg',
    rating: 4,
    title: 'Good for crypto trading',
    content: 'BitFunded is a good choice for crypto trading. Their evaluation process is fair, and the trading conditions are decent for crypto markets. The only downside is that it\'s crypto-focused only.',
    date: '2024-11-09',
    verified: true,
    helpful: 22,
    userLocation: 'Berlin, Germany',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 11000,
    payoutReceived: true
  },
  {
    id: 'bitfunded-review-2',
    firmId: 'bitfunded',
    userName: 'BlockchainPro',
    userAvatar: '/avatars/blockchain-pro.jpg',
    rating: 3,
    title: 'Decent but limited',
    content: 'BitFunded is okay for crypto trading, but I think there are better options out there. The evaluation process is a bit too strict, and the profit targets are challenging.',
    date: '2024-10-03',
    verified: true,
    helpful: 15,
    userLocation: 'Amsterdam, Netherlands',
    tradingExperience: '2 years',
    accountSize: '$25,000',
    profitMade: 3000,
    payoutReceived: true
  }
];

// Helper function to get reviews by firm ID
export const getReviewsByFirmId = (firmId: string): UserReview[] => {
  return userReviews.filter(review => review.firmId === firmId);
};

// Helper function to get review statistics
export const getReviewStats = (firmId: string) => {
  const reviews = getReviewsByFirmId(firmId);
  const totalReviews = reviews.length;
  const averageRating = totalReviews > 0 ? reviews.reduce((sum, review) => sum + review.rating, 0) / totalReviews : 0;
  const ratingDistribution = {
    5: reviews.filter(r => r.rating === 5).length,
    4: reviews.filter(r => r.rating === 4).length,
    3: reviews.filter(r => r.rating === 3).length,
    2: reviews.filter(r => r.rating === 2).length,
    1: reviews.filter(r => r.rating === 1).length
  };
  
  return {
    totalReviews,
    averageRating: Math.round(averageRating * 10) / 10,
    ratingDistribution
  };
};
