import type { UserReview } from '../types';

export const userReviews: UserReview[] = [
  // Soar Funding Reviews
  {
    id: 'soar-funding-review-1',
    firmId: 'soar-funding',
    userName: 'Michael Chen',
    userAvatar: '/avatars/michael-chen.jpg',
    rating: 5,
    title: 'The 100% profit split is real!',
    content: 'I was skeptical about the 100% profit split on first payout, but Soar Funding delivered exactly as promised. I passed their evaluation in just 2 weeks and received my first payout with ZERO fees taken out. Their platform is stable and their support team is incredibly responsive. Highly recommend!',
    date: '2025-09-05',
    verified: true,
    helpful: 87,
    userLocation: 'Singapore',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 12300,
    payoutReceived: true
  },
  {
    id: 'soar-funding-review-2',
    firmId: 'soar-funding',
    userName: 'Emma Rodriguez',
    userAvatar: '/avatars/emma-rodriguez.jpg',
    rating: 4,
    title: 'Great firm with minor platform issues',
    content: 'Soar Funding has been excellent overall. The evaluation process is fair and the 100% first payout is legitimate. I had some minor issues with their platform during high volatility periods, but their support team was quick to resolve them. The educational resources they provide are also very helpful.',
    date: '2025-08-22',
    verified: true,
    helpful: 45,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '3 years',
    accountSize: '$50,000',
    profitMade: 6500,
    payoutReceived: true
  },
  {
    id: 'soar-funding-review-3',
    firmId: 'soar-funding',
    userName: 'David Williams',
    userAvatar: '/avatars/david-williams.jpg',
    rating: 5,
    title: 'Best prop firm for scaling up',
    content: 'I\'ve been with several prop firms, but Soar Funding has the best scaling plan by far. Started with a $50K account and now managing $300K after just 4 months. Their profit targets are reasonable and the account growth is sustainable. The 100% first payout was a great bonus too!',
    date: '2025-09-18',
    verified: true,
    helpful: 62,
    userLocation: 'Sydney, Australia',
    tradingExperience: '8 years',
    accountSize: '$300,000',
    profitMade: 45000,
    payoutReceived: true
  },
  
  // Funded7 Reviews
  {
    id: 'funded7-review-1',
    firmId: 'funded7',
    userName: 'James Harrison',
    userAvatar: '/avatars/james-harrison.jpg',
    rating: 5,
    title: 'Excellent flexibility with multiple models',
    content: 'Funded7\'s triple model approach is perfect for traders at different skill levels. I started with their 2-step challenge and passed both phases in 3 weeks. Their platform is rock solid and the 85% profit split is one of the best in the industry. Payouts are processed within 48 hours as promised.',
    date: '2025-08-10',
    verified: true,
    helpful: 53,
    userLocation: 'Toronto, Canada',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 13200,
    payoutReceived: true
  },
  {
    id: 'funded7-review-2',
    firmId: 'funded7',
    userName: 'Olivia Johnson',
    userAvatar: '/avatars/olivia-johnson.jpg',
    rating: 4,
    title: 'Great instant funding option',
    content: 'I chose Funded7\'s instant funding model and was trading with real capital within hours. The verification process was smooth and their customer service is excellent. The only reason for 4 stars instead of 5 is that their platform had some minor latency issues during major news events.',
    date: '2025-09-02',
    verified: true,
    helpful: 38,
    userLocation: 'Chicago, USA',
    tradingExperience: '7 years',
    accountSize: '$75,000',
    profitMade: 9800,
    payoutReceived: true
  },
  {
    id: 'funded7-review-3',
    firmId: 'funded7',
    userName: 'Thomas Schmidt',
    userAvatar: '/avatars/thomas-schmidt.jpg',
    rating: 5,
    title: 'Transparent and trustworthy',
    content: 'What sets Funded7 apart is their transparency. All rules are clearly explained, no hidden conditions. I\'ve been with them for 4 months and have received 3 payouts so far, all processed quickly and accurately. Their educational webinars are also very informative and practical.',
    date: '2025-07-15',
    verified: true,
    helpful: 47,
    userLocation: 'Berlin, Germany',
    tradingExperience: '4 years',
    accountSize: '$150,000',
    profitMade: 18500,
    payoutReceived: true
  },
  
  // Aqua Funded Reviews
  {
    id: 'aqua-funded-review-1',
    firmId: 'aqua-funded',
    userName: 'Rebecca Taylor',
    userAvatar: '/avatars/rebecca-taylor.jpg',
    rating: 5,
    title: 'Best customer support in the industry',
    content: 'Aqua Funded has set a new standard for customer support in the prop trading industry. I had several questions during my evaluation phase, and their team was always available with detailed and helpful responses. The trading conditions are excellent with tight spreads and fast execution.',
    date: '2025-09-12',
    verified: true,
    helpful: 29,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '2 years',
    accountSize: '$50,000',
    profitMade: 6200,
    payoutReceived: true
  },
  {
    id: 'aqua-funded-review-2',
    firmId: 'aqua-funded',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 5,
    title: 'Transparent evaluation process',
    content: 'What I appreciate most about Aqua Funded is their transparent evaluation process. The rules are clear, fair, and consistent. No hidden conditions or sudden changes. I passed their challenge in 3 weeks and was trading a funded account shortly after. Their platform is also very stable with minimal downtime.',
    date: '2025-08-28',
    verified: true,
    helpful: 34,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 12800,
    payoutReceived: true
  },
  {
    id: 'aqua-funded-review-3',
    firmId: 'aqua-funded',
    userName: 'Lisa Martinez',
    userAvatar: '/avatars/lisa-martinez.jpg',
    rating: 4,
    title: 'Great for forex traders',
    content: 'Aqua Funded is particularly good for forex traders like myself. Their spreads are competitive and execution is fast. I\'ve been with them for 3 months and have had a positive experience overall. The only improvement I\'d suggest is adding more educational resources for newer traders.',
    date: '2025-09-05',
    verified: true,
    helpful: 22,
    userLocation: 'Miami, USA',
    tradingExperience: '3 years',
    accountSize: '$75,000',
    profitMade: 8900,
    payoutReceived: true
  },
  
  // Funded Kingdom Reviews
  {
    id: 'funded-kingdom-review-1',
    firmId: 'funded-kingdom',
    userName: 'Alexander Brown',
    userAvatar: '/avatars/alexander-brown.jpg',
    rating: 5,
    title: 'Love the gamified approach!',
    content: 'Funded Kingdom\'s level-based approach makes the evaluation process much more engaging. It feels like you\'re progressing through a game while actually building real trading skills. I\'ve reached Level 4 and am now managing a $200K account. Their platform is excellent and the community is very supportive.',
    date: '2025-08-15',
    verified: true,
    helpful: 56,
    userLocation: 'London, UK',
    tradingExperience: '4 years',
    accountSize: '$200,000',
    profitMade: 23500,
    payoutReceived: true
  },
  {
    id: 'funded-kingdom-review-2',
    firmId: 'funded-kingdom',
    userName: 'Sophia Lee',
    userAvatar: '/avatars/sophia-lee.jpg',
    rating: 4,
    title: 'Great concept but needs some refinement',
    content: 'The gamified evaluation model is innovative and motivating. I enjoy the clear progression path and achievement system. However, some of the level transitions can be a bit challenging. Their customer support is excellent though, and they\'re always open to feedback for improving the system.',
    date: '2025-09-01',
    verified: true,
    helpful: 42,
    userLocation: 'Hong Kong',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 12000,
    payoutReceived: true
  },
  {
    id: 'funded-kingdom-review-3',
    firmId: 'funded-kingdom',
    userName: 'Ryan Wilson',
    userAvatar: '/avatars/ryan-wilson.jpg',
    rating: 5,
    title: 'Perfect for goal-oriented traders',
    content: 'If you\'re a goal-oriented trader who enjoys clear milestones, Funded Kingdom is perfect for you. Their level system provides a clear roadmap for growth, and the rewards at each level are substantial. I particularly appreciate their community features where you can compare progress with other traders.',
    date: '2025-08-22',
    verified: true,
    helpful: 38,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '3 years',
    accountSize: '$150,000',
    profitMade: 16800,
    payoutReceived: true
  },
  
  // Fundora Reviews
  {
    id: 'fundora-review-1',
    firmId: 'fundora',
    userName: 'Hiroshi Tanaka',
    userAvatar: '/avatars/hiroshi-tanaka.jpg',
    rating: 5,
    title: 'Excellent for Asian market traders',
    content: 'As someone who primarily trades Asian markets, Fundora has been the perfect fit. Their platform is optimized for trading during Asian hours, and their support team is available when I need them. The two-phase challenge is fair and well-structured, and I appreciate that there\'s no time limit to complete it.',
    date: '2025-08-05',
    verified: true,
    helpful: 42,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'fundora-review-2',
    firmId: 'fundora',
    userName: 'Sarah Johnson',
    userAvatar: '/avatars/sarah-johnson.jpg',
    rating: 4,
    title: 'Great platform with monthly payouts',
    content: 'Fundora offers a stable trading environment with excellent execution. Their educational resources are particularly helpful for developing trading strategies. The only drawback is the monthly payout schedule, which is slower than some competitors. However, the payouts are always accurate and reliable.',
    date: '2025-09-10',
    verified: true,
    helpful: 35,
    userLocation: 'Sydney, Australia',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 13500,
    payoutReceived: true
  },
  {
    id: 'fundora-review-3',
    firmId: 'fundora',
    userName: 'Michael Zhang',
    userAvatar: '/avatars/michael-zhang.jpg',
    rating: 5,
    title: 'Perfect for gold traders',
    content: 'Fundora\'s gold swap-free trading is a game-changer for me as a primarily gold trader. I can hold positions overnight without worrying about swap fees. Their platform is very stable, and the execution speed is excellent. The 80% profit split is competitive, and I\'ve had no issues with payouts so far.',
    date: '2025-07-25',
    verified: true,
    helpful: 29,
    userLocation: 'Shanghai, China',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 18200,
    payoutReceived: true
  },

  // FTMO Reviews - Industry Leader
  {
    id: 'ftmo-review-1',
    firmId: 'ftmo',
    userName: 'Marcus Johnson',
    userAvatar: '/avatars/marcus-johnson.jpg',
    rating: 5,
    title: 'Industry standard for a reason',
    content: 'FTMO has been the gold standard in prop trading for years, and after completing their 2-step challenge, I understand why. The evaluation process is tough but fair, and their MetaTrader integration is flawless. I passed both phases in 6 weeks and received my first payout within 48 hours. The 90% profit split after scaling is exceptional. Their customer support is professional and responsive, and the trading conditions are exactly as advertised. If you\'re serious about prop trading, FTMO should be your first choice.',
    date: '2024-09-28',
    verified: true,
    helpful: 142,
    userLocation: 'London, UK',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 28500,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-2',
    firmId: 'ftmo',
    userName: 'Sarah Kim',
    userAvatar: '/avatars/sarah-kim.jpg',
    rating: 5,
    title: 'Professional platform, excellent support',
    content: 'As someone who has tried multiple prop firms, FTMO stands out for their professionalism and transparency. The rules are clearly defined, and there are no hidden surprises. I particularly appreciate their free retake policy and the comprehensive trading analytics they provide. The scaling plan is realistic and achievable. Currently managing $400K in capital after 8 months, and every payout has been processed on time. Worth every penny of the evaluation fee.',
    date: '2024-10-02',
    verified: true,
    helpful: 98,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '5 years',
    accountSize: '$400,000',
    profitMade: 52000,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-3',
    firmId: 'ftmo',
    userName: 'Roberto Martinez',
    userAvatar: '/avatars/roberto-martinez.jpg',
    rating: 4,
    title: 'Challenging but rewarding',
    content: 'FTMO\'s evaluation is definitely challenging - it took me three attempts to pass, but that\'s actually a good thing. It ensures only disciplined traders get funded. The 10% profit target in phase 1 requires patience and strategy. Once funded, the experience has been excellent. Fast payouts, good spreads, and no issues with order execution. The only downside is the initial cost, but the refund policy makes it reasonable. If you can pass their challenge, you\'re ready for serious trading.',
    date: '2024-08-15',
    verified: true,
    helpful: 76,
    userLocation: 'Madrid, Spain',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 15200,
    payoutReceived: true
  },
  {
    id: 'ftmo-review-4',
    firmId: 'ftmo',
    userName: 'Jennifer Wu',
    userAvatar: '/avatars/jennifer-wu.jpg',
    rating: 5,
    title: 'Best risk management education',
    content: 'Beyond just providing capital, FTMO has taught me invaluable risk management skills. Their maximum drawdown rules and daily loss limits forced me to become a better trader. The FTMO dashboard is incredibly detailed, showing every metric you need to track your performance. I\'ve been with them for over a year now, scaled to $200K, and the consistency in payouts and support has been remarkable. Highly recommended for both new and experienced traders.',
    date: '2024-09-12',
    verified: true,
    helpful: 89,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 31000,
    payoutReceived: true
  },

  // Apex Trader Funding Reviews - Futures Leader
  {
    id: 'apex-review-1',
    firmId: 'apex-trader-funding',
    userName: 'Tyler Henderson',
    userAvatar: '/avatars/tyler-henderson.jpg',
    rating: 5,
    title: 'Best futures prop firm, hands down',
    content: 'Apex has completely transformed my futures trading career. The Rithmic and Tradovate platform integration is seamless with near-zero latency. I chose their $50K account and passed the evaluation in just 11 days trading ES and NQ. The 90% profit split is generous, and payouts are processed every Friday like clockwork. No time limits, no minimum trading days - just pure performance-based funding. Their scaling plan is aggressive in the best way. After 5 months, I\'m now trading a $250K account. Customer support responds within hours, not days.',
    date: '2024-10-05',
    verified: true,
    helpful: 156,
    userLocation: 'Chicago, USA',
    tradingExperience: '8 years',
    accountSize: '$250,000',
    profitMade: 47000,
    payoutReceived: true
  },
  {
    id: 'apex-review-2',
    firmId: 'apex-trader-funding',
    userName: 'Michelle Tan',
    userAvatar: '/avatars/michelle-tan.jpg',
    rating: 5,
    title: 'Futures trading done right',
    content: 'I\'ve been with Apex for 6 months and it\'s been nothing but positive. The evaluation is straightforward - hit the profit target without breaking the max loss rules. No complicated requirements or hidden terms. The platform options (Rithmic, Tradovate, Quantower) give you flexibility to use what works best. I trade mostly micros and minis, and the execution is flawless. Payouts arrive in my account within 2-3 days of request. The Discord community is also very helpful with experienced traders sharing strategies.',
    date: '2024-09-20',
    verified: true,
    helpful: 103,
    userLocation: 'Singapore',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'apex-review-3',
    firmId: 'apex-trader-funding',
    userName: 'Derek Williams',
    userAvatar: '/avatars/derek-williams.jpg',
    rating: 4,
    title: 'Great firm, minor platform issues',
    content: 'Apex is excellent for futures traders. The evaluation process is fair and achievable - I passed in 18 days trading crude oil and gold futures. The profit split is among the best, and scaling is quick if you\'re consistent. My only complaint is occasional platform disconnections during high volatility (happened twice in 4 months), but their support team was responsive and understanding. Overall, highly recommend for anyone serious about futures trading. The lack of time pressure makes it less stressful than other firms.',
    date: '2024-08-30',
    verified: true,
    helpful: 67,
    userLocation: 'Dallas, USA',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 18500,
    payoutReceived: true
  },
  {
    id: 'apex-review-4',
    firmId: 'apex-trader-funding',
    userName: 'Priya Sharma',
    userAvatar: '/avatars/priya-sharma.jpg',
    rating: 5,
    title: 'Perfect for disciplined traders',
    content: 'What I love most about Apex is their trader-first approach. No time limits means you can trade your strategy without feeling rushed. The $50 monthly platform fee is more than worth it for the professional tools and data feeds. I trade both day and swing strategies on ES futures, and both work perfectly within their rules. The evaluation metrics are clearly displayed in real-time, so you always know where you stand. Three successful payouts so far, each processed faster than promised. If you\'re disciplined and have a solid strategy, Apex is the place to be.',
    date: '2024-09-08',
    verified: true,
    helpful: 94,
    userLocation: 'Mumbai, India',
    tradingExperience: '4 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },

  // TopStep Reviews - Futures Veteran
  {
    id: 'topstep-review-1',
    firmId: 'topstep',
    userName: 'Brandon Miller',
    userAvatar: '/avatars/brandon-miller.jpg',
    rating: 5,
    title: 'Pioneer in futures prop trading',
    content: 'TopStep has been around since 2012, and their experience shows. The Trading Combine is well-structured and teaches you discipline before giving you real capital. I trade primarily ES and CL futures, and their platform integration with multiple brokers gives great flexibility. Passed my combine in 4 weeks and have been funded for 8 months now. The 80% profit split is fair, and I appreciate their transparent rules. Customer support is top-notch - they actually understand futures trading. Great educational resources too.',
    date: '2024-09-25',
    verified: true,
    helpful: 134,
    userLocation: 'New York, USA',
    tradingExperience: '9 years',
    accountSize: '$150,000',
    profitMade: 34000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-2',
    firmId: 'topstep',
    userName: 'Jessica Lee',
    userAvatar: '/avatars/jessica-lee.jpg',
    rating: 4,
    title: 'Solid and reliable',
    content: 'TopStep is one of the most established prop firms, and it shows in their professionalism. The combine takes patience - I failed twice before passing, but the reset option is helpful. Once funded, the experience has been smooth. Payouts are processed on the 15th of each month consistently. The rules are strict but fair, focusing on consistency rather than home-run trades. My only critique is the monthly fee during the combine, but it keeps traders serious. Overall, a trustworthy firm for futures traders.',
    date: '2024-08-18',
    verified: true,
    helpful: 89,
    userLocation: 'Austin, USA',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 19000,
    payoutReceived: true
  },
  {
    id: 'topstep-review-3',
    firmId: 'topstep',
    userName: 'David Chen',
    userAvatar: '/avatars/david-chen.jpg',
    rating: 5,
    title: 'Best for learning futures discipline',
    content: 'What makes TopStep special is their focus on trader development. The combine isn\'t just an evaluation - it\'s education. The daily loss limit and profit target goals forced me to develop a consistent strategy. Been funded for 6 months, trading NQ and YM futures. The bi-weekly payout option is convenient, and the funded account rules are clear. Their trading room and coaching sessions add real value. If you want to become a professional futures trader, TopStep is an excellent choice.',
    date: '2024-10-03',
    verified: true,
    helpful: 102,
    userLocation: 'San Francisco, USA',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 27500,
    payoutReceived: true
  },

  // FundedNext Reviews - Aggressive Scaling
  {
    id: 'fundednext-review-1',
    firmId: 'fundednext',
    userName: 'Omar Hassan',
    userAvatar: '/avatars/omar-hassan.jpg',
    rating: 5,
    title: 'Incredible 15% profit split model',
    content: 'FundedNext\'s Stellar Lite program with 15% profit split on first payout is absolutely game-changing. I couldn\'t believe it when I received 100% of my first profit plus 15% bonus. The evaluation is fair with reasonable profit targets and drawdown limits. I passed the 2-phase challenge in 5 weeks trading EUR/USD and Gold. Their platform choices (MT4/MT5/cTrader/DXtrade) cover every preference. Customer support via Telegram is incredibly responsive. Scaling plan is aggressive - already doubled my account size in 3 months.',
    date: '2024-10-08',
    verified: true,
    helpful: 167,
    userLocation: 'Dubai, UAE',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 41000,
    payoutReceived: true
  },
  {
    id: 'fundednext-review-2',
    firmId: 'fundednext',
    userName: 'Rachel Anderson',
    userAvatar: '/avatars/rachel-anderson.jpg',
    rating: 5,
    title: 'Multiple models for different traders',
    content: 'I love that FundedNext offers multiple challenge types - Express, Evaluation, and Stellar programs. I chose the Evaluation model for the higher profit split. The consistency rule (10% requirement) actually helps develop good trading habits. Passed both phases in my first attempt. EA trading is allowed which is perfect for my strategy. Payouts processed within 48 hours as promised. The educational content and market analysis they provide is surprisingly detailed. Best prop firm I\'ve worked with.',
    date: '2024-09-19',
    verified: true,
    helpful: 121,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 23000,
    payoutReceived: true
  },
  {
    id: 'fundednext-review-3',
    firmId: 'fundednext',
    userName: 'Thomas Berg',
    userAvatar: '/avatars/thomas-berg.jpg',
    rating: 4,
    title: 'Great value, minor verification delays',
    content: 'FundedNext offers excellent value with competitive pricing and high profit splits. The Express challenge is perfect if you want quicker access to funding. I trade mostly indices and commodities, and spreads are competitive. Verification took longer than expected (5 days), but once cleared, everything has been smooth. On my second payout now, both processed correctly. The consistency requirement requires planning but is achievable. Recommend for traders who want flexibility and good profit sharing.',
    date: '2024-08-27',
    verified: true,
    helpful: 78,
    userLocation: 'Stockholm, Sweden',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 8900,
    payoutReceived: true
  },

  // City Traders Imperium Reviews - UK Leader
  {
    id: 'cti-review-1',
    firmId: 'city-traders-imperium',
    userName: 'James Sterling',
    userAvatar: '/avatars/james-sterling.jpg',
    rating: 5,
    title: 'UK-based professionalism',
    content: 'City Traders Imperium stands out as one of the most professional firms I\'ve encountered. Being UK-based and FCA-monitored provides extra peace of mind. Their 3-phase evaluation is comprehensive but fair, focusing on risk management and consistency. I appreciated the detailed performance metrics and feedback throughout. Once funded, the 75% profit split is good, and payouts are reliable. Trade ES, GBP/USD, and DAX with excellent execution. The community aspect with trading rooms and mentorship is valuable.',
    date: '2024-09-22',
    verified: true,
    helpful: 118,
    userLocation: 'London, UK',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 29000,
    payoutReceived: true
  },
  {
    id: 'cti-review-2',
    firmId: 'city-traders-imperium',
    userName: 'Sophie Martin',
    userAvatar: '/avatars/sophie-martin.jpg',
    rating: 5,
    title: 'Excellent education and support',
    content: 'What I love about CTI is their holistic approach. It\'s not just about passing a challenge - they invest in trader education. The Master Your Mind program and weekly webinars significantly improved my trading psychology. The evaluation process has clear objectives for each phase. Passed all 3 phases in 9 weeks. The funded account rules are transparent with no hidden surprises. Support team is knowledgeable and helpful. Payouts come through monthly as scheduled. Great for traders who value ongoing education.',
    date: '2024-10-01',
    verified: true,
    helpful: 93,
    userLocation: 'Paris, France',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 17500,
    payoutReceived: true
  },
  {
    id: 'cti-review-3',
    firmId: 'city-traders-imperium',
    userName: 'Michael O\'Brien',
    userAvatar: '/avatars/michael-obrien.jpg',
    rating: 4,
    title: 'Professional but slower payout',
    content: 'CTI is highly professional with a structured evaluation process. The 3-phase model ensures only consistent traders get funded, which I respect. Trading conditions are good with tight spreads on major pairs. My only complaint is the monthly payout frequency - would prefer bi-weekly like some competitors. However, when payouts come, they\'re always accurate and reliable. The UK regulatory oversight is reassuring. Good choice for traders who prioritize security and professional operations.',
    date: '2024-08-14',
    verified: true,
    helpful: 67,
    userLocation: 'Dublin, Ireland',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 14200,
    payoutReceived: true
  },

  // E8 Funding Reviews - Multi-Asset Expert
  {
    id: 'e8-review-1',
    firmId: 'e8-funding',
    userName: 'Alexei Volkov',
    userAvatar: '/avatars/alexei-volkov.jpg',
    rating: 5,
    title: 'Best crypto prop firm',
    content: 'E8 Funding is the only serious prop firm offering crypto funding. Their Elev8 and Track8 programs give flexibility in evaluation style. I trade Bitcoin and Ethereum futures primarily, and the execution is excellent. Passed Track8 evaluation in 3 weeks with Bitcoin CFDs. The 80% profit split is competitive, and they allow both MT4/MT5 and DXtrade. Payouts are processed twice monthly and always on time. If you want to trade crypto with prop firm capital, E8 is your best option.',
    date: '2024-10-04',
    verified: true,
    helpful: 145,
    userLocation: 'Prague, Czech Republic',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'e8-review-2',
    firmId: 'e8-funding',
    userName: 'Maya Patel',
    userAvatar: '/avatars/maya-patel.jpg',
    rating: 5,
    title: 'Comprehensive multi-asset platform',
    content: 'E8 offers the widest range of instruments I\'ve seen - Forex, indices, commodities, crypto, and stocks. I trade a diversified portfolio which their platform handles perfectly. The Elev8 program\'s single-phase evaluation is efficient. Achieved profit target in 4 weeks trading mix of GBP/JPY, Gold, and BTC. Support is responsive and knowledgeable across all asset classes. Scaling plan is transparent. Three successful payouts so far. Great for traders who don\'t want to be limited to just forex.',
    date: '2024-09-16',
    verified: true,
    helpful: 108,
    userLocation: 'Mumbai, India',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 19500,
    payoutReceived: true
  },
  {
    id: 'e8-review-3',
    firmId: 'e8-funding',
    userName: 'Luis Fernandez',
    userAvatar: '/avatars/luis-fernandez.jpg',
    rating: 4,
    title: 'Great platform, learning curve',
    content: 'E8\'s multi-asset offering is impressive, though it took time to understand all the options. I went with Track8 two-phase challenge which felt more familiar coming from other firms. Trading conditions are solid, and the ability to trade stocks as CFDs opened new opportunities. Passed evaluation in 6 weeks. Payouts come bi-monthly as stated. My only issue was some confusion about rules for different asset classes initially, but support clarified quickly. Solid choice for experienced traders wanting variety.',
    date: '2024-08-21',
    verified: true,
    helpful: 72,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '5 years',
    accountSize: '$75,000',
    profitMade: 11000,
    payoutReceived: true
  },

  // DNA Funded Reviews - Transparent Operations
  {
    id: 'dna-review-1',
    firmId: 'dna-funded',
    userName: 'Kevin Wright',
    userAvatar: '/avatars/kevin-wright.jpg',
    rating: 5,
    title: 'Most transparent firm I\'ve found',
    content: 'DNA Funded lives up to their transparency promise. Everything is clearly explained - no hidden fees, no surprise rule changes. Their evaluation process is straightforward with clear profit targets and drawdown rules. I particularly appreciate their trader dashboard showing real-time stats. Passed the challenge in 5 weeks trading GBP/USD and EUR/JPY. The 80% profit split is fair, and they allow news trading and EAs. Payouts processed within 72 hours consistently. Support team is honest and responsive.',
    date: '2024-09-30',
    verified: true,
    helpful: 112,
    userLocation: 'Toronto, Canada',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 21000,
    payoutReceived: true
  },
  {
    id: 'dna-review-2',
    firmId: 'dna-funded',
    userName: 'Isabella Romano',
    userAvatar: '/avatars/isabella-romano.jpg',
    rating: 5,
    title: 'Refreshing honesty in the industry',
    content: 'After bad experiences with other firms, DNA Funded\'s transparency was refreshing. No gimmicks, no misleading marketing - just honest prop trading. The evaluation is challenging but achievable with proper risk management. I trade primarily indices and commodities. Platform integration with MT4/MT5 is smooth. Scaling options are clearly laid out from day one. Been funded for 7 months with 4 successful payouts. They treat traders with respect and professionalism. Highly recommend.',
    date: '2024-10-06',
    verified: true,
    helpful: 97,
    userLocation: 'Milan, Italy',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 26000,
    payoutReceived: true
  },
  {
    id: 'dna-review-3',
    firmId: 'dna-funded',
    userName: 'Daniel Kim',
    userAvatar: '/avatars/daniel-kim.jpg',
    rating: 4,
    title: 'Solid firm, could improve scaling',
    content: 'DNA Funded delivers on their transparency promise. Rules are clear, no hidden catches. Evaluation process is fair - passed in my second attempt after learning from first. Trading conditions are good with competitive spreads. Payouts arrive as promised. My only feedback is the scaling plan could be more aggressive compared to competitors. That said, the consistency-based approach makes sense for sustainable growth. Good choice for traders who value straightforward terms and honest operations.',
    date: '2024-08-19',
    verified: true,
    helpful: 68,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '4 years',
    accountSize: '$50,000',
    profitMade: 7800,
    payoutReceived: true
  },

  // Take Profit Trader Reviews - Futures Innovator
  {
    id: 'tpt-review-1',
    firmId: 'take-profit-trader',
    userName: 'Nathan Brooks',
    userAvatar: '/avatars/nathan-brooks.jpg',
    rating: 5,
    title: 'Best futures evaluation structure',
    content: 'Take Profit Trader has the most trader-friendly futures evaluation I\'ve experienced. No time limits, no minimum trading days, just pure performance metrics. I trade ES and NQ exclusively, and their platform supports all major futures brokers. Passed evaluation in 16 days with consistent small gains - exactly how they encourage you to trade. The 80% profit split increases to 90% which is excellent. Payouts every two weeks like clockwork. Been funded for 5 months and very satisfied.',
    date: '2024-09-27',
    verified: true,
    helpful: 129,
    userLocation: 'Denver, USA',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 31000,
    payoutReceived: true
  },
  {
    id: 'tpt-review-2',
    firmId: 'take-profit-trader',
    userName: 'Emily Watson',
    userAvatar: '/avatars/emily-watson.jpg',
    rating: 5,
    title: 'No-pressure evaluation perfect for my style',
    content: 'The lack of time pressure at Take Profit Trader made all the difference for me. I could trade my strategy without feeling rushed to hit targets. Took me 4 weeks to pass evaluation trading crude oil and gold futures. Their risk management rules are sensible and teach good habits. Customer support understands futures trading deeply. Scaling is straightforward based on consistent profits. Already upgraded from $50K to $100K account. Payouts arrive in my account within 48 hours of request.',
    date: '2024-10-02',
    verified: true,
    helpful: 94,
    userLocation: 'Seattle, USA',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 18000,
    payoutReceived: true
  },
  {
    id: 'tpt-review-3',
    firmId: 'take-profit-trader',
    userName: 'Roberto Silva',
    userAvatar: '/avatars/roberto-silva.jpg',
    rating: 4,
    title: 'Great for swing traders',
    content: 'Take Profit Trader is perfect if you\'re a swing trader like me. No daily trading requirements means I can hold positions overnight when my strategy calls for it. Evaluation rules are clear and fair. Passed in 3 weeks trading NQ and YM. The profit targets are achievable without taking excessive risk. One minor issue was delayed response from support during weekends, but weekday support is excellent. Overall, highly recommend for traders who prefer low-pressure, consistency-focused evaluation.',
    date: '2024-08-25',
    verified: true,
    helpful: 71,
    userLocation: 'São Paulo, Brazil',
    tradingExperience: '6 years',
    accountSize: '$75,000',
    profitMade: 12500,
    payoutReceived: true
  },

  // FXIFY Reviews - Fast Growing
  {
    id: 'fxify-review-1',
    firmId: 'fxify',
    userName: 'Chris Taylor',
    userAvatar: '/avatars/chris-taylor.jpg',
    rating: 5,
    title: 'Rapid growth with excellent conditions',
    content: 'FXIFY impressed me from day one. Their evaluation process is well-designed with clear milestones. I chose the 2-step challenge and passed both phases in 5 weeks trading EUR/USD and GBP/JPY. The 90% profit split is among the highest I\'ve seen. Platform choice includes MT4, MT5, cTrader, and Match-Trader. Spreads are tight, execution is fast. Their scaling plan is aggressive - already moved from $100K to $200K in 4 months. Payouts processed within 24-48 hours consistently.',
    date: '2024-10-07',
    verified: true,
    helpful: 138,
    userLocation: 'Manchester, UK',
    tradingExperience: '7 years',
    accountSize: '$200,000',
    profitMade: 39000,
    payoutReceived: true
  },
  {
    id: 'fxify-review-2',
    firmId: 'fxify',
    userName: 'Yuki Tanaka',
    userAvatar: '/avatars/yuki-tanaka.jpg',
    rating: 5,
    title: 'Modern approach to prop funding',
    content: 'FXIFY feels like a next-generation prop firm. Everything from their website to their trader dashboard is modern and user-friendly. The evaluation tracks are flexible - I chose the slower track for more manageable targets. Passed in 6 weeks with consistent gains. EA trading is fully supported which works perfectly for my algorithmic strategy. Support team is available 24/5 and genuinely helpful. Been funded 3 months with flawless payout experiences. Great for both discretionary and algo traders.',
    date: '2024-09-14',
    verified: true,
    helpful: 103,
    userLocation: 'Tokyo, Japan',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'fxify-review-3',
    firmId: 'fxify',
    userName: 'Marcus Anderson',
    userAvatar: '/avatars/marcus-anderson.jpg',
    rating: 4,
    title: 'Excellent but still building track record',
    content: 'FXIFY is a newer firm but they\'re doing things right. The evaluation process is fair with reasonable targets. I like the multiple challenge options catering to different risk appetites. Passed the aggressive track in 4 weeks. Trading conditions are competitive with good spreads. Payouts have been reliable so far (2 received). The only reason for 4 stars is they\'re still building their long-term track record, but all signs point to them being a solid choice. Recommend giving them a try.',
    date: '2024-08-29',
    verified: true,
    helpful: 76,
    userLocation: 'Cape Town, South Africa',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // The 5%ers Reviews - Scaling Specialists
  {
    id: '5percenters-review-1',
    firmId: 'the-5-percenters',
    userName: 'Andreas Mueller',
    userAvatar: '/avatars/andreas-mueller.jpg',
    rating: 5,
    title: 'Unmatched scaling to $4M',
    content: 'The 5%ers is not your typical prop firm - their Hyper Growth program is truly unique. I started with a $6K account and within 9 months, I\'ve scaled to $250K. The bootcamp style evaluation teaches you proper risk management while you earn. What really sets them apart is the potential to scale up to $4 million, which is unheard of elsewhere. The profit split increases as you progress, currently at 80% and heading to 100%. Payouts are bi-weekly and always on time. Their multi-platform support (MT4, MT5, cTrader) is excellent.',
    date: '2024-10-01',
    verified: true,
    helpful: 128,
    userLocation: 'Berlin, Germany',
    tradingExperience: '7 years',
    accountSize: '$250,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: '5percenters-review-2',
    firmId: 'the-5-percenters',
    userName: 'Lisa Chang',
    userAvatar: '/avatars/lisa-chang.jpg',
    rating: 5,
    title: 'Bootcamp program is genius',
    content: 'The 3-step bootcamp model was perfect for me as an intermediate trader. Each phase builds on the last, gradually increasing your account size while maintaining consistent risk management. I appreciate that they allow EA trading and news trading - no artificial restrictions. The High Stakes program is challenging but rewarding. Support team is knowledgeable and actually understands trading. Six months in, scaled from $20K to $100K, and looking forward to the next level. The profit split progression is very motivating.',
    date: '2024-09-15',
    verified: true,
    helpful: 87,
    userLocation: 'Hong Kong',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 16500,
    payoutReceived: true
  },
  {
    id: '5percenters-review-3',
    firmId: 'the-5-percenters',
    userName: 'Carlos Rodriguez',
    userAvatar: '/avatars/carlos-rodriguez.jpg',
    rating: 4,
    title: 'Excellent but requires patience',
    content: 'The 5%ers offers something special with their scaling approach. The bootcamp program takes time - it\'s not instant funding - but the education and gradual progression make you a better trader. I\'m currently in phase 2 of the bootcamp and already seeing improvement in my discipline. The 8% profit target is reasonable, and the static drawdown rules are clear. My only critique is that the progression can feel slow if you\'re aggressive, but I understand it\'s designed for long-term success. Looking forward to reaching the higher tiers.',
    date: '2024-08-22',
    verified: true,
    helpful: 62,
    userLocation: 'Mexico City, Mexico',
    tradingExperience: '4 years',
    accountSize: '$40,000',
    profitMade: 5200,
    payoutReceived: true
  },
  {
    id: '5percenters-review-4',
    firmId: 'the-5-percenters',
    userName: 'Nina Petrov',
    userAvatar: '/avatars/nina-petrov.jpg',
    rating: 5,
    title: 'Long-term partnership, not just funding',
    content: 'After 14 months with The 5%ers, I can confidently say this is the best prop firm for traders who think long-term. The hyper growth scaling is real - I\'ve gone from $10K to $500K. The profit split increasing to 100% is incredible motivation. They truly invest in their traders with regular webinars and strategy sessions. cTrader integration is smooth, and the spread conditions are competitive. Payouts are always processed on schedule. This isn\'t a get-rich-quick scheme; it\'s a professional trading partnership.',
    date: '2024-09-28',
    verified: true,
    helpful: 115,
    userLocation: 'Moscow, Russia',
    tradingExperience: '9 years',
    accountSize: '$500,000',
    profitMade: 72000,
    payoutReceived: true
  },

  // Darwinex Reviews - Multi-Asset Pioneer
  {
    id: 'darwinex-review-1',
    firmId: 'darwinex',
    userName: 'Sebastian Werner',
    userAvatar: '/avatars/sebastian-werner.jpg',
    rating: 5,
    title: 'Unique investment platform for traders',
    content: 'Darwinex is unlike any other prop firm - they offer both traditional funding and the ability to attract investor capital through DARWINs. I\'ve been trading with them for over a year, and the transparency is remarkable. You keep 100% of your profits, plus 20% of investor profits on your DARWIN. The FCA regulation provides peace of mind. Platform integration with MT4/MT5 is seamless. Risk management tools are sophisticated. If you want to build a track record that attracts real investors, Darwinex is the best choice.',
    date: '2024-09-24',
    verified: true,
    helpful: 156,
    userLocation: 'Frankfurt, Germany',
    tradingExperience: '10 years',
    accountSize: '$200,000',
    profitMade: 42000,
    payoutReceived: true
  },
  {
    id: 'darwinex-review-2',
    firmId: 'darwinex',
    userName: 'Charlotte Davies',
    userAvatar: '/avatars/charlotte-davies.jpg',
    rating: 5,
    title: 'Revolutionary approach to prop funding',
    content: 'What sets Darwinex apart is the DARWIN investment platform. You trade your strategy, and if it performs well, investors allocate capital to it. I started with their demo account and progressed to live funding. The analytics dashboard is incredibly detailed with 40+ metrics. FCA regulation means your capital is protected. Customer support is excellent and truly understands trading. Been with them 18 months and have attracted over $500K in investor capital. This is the future of prop trading.',
    date: '2024-10-03',
    verified: true,
    helpful: 134,
    userLocation: 'London, UK',
    tradingExperience: '8 years',
    accountSize: '$500,000',
    profitMade: 87000,
    payoutReceived: true
  },
  {
    id: 'darwinex-review-3',
    firmId: 'darwinex',
    userName: 'Marco Bellini',
    userAvatar: '/avatars/marco-bellini.jpg',
    rating: 4,
    title: 'Sophisticated but requires consistency',
    content: 'Darwinex is for serious, consistent traders. The evaluation period requires 6+ months of track record, which is longer than most firms but ensures quality. The DARWIN metrics system is complex initially but incredibly valuable once you understand it. Trading conditions are excellent with tight spreads. The investor allocation model is brilliant - passive income from your trading skill. My only critique is the learning curve is steep. Great for experienced traders committed to long-term success.',
    date: '2024-08-28',
    verified: true,
    helpful: 89,
    userLocation: 'Milan, Italy',
    tradingExperience: '12 years',
    accountSize: '$300,000',
    profitMade: 51000,
    payoutReceived: true
  },

  // Audacity Capital Reviews - Instant Funding Specialist
  {
    id: 'audacity-review-1',
    firmId: 'audacity-capital',
    userName: 'Jonathan Price',
    userAvatar: '/avatars/jonathan-price.jpg',
    rating: 5,
    title: 'True instant funding, no evaluation',
    content: 'Audacity Capital delivers on their instant funding promise. After submitting my trading history and passing their interview, I was trading live capital within 48 hours. No lengthy evaluation challenges. They focus on experienced traders with proven track records. The 75% profit split is fair, and spreads are among the tightest I\'ve experienced. Monthly payouts are reliable. Their educational webinars add real value. Been with them for 10 months and scaled from $50K to $150K. Perfect for traders who can prove their ability.',
    date: '2024-09-26',
    verified: true,
    helpful: 127,
    userLocation: 'Birmingham, UK',
    tradingExperience: '9 years',
    accountSize: '$150,000',
    profitMade: 29000,
    payoutReceived: true
  },
  {
    id: 'audacity-review-2',
    firmId: 'audacity-capital',
    userName: 'Emma Thompson',
    userAvatar: '/avatars/emma-thompson.jpg',
    rating: 4,
    title: 'Great for experienced traders',
    content: 'Audacity\'s instant funding model is refreshing if you have a solid track record. The interview process was thorough but professional. Once approved, access to capital is immediate. Trading conditions are excellent with tight spreads and good execution. The rules are strict but transparent. Monthly payout frequency is slower than some competitors, but payments always arrive on time. Support team is knowledgeable. Good choice if you want to skip evaluation challenges and start trading immediately.',
    date: '2024-08-19',
    verified: true,
    helpful: 78,
    userLocation: 'Manchester, UK',
    tradingExperience: '7 years',
    accountSize: '$75,000',
    profitMade: 13500,
    payoutReceived: true
  },
  {
    id: 'audacity-review-3',
    firmId: 'audacity-capital',
    userName: 'Richard Foster',
    userAvatar: '/avatars/richard-foster.jpg',
    rating: 5,
    title: 'Professional operation from day one',
    content: 'As someone who\'s been prop trading for over a decade, Audacity Capital impressed me with their professionalism. The instant funding model saved me months of evaluation. Their focus on risk management and trader education shows they want long-term partnerships. Platform integration with MT4/MT5 is flawless. The tight spreads and execution quality are consistently good. Five months in with steady profits and reliable monthly payouts. Highly recommend for traders with proven strategies.',
    date: '2024-10-01',
    verified: true,
    helpful: 94,
    userLocation: 'Leeds, UK',
    tradingExperience: '11 years',
    accountSize: '$100,000',
    profitMade: 21000,
    payoutReceived: true
  },

  // Lux Trading Firm Reviews - Premium Experience
  {
    id: 'lux-review-1',
    firmId: 'lux-trading-firm',
    userName: 'Alexander Novak',
    userAvatar: '/avatars/alexander-novak.jpg',
    rating: 5,
    title: 'Premium prop firm experience',
    content: 'Lux Trading Firm lives up to their name with a premium trading experience. The 2-phase evaluation is challenging but fair, focusing on consistency and risk management. What impressed me most is their trader support - weekly coaching calls and detailed performance analysis. Passed evaluation in 7 weeks and the funded account conditions are excellent. 80% profit split with potential to increase. Payouts processed within 48 hours consistently. Platform choice of MT4/MT5/cTrader covers all bases. Great for traders who value premium support.',
    date: '2024-09-29',
    verified: true,
    helpful: 118,
    userLocation: 'Prague, Czech Republic',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 23000,
    payoutReceived: true
  },
  {
    id: 'lux-review-2',
    firmId: 'lux-trading-firm',
    userName: 'Victoria Sterling',
    userAvatar: '/avatars/victoria-sterling.jpg',
    rating: 5,
    title: 'Excellent education and mentorship',
    content: 'Beyond just capital, Lux provides exceptional trader education. Their mentorship program helped refine my strategy significantly. The evaluation process teaches proper risk management - I failed first attempt but learned invaluable lessons. Second attempt passed easily. The funded account rules are clear with no hidden surprises. Trading conditions are competitive with good spreads. Support team responds within hours. Scaling plan is transparent and achievable. Four months funded with consistent profits. Highly recommend.',
    date: '2024-10-06',
    verified: true,
    helpful: 102,
    userLocation: 'Vienna, Austria',
    tradingExperience: '5 years',
    accountSize: '$150,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'lux-review-3',
    firmId: 'lux-trading-firm',
    userName: 'Michael Roth',
    userAvatar: '/avatars/michael-roth.jpg',
    rating: 4,
    title: 'Quality over quantity approach',
    content: 'Lux Trading Firm focuses on quality traders rather than mass enrollment. The evaluation is thorough and requires discipline. I appreciate their detailed feedback during the challenge phase - helps you improve. Once funded, the experience is professional. Payouts are reliable and support is excellent. The only minor issue is slightly higher entry cost than competitors, but the premium service justifies it. Good choice for serious traders who want ongoing support and education.',
    date: '2024-08-23',
    verified: true,
    helpful: 76,
    userLocation: 'Zurich, Switzerland',
    tradingExperience: '8 years',
    accountSize: '$100,000',
    profitMade: 18500,
    payoutReceived: true
  },

  // MyFlashFunding Reviews - Fast Track Funding
  {
    id: 'myflash-review-1',
    firmId: 'my-flash-funding',
    userName: 'Carlos Mendoza',
    userAvatar: '/avatars/carlos-mendoza.jpg',
    rating: 5,
    title: 'Lightning fast evaluation process',
    content: 'MyFlashFunding lives up to their name - passed their evaluation in just 8 days! The profit targets are reasonable and the drawdown rules are fair. What I love is the flexibility - trade forex, indices, commodities, or crypto. Platform choice includes MT4, MT5, and cTrader. The 80% profit split increases to 90% after consistency. Payouts are processed bi-weekly like clockwork. Customer support via Discord is incredibly responsive. Scaling plan is aggressive in the best way. Perfect for traders who want quick access to capital.',
    date: '2024-10-04',
    verified: true,
    helpful: 143,
    userLocation: 'Miami, USA',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'myflash-review-2',
    firmId: 'my-flash-funding',
    userName: 'Sophie Laurent',
    userAvatar: '/avatars/sophie-laurent.jpg',
    rating: 5,
    title: 'Best for crypto traders',
    content: 'As a primarily crypto trader, MyFlashFunding is perfect. They allow Bitcoin, Ethereum, and other crypto CFD trading with generous leverage. The evaluation was straightforward - no complicated rules or hidden requirements. Passed in 12 days trading BTC and ETH. Support team understands crypto markets well. Payouts arrive within 2-3 days of request. The profit split increasing to 90% is excellent motivation. Been funded 5 months and scaled to $200K account. Highly recommend for crypto-focused traders.',
    date: '2024-09-17',
    verified: true,
    helpful: 116,
    userLocation: 'Paris, France',
    tradingExperience: '5 years',
    accountSize: '$200,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: 'myflash-review-3',
    firmId: 'my-flash-funding',
    userName: 'Ahmed Al-Rashid',
    userAvatar: '/avatars/ahmed-alrashid.jpg',
    rating: 4,
    title: 'Fast and flexible',
    content: 'MyFlashFunding offers great flexibility in trading instruments and evaluation style. The flash challenge option is perfect for experienced traders. Passed in 10 days with consistent daily profits. Trading conditions are solid with competitive spreads. Payouts have been reliable - received three so far. The only reason for 4 stars is occasional platform latency during high volatility, but it\'s rare. Overall, excellent choice for traders who want fast funding with flexible instrument choices.',
    date: '2024-08-30',
    verified: true,
    helpful: 82,
    userLocation: 'Dubai, UAE',
    tradingExperience: '7 years',
    accountSize: '$150,000',
    profitMade: 26000,
    payoutReceived: true
  },

  // Funding Pips Reviews - UK Excellence
  {
    id: 'fundingpips-review-1',
    firmId: 'funding-pips',
    userName: 'Oliver Mitchell',
    userAvatar: '/avatars/oliver-mitchell.jpg',
    rating: 5,
    title: 'UK firm with excellent service',
    content: 'Funding Pips is a professional UK-based firm with outstanding service. Their 2-step evaluation is clearly structured with achievable targets. I trade primarily GBP pairs and indices, and execution is consistently good. Passed both phases in 6 weeks. The 80% profit split is competitive, and they offer fee refunds on first payout. Customer support is responsive and actually understands trading. Payouts processed monthly without delays. Scaling plan is straightforward. Been funded 8 months with steady growth. Excellent choice for UK and European traders.',
    date: '2024-09-23',
    verified: true,
    helpful: 109,
    userLocation: 'London, UK',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },
  {
    id: 'fundingpips-review-2',
    firmId: 'funding-pips',
    userName: 'Isabella Garcia',
    userAvatar: '/avatars/isabella-garcia.jpg',
    rating: 5,
    title: 'Transparent and trader-friendly',
    content: 'What I appreciate most about Funding Pips is their transparency. All rules are clearly stated, no hidden conditions. The evaluation process focuses on consistency rather than aggressive profits. I failed my first attempt and their support team provided helpful feedback. Passed second attempt and have been funded for 5 months. Trading conditions are excellent with tight spreads on major pairs. Payouts arrive on schedule. The community Discord is helpful with experienced traders sharing insights. Highly recommend.',
    date: '2024-10-02',
    verified: true,
    helpful: 95,
    userLocation: 'Barcelona, Spain',
    tradingExperience: '5 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },
  {
    id: 'fundingpips-review-3',
    firmId: 'funding-pips',
    userName: 'William Brooks',
    userAvatar: '/avatars/william-brooks.jpg',
    rating: 4,
    title: 'Solid UK-based option',
    content: 'Funding Pips provides a reliable prop trading experience. The evaluation is fair with reasonable profit targets and drawdown limits. Passed in 7 weeks trading EUR/USD and Gold. Once funded, rules are clear and support is helpful. Payouts are monthly which is standard. Trading conditions are good though not the absolute tightest spreads. That said, execution is reliable which matters more. Good scaling options available. A trustworthy choice, especially for UK-based traders.',
    date: '2024-08-16',
    verified: true,
    helpful: 71,
    userLocation: 'Edinburgh, UK',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 19000,
    payoutReceived: true
  },

  // Tradeify Reviews - Modern Futures Trading
  {
    id: 'tradeify-review-1',
    firmId: 'tradeify',
    userName: 'Jake Morrison',
    userAvatar: '/avatars/jake-morrison.jpg',
    rating: 5,
    title: 'Best modern futures prop firm',
    content: 'Tradeify brings a fresh, modern approach to futures prop trading. Their evaluation process is straightforward with clear rules and no hidden requirements. I trade primarily ES and NQ micros, and the platform integration with all major futures brokers is seamless. Passed evaluation in 14 days with consistent small wins. The 90% profit split is excellent, and payouts are processed bi-weekly without delays. Customer support via Discord is responsive and knowledgeable. Scaling plan is transparent. Great for both new and experienced futures traders.',
    date: '2024-10-06',
    verified: true,
    helpful: 141,
    userLocation: 'Austin, USA',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 22000,
    payoutReceived: true
  },
  {
    id: 'tradeify-review-2',
    firmId: 'tradeify',
    userName: 'Rachel Green',
    userAvatar: '/avatars/rachel-green.jpg',
    rating: 5,
    title: 'Perfect for micro traders',
    content: 'As someone who trades micro E-mini futures, Tradeify is perfect. Their rules accommodate micro trading strategies beautifully. No time limits means I can trade my own pace. Evaluation took me 3 weeks trading carefully. Once funded, everything has been smooth. Platform options include all the major futures platforms. Payouts arrive exactly when promised. Support team actually trades futures and understands the challenges. Four months in and scaling steadily. Highly recommend for futures traders.',
    date: '2024-09-19',
    verified: true,
    helpful: 107,
    userLocation: 'Phoenix, USA',
    tradingExperience: '4 years',
    accountSize: '$75,000',
    profitMade: 14000,
    payoutReceived: true
  },
  {
    id: 'tradeify-review-3',
    firmId: 'tradeify',
    userName: 'Mark Patterson',
    userAvatar: '/avatars/mark-patterson.jpg',
    rating: 4,
    title: 'Solid futures option',
    content: 'Tradeify offers a good futures trading experience. Evaluation is fair with reasonable profit targets. Passed in 18 days trading crude oil and gold futures. Trading conditions are competitive and execution is reliable. Payouts processed as promised. The only minor issue is their platform had brief downtime once in 5 months, but support communicated well. Overall, a solid choice for futures traders wanting straightforward terms and good profit splits.',
    date: '2024-08-24',
    verified: true,
    helpful: 73,
    userLocation: 'Tampa, USA',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 17500,
    payoutReceived: true
  },

  // Leeloo Trading Reviews - European Excellence
  {
    id: 'leeloo-review-1',
    firmId: 'leeloo-trading',
    userName: 'Pierre Dubois',
    userAvatar: '/avatars/pierre-dubois.jpg',
    rating: 5,
    title: 'European firm with global reach',
    content: 'Leeloo Trading is an excellent European-based prop firm with professional operations. Their evaluation process is well-structured with clear phases and achievable targets. I trade primarily EUR pairs and European indices, and execution is consistently excellent. Passed their 2-phase challenge in 6 weeks. The 80% profit split is competitive, and they offer multiple platform choices. Customer support is available 24/5 and very responsive. Payouts processed bi-weekly without issues. Scaling plan is transparent and fair. Highly recommend for European traders.',
    date: '2024-10-02',
    verified: true,
    helpful: 123,
    userLocation: 'Paris, France',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'leeloo-review-2',
    firmId: 'leeloo-trading',
    userName: 'Sofia Petersen',
    userAvatar: '/avatars/sofia-petersen.jpg',
    rating: 5,
    title: 'Professional and transparent',
    content: 'What I appreciate most about Leeloo is their transparency. All rules are clearly explained with no hidden conditions. The evaluation focuses on consistency and proper risk management. I trade multiple instruments including forex, indices, and commodities. Platform integration with MT4/MT5 is seamless. Passed evaluation in 7 weeks and have been funded for 5 months. Payouts always arrive on schedule. Support team is professional and helpful. Great choice for traders who value clear communication and fair terms.',
    date: '2024-09-15',
    verified: true,
    helpful: 98,
    userLocation: 'Copenhagen, Denmark',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 28000,
    payoutReceived: true
  },
  {
    id: 'leeloo-review-3',
    firmId: 'leeloo-trading',
    userName: 'Marco Rossi',
    userAvatar: '/avatars/marco-rossi.jpg',
    rating: 4,
    title: 'Solid European option',
    content: 'Leeloo Trading provides a reliable prop trading experience. Their evaluation is challenging but fair, requiring proper risk management. Passed in my second attempt after learning from the first. Trading conditions are good with competitive spreads on major pairs. Support team is helpful and professional. Payouts come bi-weekly as promised. The scaling plan could be more aggressive, but it\'s steady and achievable. Good choice for European traders wanting a trustworthy firm.',
    date: '2024-08-20',
    verified: true,
    helpful: 71,
    userLocation: 'Rome, Italy',
    tradingExperience: '5 years',
    accountSize: '$75,000',
    profitMade: 15000,
    payoutReceived: true
  },

  // Finotive Funding Reviews - Multi-Asset Innovator
  {
    id: 'finotive-review-1',
    firmId: 'finotive-funding',
    userName: 'David Chen',
    userAvatar: '/avatars/david-chen-fin.jpg',
    rating: 5,
    title: 'Comprehensive multi-asset platform',
    content: 'Finotive Funding offers one of the most comprehensive multi-asset platforms I\'ve experienced. Trade forex, futures, indices, commodities - all with one firm. Their evaluation process is well-designed with clear objectives. I trade a diversified portfolio across asset classes, and the platform handles everything smoothly. Passed evaluation in 5 weeks. The 80% profit split increases to 90%, which is great motivation. Payouts processed bi-weekly consistently. Support team is knowledgeable across all asset classes. Excellent for traders who want variety.',
    date: '2024-09-27',
    verified: true,
    helpful: 136,
    userLocation: 'Hong Kong',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 32000,
    payoutReceived: true
  },
  {
    id: 'finotive-review-2',
    firmId: 'finotive-funding',
    userName: 'Jessica Martinez',
    userAvatar: '/avatars/jessica-martinez-fin.jpg',
    rating: 5,
    title: 'Flexibility in trading instruments',
    content: 'What sets Finotive apart is their flexibility. I can trade forex in the morning and switch to futures in the afternoon - all within the same account. The evaluation is straightforward with reasonable targets. Passed in 6 weeks trading mix of EUR/USD, Gold, and ES futures. Platform integration is excellent with multiple choices. Payouts arrive within 48 hours of request. Educational resources are surprisingly good. Been funded 7 months and very satisfied. Great for multi-asset traders.',
    date: '2024-10-04',
    verified: true,
    helpful: 114,
    userLocation: 'Madrid, Spain',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 21000,
    payoutReceived: true
  },
  {
    id: 'finotive-review-3',
    firmId: 'finotive-funding',
    userName: 'Robert Williams',
    userAvatar: '/avatars/robert-williams-fin.jpg',
    rating: 4,
    title: 'Great variety, slight learning curve',
    content: 'Finotive offers impressive variety in tradable instruments. The evaluation process is fair, though understanding the rules for different asset classes took time. Passed in 7 weeks once I got comfortable with their system. Trading conditions are competitive across all asset classes. Payouts processed as promised. Support is helpful but can be slow during peak hours. Overall, excellent choice if you want multi-asset flexibility. Just expect a bit of learning curve initially.',
    date: '2024-08-29',
    verified: true,
    helpful: 79,
    userLocation: 'Toronto, Canada',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 19000,
    payoutReceived: true
  },

  // TopTier Trader Reviews - Premium Futures
  {
    id: 'toptier-review-1',
    firmId: 'toptier-trader',
    userName: 'Brandon Scott',
    userAvatar: '/avatars/brandon-scott.jpg',
    rating: 5,
    title: 'Top-tier futures trading experience',
    content: 'TopTier Trader delivers exactly what their name promises - a top-tier futures trading experience. Their evaluation is challenging but teaches excellent risk management. I trade ES, NQ, and YM futures with consistent execution quality. Passed evaluation in 3 weeks with disciplined trading. The 80% profit split with increases to 90% is competitive. Payouts processed bi-weekly without delays. Platform support includes all major futures brokers. Customer support is outstanding - quick responses and knowledgeable staff. Six months in and scaled to $200K. Highly recommend.',
    date: '2024-10-01',
    verified: true,
    helpful: 129,
    userLocation: 'Chicago, USA',
    tradingExperience: '9 years',
    accountSize: '$200,000',
    profitMade: 38000,
    payoutReceived: true
  },
  {
    id: 'toptier-review-2',
    firmId: 'toptier-trader',
    userName: 'Amanda Brooks',
    userAvatar: '/avatars/amanda-brooks.jpg',
    rating: 5,
    title: 'Professional futures funding',
    content: 'TopTier Trader is perfect for serious futures traders. The evaluation process focuses on consistency and proper risk management - exactly what sustainable trading requires. I trade crude oil and gold futures primarily. Passed evaluation in 25 days with steady gains. Once funded, trading conditions are excellent with tight spreads and fast execution. Payouts arrive exactly when promised. Support team truly understands futures markets. Scaling is straightforward based on performance. Four months funded with consistent profits.',
    date: '2024-09-13',
    verified: true,
    helpful: 103,
    userLocation: 'Denver, USA',
    tradingExperience: '7 years',
    accountSize: '$150,000',
    profitMade: 27000,
    payoutReceived: true
  },
  {
    id: 'toptier-review-3',
    firmId: 'toptier-trader',
    userName: 'Kevin Murphy',
    userAvatar: '/avatars/kevin-murphy.jpg',
    rating: 4,
    title: 'Solid futures option',
    content: 'TopTier Trader provides a solid futures trading experience. Evaluation is fair with realistic profit targets. Passed in 19 days trading ES micros. Trading conditions are good with reliable execution. Payouts processed bi-weekly as stated. Support is helpful though not always immediate. The profit split progression is motivating. My only minor critique is the initial fee is slightly higher than some competitors, but the quality justifies it. Good choice for committed futures traders.',
    date: '2024-08-25',
    verified: true,
    helpful: 76,
    userLocation: 'Seattle, USA',
    tradingExperience: '5 years',
    accountSize: '$100,000',
    profitMade: 18000,
    payoutReceived: true
  },

  // Blueberry Funded Reviews - Innovative Approach
  {
    id: 'blueberry-review-1',
    firmId: 'blueberry-funded',
    userName: 'Emily Watson',
    userAvatar: '/avatars/emily-watson-bb.jpg',
    rating: 5,
    title: 'Innovative funding model',
    content: 'Blueberry Funded brings innovation to prop trading with their unique evaluation structure. They offer multiple pathways to funding - choose based on your trading style and experience level. I selected their standard 2-phase challenge and found it fair and achievable. Passed in 6 weeks trading EUR/USD and GBP/JPY. The 80% profit split is competitive, and payouts are processed weekly which is fantastic. Platform integration with MT4/MT5 is flawless. Support team is responsive and helpful. Scaling is aggressive for consistent traders. Highly recommend.',
    date: '2024-09-30',
    verified: true,
    helpful: 147,
    userLocation: 'Sydney, Australia',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 25000,
    payoutReceived: true
  },
  {
    id: 'blueberry-review-2',
    firmId: 'blueberry-funded',
    userName: 'Lucas Silva',
    userAvatar: '/avatars/lucas-silva.jpg',
    rating: 5,
    title: 'Weekly payouts are excellent',
    content: 'The weekly payout option at Blueberry Funded is one of the best features. As a professional trader, weekly cash flow makes a huge difference. Their evaluation process is straightforward with clear rules. Passed in 4 weeks with consistent daily profits. Trading conditions are excellent with competitive spreads. EA trading is fully allowed which works perfect for my algorithmic strategy. Support is available 24/7 and very knowledgeable. Been funded 6 months with steady scaling. Great firm.',
    date: '2024-10-07',
    verified: true,
    helpful: 126,
    userLocation: 'São Paulo, Brazil',
    tradingExperience: '7 years',
    accountSize: '$150,000',
    profitMade: 31000,
    payoutReceived: true
  },
  {
    id: 'blueberry-review-3',
    firmId: 'blueberry-funded',
    userName: 'Sarah Mitchell',
    userAvatar: '/avatars/sarah-mitchell-bb.jpg',
    rating: 4,
    title: 'Good innovation, minor issues',
    content: 'Blueberry Funded offers interesting innovations in prop funding. The multiple evaluation pathways give good flexibility. Passed their standard challenge in 5 weeks. Trading conditions are solid and payouts have been reliable. Support is generally helpful. Had one issue with payout delay (resolved within 48 hours), hence 4 stars instead of 5. That said, the overall experience has been positive. Their scaling plan is attractive for consistent traders. Worth considering.',
    date: '2024-08-22',
    verified: true,
    helpful: 68,
    userLocation: 'Melbourne, Australia',
    tradingExperience: '5 years',
    accountSize: '$75,000',
    profitMade: 14500,
    payoutReceived: true
  },

  // Seacrest Funded Reviews - Multi-Asset Professional
  {
    id: 'seacrest-review-1',
    firmId: 'seacrest-funded',
    userName: 'Christopher Lee',
    userAvatar: '/avatars/christopher-lee-sc.jpg',
    rating: 5,
    title: 'Professional multi-asset firm',
    content: 'Seacrest Funded is a professional operation offering forex, futures, and crypto trading. Their evaluation process is well-structured focusing on consistency and risk management. I trade a mix of forex pairs and crypto CFDs, and the platform handles both seamlessly. Passed evaluation in 7 weeks. The 80% profit split is fair, and payouts are processed bi-weekly consistently. Customer support is excellent - responsive and knowledgeable. Platform choices include MT4, MT5, and proprietary options. Scaling plan is transparent. Excellent for diversified traders.',
    date: '2024-09-25',
    verified: true,
    helpful: 132,
    userLocation: 'San Francisco, USA',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 33000,
    payoutReceived: true
  },
  {
    id: 'seacrest-review-2',
    firmId: 'seacrest-funded',
    userName: 'Maria Gonzalez',
    userAvatar: '/avatars/maria-gonzalez-sc.jpg',
    rating: 5,
    title: 'Excellent for crypto and forex mix',
    content: 'As someone who trades both crypto and forex, Seacrest Funded is perfect. Their platform supports both asset classes with competitive conditions. The evaluation is challenging but fair. Passed in 6 weeks trading Bitcoin CFDs and EUR/USD. Payouts arrive within 48 hours of request. Support team understands both crypto and forex markets well. Been funded 5 months and scaled account size already. Educational resources are helpful. Highly recommend for traders wanting multi-asset flexibility.',
    date: '2024-10-03',
    verified: true,
    helpful: 109,
    userLocation: 'Miami, USA',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 23000,
    payoutReceived: true
  },
  {
    id: 'seacrest-review-3',
    firmId: 'seacrest-funded',
    userName: 'James Taylor',
    userAvatar: '/avatars/james-taylor-sc.jpg',
    rating: 4,
    title: 'Solid multi-asset option',
    content: 'Seacrest Funded provides good multi-asset trading opportunities. Evaluation process is fair with achievable targets across different instruments. Passed in 8 weeks trading futures and forex. Trading conditions are competitive. Payouts processed as promised, though bi-weekly frequency is standard. Support is helpful but response times can vary. The profit split progression is motivating. Good choice for traders wanting access to multiple asset classes without restrictive rules.',
    date: '2024-08-18',
    verified: true,
    helpful: 74,
    userLocation: 'Los Angeles, USA',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 19500,
    payoutReceived: true
  },

  // Top One Futures Reviews - Futures Specialist
  {
    id: 'toponefutures-review-1',
    firmId: 'top-one-futures',
    userName: 'Matthew Rivera',
    userAvatar: '/avatars/matthew-rivera.jpg',
    rating: 5,
    title: 'Excellent futures-focused firm',
    content: 'Top One Futures specializes in futures trading and it shows in their professional execution and support. The evaluation process is clear with reasonable profit targets and drawdown limits. I trade ES and NQ exclusively, and execution quality is consistently excellent. Passed evaluation in 16 days with steady gains. The 80% profit split increases to 90% which is great. Payouts processed weekly - fantastic for cash flow. Support team truly understands futures markets. Scaling is straightforward. Seven months funded with consistent growth. Highly recommend for futures traders.',
    date: '2024-10-05',
    verified: true,
    helpful: 138,
    userLocation: 'Dallas, USA',
    tradingExperience: '9 years',
    accountSize: '$150,000',
    profitMade: 34000,
    payoutReceived: true
  },
  {
    id: 'toponefutures-review-2',
    firmId: 'top-one-futures',
    userName: 'Jennifer Adams',
    userAvatar: '/avatars/jennifer-adams.jpg',
    rating: 5,
    title: 'Best for micro futures traders',
    content: 'Top One Futures is perfect for micro futures trading strategies. Their rules accommodate smaller position sizes beautifully. No time pressure means I can trade my system properly. Evaluation took 3 weeks trading ES and NQ micros. Once funded, everything has been smooth. Platform integration with all major futures brokers is seamless. Payouts arrive exactly when promised. Educational resources on futures trading are valuable. Four months in and scaled to $200K account. Excellent firm.',
    date: '2024-09-16',
    verified: true,
    helpful: 115,
    userLocation: 'Phoenix, USA',
    tradingExperience: '6 years',
    accountSize: '$200,000',
    profitMade: 39000,
    payoutReceived: true
  },
  {
    id: 'toponefutures-review-3',
    firmId: 'top-one-futures',
    userName: 'Ryan Cooper',
    userAvatar: '/avatars/ryan-cooper.jpg',
    rating: 4,
    title: 'Solid futures trading option',
    content: 'Top One Futures provides a reliable futures trading experience. Evaluation is fair with realistic targets. Passed in 20 days trading crude oil and gold futures. Trading conditions are good with competitive commissions. Payouts processed weekly as stated. Support is helpful though not always immediate during US trading hours. Overall, a solid choice for futures traders wanting straightforward terms and good profit splits. The scaling plan is achievable.',
    date: '2024-08-27',
    verified: true,
    helpful: 81,
    userLocation: 'Houston, USA',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 21000,
    payoutReceived: true
  },

  // Bulenox Reviews - European Innovation
  {
    id: 'bulenox-review-1',
    firmId: 'bulenox',
    userName: 'Alexander Volkov',
    userAvatar: '/avatars/alexander-volkov-bul.jpg',
    rating: 5,
    title: 'European innovation in prop funding',
    content: 'Bulenox brings fresh innovation to European prop trading. Their evaluation model is unique with flexible phases and achievable targets. I trade primarily European markets - DAX, FTSE, EUR pairs - and execution is consistently excellent. Passed evaluation in 5 weeks. The 85% profit split is among the best I\'ve seen. Payouts processed bi-weekly without delays. Platform choices include MT4, MT5, and cTrader. Customer support is responsive 24/5. Scaling is aggressive for consistent traders. Been funded 6 months and very impressed. Highly recommend.',
    date: '2024-09-28',
    verified: true,
    helpful: 144,
    userLocation: 'Warsaw, Poland',
    tradingExperience: '8 years',
    accountSize: '$150,000',
    profitMade: 35000,
    payoutReceived: true
  },
  {
    id: 'bulenox-review-2',
    firmId: 'bulenox',
    userName: 'Elena Petrova',
    userAvatar: '/avatars/elena-petrova.jpg',
    rating: 5,
    title: 'Excellent European option',
    content: 'As a European trader, Bulenox is perfect for trading European market hours. Their evaluation is straightforward with clear rules. Passed in 6 weeks trading EUR/GBP and DAX. Trading conditions are excellent with tight spreads on European pairs. Payouts arrive within 48 hours consistently. Support team is professional and helpful. The 85% profit split is very competitive. EA trading allowed which suits my strategy. Five months funded with steady scaling. Great European firm.',
    date: '2024-10-04',
    verified: true,
    helpful: 118,
    userLocation: 'Prague, Czech Republic',
    tradingExperience: '6 years',
    accountSize: '$100,000',
    profitMade: 24000,
    payoutReceived: true
  },
  {
    id: 'bulenox-review-3',
    firmId: 'bulenox',
    userName: 'Marcus Weber',
    userAvatar: '/avatars/marcus-weber.jpg',
    rating: 4,
    title: 'Innovative but still growing',
    content: 'Bulenox offers interesting innovations in prop funding. The evaluation model is flexible and fair. Passed in 7 weeks trading multiple instruments. Trading conditions are competitive and support is helpful. Had one minor technical issue that was resolved quickly. The 85% profit split is excellent. As a newer firm, they\'re still building track record, but all signs are positive. Good choice for European traders wanting innovation.',
    date: '2024-08-21',
    verified: true,
    helpful: 72,
    userLocation: 'Munich, Germany',
    tradingExperience: '7 years',
    accountSize: '$75,000',
    profitMade: 16000,
    payoutReceived: true
  },

  // Funded Trading Plus Reviews - Premium Features
  {
    id: 'fundedplus-review-1',
    firmId: 'funded-trading-plus',
    userName: 'Daniel Park',
    userAvatar: '/avatars/daniel-park.jpg',
    rating: 5,
    title: 'Exceptional profit split and conditions',
    content: 'Funded Trading Plus offers some of the best terms in the industry. The 90% profit split from day one is incredible, and it increases to 95% with consistency. Evaluation is challenging but fair - took me two attempts but the learning was valuable. Once funded, trading conditions are excellent with MT4/MT5/cTrader options. Payouts processed weekly which is fantastic for cash flow. Customer support is top-tier with 24/5 availability. Scaling is aggressive - doubled my account in 4 months. Highly recommend for serious traders.',
    date: '2024-10-05',
    verified: true,
    helpful: 152,
    userLocation: 'Seoul, South Korea',
    tradingExperience: '8 years',
    accountSize: '$200,000',
    profitMade: 44000,
    payoutReceived: true
  },
  {
    id: 'fundedplus-review-2',
    firmId: 'funded-trading-plus',
    userName: 'Laura Martinez',
    userAvatar: '/avatars/laura-martinez.jpg',
    rating: 5,
    title: 'Weekly payouts are game-changing',
    content: 'The weekly payout option at Funded Trading Plus is a game-changer for professional traders. I can manage my cash flow much better than with monthly payouts. The evaluation process is straightforward with clear rules. Passed in 5 weeks trading indices and commodities. The 90% profit split is among the best available. Platform integration is seamless, and execution is fast. Support team is professional and responsive. Educational resources are surprisingly comprehensive. Six months in and very satisfied.',
    date: '2024-09-18',
    verified: true,
    helpful: 128,
    userLocation: 'Buenos Aires, Argentina',
    tradingExperience: '6 years',
    accountSize: '$150,000',
    profitMade: 31000,
    payoutReceived: true
  },
  {
    id: 'fundedplus-review-3',
    firmId: 'funded-trading-plus',
    userName: 'Thomas Anderson',
    userAvatar: '/avatars/thomas-anderson.jpg',
    rating: 4,
    title: 'Premium service at fair price',
    content: 'Funded Trading Plus delivers premium service. The evaluation cost is slightly higher than average, but the 90% profit split and weekly payouts justify it. Passed evaluation in 6 weeks with disciplined trading. Once funded, everything operates smoothly. Trading conditions are competitive and support is excellent. The scaling plan is clear and achievable. My only minor critique is the consistency rule requires careful planning, but it promotes good habits. Overall, excellent choice for committed traders.',
    date: '2024-08-26',
    verified: true,
    helpful: 84,
    userLocation: 'Oslo, Norway',
    tradingExperience: '7 years',
    accountSize: '$100,000',
    profitMade: 21500,
    payoutReceived: true
  }
];

// Helper function to get reviews by firm ID
export const getReviewsByFirmId = (firmId: string): UserReview[] => {
  return userReviews.filter(review => review.firmId === firmId);
};

// Helper function to get review statistics
export const getReviewStats = (firmId: string) => {
  const reviews = getReviewsByFirmId(firmId);
  const totalReviews = reviews.length;
  const averageRating = totalReviews > 0 ? reviews.reduce((sum, review) => sum + review.rating, 0) / totalReviews : 0;
  const ratingDistribution = {
    5: reviews.filter(r => r.rating === 5).length,
    4: reviews.filter(r => r.rating === 4).length,
    3: reviews.filter(r => r.rating === 3).length,
    2: reviews.filter(r => r.rating === 2).length,
    1: reviews.filter(r => r.rating === 1).length
  };
  
  return {
    totalReviews,
    averageRating: Math.round(averageRating * 10) / 10,
    ratingDistribution
  };
};
