import type { TradingTool } from '../types.ts';

export const tradingTools: TradingTool[] = [
  {
    id: 'edgeful',
    name: 'Edgeful',
    shortName: 'Edgeful',
    logoUrl: '/logos/edgeful.png',
    officialWebsite: 'https://edgeful.com',
    tagline: 'Data-Driven Trading Platform',
    shortDescription: 'Comprehensive trading analysis platform with over 100 customizable reports, real-time data alerts, and automated trading algorithms.',
    rating: 4.5,
    reviewCount: 83,
    affiliateUrl: 'https://edgeful.com?ref=FPG',
    fpgAffiliateCode: 'FPG',
    categories: ['Technical Analysis', 'News & Sentiment', 'Algorithmic Trading'],
    targetMarkets: ['Stocks', 'Futures', 'Crypto', 'Forex'],
    pricing: {
      free: false,
      freeTrial: true,
      monthlyPrice: 49,
      yearlyPrice: 468,
      currency: 'USD'
    },
    features: {
      realTimeData: true,
      alerts: true,
      backtesting: false,
      paperTrading: false,
      mobileApp: false,
      apiAccess: true,
      customIndicators: true,
      socialTrading: false,
      newsFeed: true,
      optionsFlow: false,
      darkPoolData: false,
      institutionalData: false,
      sentimentAnalysis: false,
      automatedTrading: true
    },
    dataProviders: ['Multiple Exchanges', 'Market Data Vendors'],
    supportedPlatforms: ['Web', 'TradingView', 'API'],
    dataLatency: '< 500ms',
    updateFrequency: 'Real-time',
    overview: 'Edgeful is a data-driven trading platform that simplifies market analysis by providing over 100 customizable reports on price action, trends, and strategies. It offers real-time data alerts for high-probability trades, custom TradingView indicators, and automated trading algorithms. The platform focuses on gap fills, opening range breakouts, and prior day range extensions to help traders make data-driven decisions.',
    pros: [
      '100+ customizable reports',
      'Real-time data alerts',
      '30+ custom TradingView indicators',
      'Automated trading algorithms',
      'Comprehensive market screener',
      'Mentorship and community support',
      'Affordable pricing at $49/month'
    ],
    cons: [
      'No mobile app',
      'Limited to specific market patterns',
      'Static data approach',
      'No options flow or dark pool data',
      'Requires TradingView for indicators'
    ],
    bestFor: [
      'Data-driven traders',
      'Gap and breakout traders',
      'Technical analysis enthusiasts',
      'Traders seeking mentorship',
      'Multi-asset traders'
    ],
    deal: {
      description: 'Save 20% with annual subscription ($39/month)',
      isTopDeal: true
    }
  },
  {
    id: 'lux-algo',
    name: 'Lux Algo',
    shortName: 'Lux Algo',
    logoUrl: 'https://logo.clearbit.com/luxalgo.com',
    officialWebsite: 'https://luxalgo.com',
    tagline: 'Advanced TradingView Indicators & Signals',
    shortDescription: 'Premium TradingView indicators with real-time buy/sell signals, trend detection, and comprehensive oscillator tools.',
    rating: 4.5,
    reviewCount: 268,
    affiliateUrl: 'https://luxalgo.com?ref=FPG',
    fpgAffiliateCode: 'FPG',
    categories: ['Technical Analysis', 'Social Trading'],
    targetMarkets: ['Stocks', 'Crypto', 'Forex'],
    pricing: {
      free: false,
      freeTrial: true,
      monthlyPrice: 68,
      yearlyPrice: 490,
      currency: 'USD'
    },
    features: {
      realTimeData: true,
      alerts: true,
      backtesting: false,
      paperTrading: false,
      mobileApp: false,
      apiAccess: false,
      customIndicators: true,
      socialTrading: true,
      newsFeed: false,
      optionsFlow: false,
      darkPoolData: false,
      institutionalData: true,
      sentimentAnalysis: false,
      automatedTrading: false
    },
    dataProviders: ['TradingView', 'Multiple Exchanges'],
    supportedPlatforms: ['TradingView'],
    dataLatency: '< 1 second',
    updateFrequency: 'Real-time',
    overview: 'Lux Algo provides premium TradingView indicators including the flagship Lux Algo Premium Indicator with real-time buy/sell signals, Lux Oscillator Premium with multiple oscillator components (Legacy, Classic, Advanced, Normalized), and Lux Statistics Premium with pivot oscillator, volatility measurement, and institutional activity tracking. Features a vibrant Discord community with over 50,000 members.',
    pros: [
      'Real-time buy/sell signals',
      'Multiple oscillator tools',
      'Large Discord community (50k+ members)',
      'Institutional activity tracking',
      'TradingView integration',
      'Free courses and strategy videos',
      'Weekly live sessions'
    ],
    cons: [
      'TradingView only (no standalone platform)',
      'No verified live trading results',
      'Limited backtesting data',
      'No mobile app',
      'No API access'
    ],
    bestFor: [
      'TradingView users',
      'Technical analysis traders',
      'Community-focused traders',
      'Multi-market traders',
      'Traders seeking educational resources'
    ],
    deal: {
      description: 'Free trial available with full access',
      isTopDeal: false
    }
  },
  {
    id: 'true-algo',
    name: 'True Algo',
    shortName: 'True Algo',
    logoUrl: 'https://logo.clearbit.com/truealgo.com',
    officialWebsite: 'https://truealgo.com',
    tagline: 'Statistics-Backed Trading Signals & Live Coaching',
    shortDescription: 'Industry-leading non-repainting indicator with live coaching, community support, and comprehensive educational resources for mastering price action.',
    rating: 4.7,
    reviewCount: 500,
    affiliateUrl: 'https://truealgo.com?ref=FPG',
    fpgAffiliateCode: 'FPG',
    categories: ['Technical Analysis', 'Social Trading'],
    targetMarkets: ['Stocks', 'Crypto', 'Forex', 'Futures'],
    pricing: {
      free: false,
      freeTrial: true,
      monthlyPrice: 97,
      yearlyPrice: 970,
      currency: 'USD'
    },
    features: {
      realTimeData: true,
      alerts: true,
      backtesting: true,
      paperTrading: false,
      mobileApp: false,
      apiAccess: false,
      customIndicators: true,
      socialTrading: true,
      newsFeed: false,
      optionsFlow: false,
      darkPoolData: false,
      institutionalData: false,
      sentimentAnalysis: false,
      automatedTrading: false
    },
    dataProviders: ['Multiple Exchanges'],
    supportedPlatforms: ['Web', 'Desktop'],
    dataLatency: '< 1 second',
    updateFrequency: 'Real-time',
    overview: 'True Algo provides traders with precise entry points, average take profits, and real drawdown risks before entering trades. Features the industry-leading True Algo Indicator that operates across all time frames, automatically generating daily and weekly True Algo Reaction Boxes for mastering price action. Includes live coaching sessions with expert coaches demonstrating the indicator across multiple assets, a thriving community for strategy sharing, and a comprehensive learning platform with hundreds of hours of training videos and past livestreams.',
    pros: [
      'Non-repainting indicator with live-candle precision',
      'Daily and weekly reaction boxes across all timeframes',
      'Live coaching sessions with expert coaches',
      'Strong community support and collaboration',
      'Comprehensive educational resources (hundreds of hours)',
      'Statistics-backed signals with backtested metrics',
      'All time frame compatibility',
      'Proven track record (FTMO leaderboard success)',
      'Full transparency with exact entry points and take profits',
      'Solo & confluence setups with heads-up table',
      'Optimized for 15-minute and above timeframes'
    ],
    cons: [
      'No mobile app',
      'No API access',
      'Limited to technical analysis',
      'No automated trading',
      'Higher pricing',
      'Steep learning curve for beginners',
      'Requires active participation in community'
    ],
    bestFor: [
      'Price action traders',
      'Community-focused traders',
      'Traders seeking education and mentorship',
      'Multi-timeframe traders',
      'Funded traders',
      'Traders wanting statistics-backed signals',
      'Traders looking for live coaching support'
    ],
    deal: {
      description: 'Free trial available with full access to indicator and community',
      isTopDeal: false
    }
  },
  {
    id: 'unusual-whales',
    name: 'Unusual Whales',
    shortName: 'Unusual Whales',
    logoUrl: 'https://logo.clearbit.com/unusualwhales.com',
    officialWebsite: 'https://unusualwhales.com',
    tagline: 'Real-Time Options Flow & Dark Pool Analytics',
    shortDescription: 'Comprehensive financial data platform providing retail traders with real-time options flow, dark pool data, live charting, and institutional-level market insights.',
    rating: 4.3,
    reviewCount: 2500,
    affiliateUrl: 'https://unusualwhales.com?ref=FPG',
    fpgAffiliateCode: 'FPG',
    categories: ['Options Flow', 'News & Sentiment', 'Institutional Data', 'Technical Analysis'],
    targetMarkets: ['Stocks', 'Options', 'Crypto'],
    pricing: {
      free: true,
      freeTrial: false,
      monthlyPrice: 48,
      yearlyPrice: 528,
      currency: 'USD'
    },
    features: {
      realTimeData: true,
      alerts: true,
      backtesting: false,
      paperTrading: true,
      mobileApp: true,
      apiAccess: true,
      customIndicators: true,
      socialTrading: false,
      newsFeed: true,
      optionsFlow: true,
      darkPoolData: true,
      institutionalData: true,
      sentimentAnalysis: false,
      automatedTrading: false
    },
    dataProviders: ['U.S. Options Exchanges', 'Dark Pool Exchanges', 'News APIs', 'Crypto Exchanges'],
    supportedPlatforms: ['Web', 'Mobile', 'API'],
    dataLatency: '< 1 second',
    updateFrequency: 'Real-time',
    overview: 'Unusual Whales is a comprehensive financial data platform established in 2021, designed to provide retail traders with institutional-level tools and insights. Features real-time options flow tracking across all U.S. exchanges, dark pool and whale feed monitoring, live charting with technical indicators, options profit calculator, comprehensive trading journal, and live news feed. Includes exclusive partnership with Tastytrade for direct trading integration.',
    pros: [
      'Free tier available',
      'Real-time options flow across all U.S. exchanges',
      'Dark pool and whale feed monitoring',
      'Live charting with technical indicators',
      'Options profit calculator',
      'Comprehensive trading journal',
      'Mobile app for iOS and Android',
      'API access with annual plan',
      'Tastytrade integration for direct trading',
      'Affordable pricing starting at $20/month annually'
    ],
    cons: [
      'Steep learning curve',
      'Requires solid options trading knowledge',
      'Limited to U.S. markets primarily',
      'No automated trading capabilities',
      'No sentiment analysis features'
    ],
    bestFor: [
      'Options traders',
      'Retail traders seeking institutional data',
      'Dark pool data enthusiasts',
      'Technical analysis traders',
      'Traders using Tastytrade',
      'Mobile traders'
    ],
    deal: {
      description: 'Annual plan: $528/year (save $48 vs monthly)',
      isTopDeal: true
    }
  },
  {
    id: 'cheddar-flow',
    name: 'Cheddar Flow',
    shortName: 'Cheddar Flow',
    logoUrl: 'https://logo.clearbit.com/cheddarflow.com',
    officialWebsite: 'https://cheddarflow.com',
    tagline: 'Real-Time Options Order Flow & Dark Pool Analytics',
    shortDescription: 'Professional options order flow platform with real-time institutional trading insights, dark pool data, AI-powered alerts, and customizable dashboards.',
    rating: 4.6,
    reviewCount: 1200,
    affiliateUrl: 'https://cheddarflow.com?ref=FPG',
    fpgAffiliateCode: 'FPG',
    categories: ['Options Flow', 'Institutional Data', 'Dark Pool Data'],
    targetMarkets: ['Stocks', 'Options'],
    pricing: {
      free: false,
      freeTrial: true,
      monthlyPrice: 85,
      yearlyPrice: 891,
      currency: 'USD'
    },
    features: {
      realTimeData: true,
      alerts: true,
      backtesting: false,
      paperTrading: false,
      mobileApp: false,
      apiAccess: false,
      customIndicators: false,
      socialTrading: false,
      newsFeed: false,
      optionsFlow: true,
      darkPoolData: true,
      institutionalData: true,
      sentimentAnalysis: false,
      automatedTrading: false
    },
    dataProviders: ['Options Exchanges', 'Dark Pool Exchanges', 'Institutional Data Sources'],
    supportedPlatforms: ['Web'],
    dataLatency: '< 100ms',
    updateFrequency: 'Real-time',
    overview: 'Cheddar Flow is a real-time options order flow tracking platform founded in 2018, designed to provide retail traders with institutional-level insights. Features real-time options order flow monitoring, dark pool order tracking, AI-powered alerts for unusual market activities, customizable dashboards, and pre/post-market data analysis. Offers multiple subscription tiers with advanced features like dark pool data and AI alerts for professional traders.',
    pros: [
      'Real-time options order flow tracking',
      'Dark pool data access',
      'AI-powered alerts for unusual activities',
      'Customizable dashboard interface',
      'Pre/post-market data analysis',
      'Clean, modern, intuitive interface',
      'High-speed, lag-free data delivery',
      'Advanced filtering capabilities',
      'Historical data analysis (1 year)',
      'Professional-grade institutional insights'
    ],
    cons: [
      'Higher pricing ($85-99/month)',
      'No mobile app available',
      'No API access',
      'Limited to options and stocks',
      'No free trial for Professional plans',
      'Strict non-refundable payment policy',
      'No automated trading capabilities',
      'Steep learning curve for beginners'
    ],
    bestFor: [
      'Professional options traders',
      'Institutional data seekers',
      'Dark pool data enthusiasts',
      'Day traders and swing traders',
      'Market analysis specialists',
      'Traders requiring real-time insights',
      'Experienced order flow analysts'
    ],
    deal: {
      description: 'Pro Annual Plan: $75/month (save $24/month vs Professional)',
      isTopDeal: true
    }
  },
  {
    id: 'atas',
    name: 'ATAS',
    shortName: 'ATAS',
    logoUrl: 'https://logo.clearbit.com/atas.net',
    officialWebsite: 'https://atas.net',
    tagline: 'Professional Volume & Order Flow Analysis Platform',
    shortDescription: 'Advanced trading platform specializing in volume profile analysis, order flow visualization, and market microstructure for futures, forex, and crypto markets.',
    rating: 4.7,
    reviewCount: 1800,
    affiliateUrl: 'https://atas.net?ref=FPG',
    fpgAffiliateCode: 'FPG',
    categories: ['Technical Analysis', 'Market Analysis'],
    targetMarkets: ['Futures', 'Forex', 'Stocks', 'Crypto'],
    pricing: {
      free: true,
      freeTrial: true,
      monthlyPrice: 75,
      yearlyPrice: 900,
      currency: 'USD'
    },
    features: {
      realTimeData: true,
      alerts: true,
      backtesting: true,
      paperTrading: true,
      mobileApp: false,
      apiAccess: true,
      customIndicators: true,
      socialTrading: false,
      newsFeed: false,
      optionsFlow: false,
      darkPoolData: false,
      institutionalData: true,
      sentimentAnalysis: false,
      automatedTrading: true
    },
    dataProviders: ['Rithmic', 'CQG/Continuum', 'dxFeed', 'Interactive Brokers', 'Binance', 'Bybit', 'Bitfinex', 'BitMEX'],
    supportedPlatforms: ['Desktop', 'Web', 'API'],
    dataLatency: '< 50ms',
    updateFrequency: 'Real-time',
    overview: 'ATAS (Advanced Time And Sales) is a professional trading platform designed for in-depth volume and order flow analysis. Features comprehensive volume profile analysis with Market Profile & TPO indicators, cluster charts (footprint) with Bid x Ask, Delta, and Volume modes, order flow tools including Order Book and Time & Sales, Depth of Market (DOM) with heatmap visualization, VWAP/TWAP indicators, and extensive market connectivity. Supports futures, forex, stocks, and cryptocurrency markets with free crypto trading access.',
    pros: [
      'Comprehensive volume profile analysis',
      'Advanced cluster charts (footprint)',
      'Real-time order flow visualization',
      'Depth of Market (DOM) with heatmap',
      'VWAP/TWAP indicators',
      'Extensive market connectivity',
      'Free crypto trading access',
      'Customizable indicators',
      'Professional market microstructure tools',
      'Intuitive interface design',
      'Responsive support team',
      'Lifetime license option available'
    ],
    cons: [
      'Desktop-only (no mobile app)',
      'Steep learning curve',
      'Higher pricing for premium features',
      'No social trading features',
      'Complex interface for beginners',
      'Limited to specific market types'
    ],
    bestFor: [
      'Futures traders',
      'Forex traders',
      'Crypto traders',
      'Order flow specialists',
      'Volume analysis experts',
      'Professional traders',
      'Market microstructure analysts',
      'Institutional traders'
    ],
    deal: {
      description: 'Free crypto trading + Lifetime license: €1,790 (one-time payment)',
      isTopDeal: true
    }
  }
];
